# Generated by Django 5.2.7 on 2026-01-18 07:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO 4217 currency code (USD, EUR, CAD, etc.)', max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2, help_text='Number of decimal places for this currency', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this currency is available for new transactions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=8, help_text='Exchange rate from source to target currency', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('date', models.DateField(help_text='Date this rate is effective for')),
                ('source', models.CharField(default='api', help_text='Source of exchange rate (api, manual, etc.)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_from', to='payments.currency')),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_to', to='payments.currency')),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'ordering': ['-date', 'from_currency'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('card', 'Credit/Debit Card'), ('bank_account', 'Bank Account'), ('wallet', 'Digital Wallet'), ('other', 'Other')], default='card', max_length=20)),
                ('card_brand', models.CharField(blank=True, max_length=50)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('card_exp_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('card_exp_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_last4', models.CharField(blank=True, max_length=4)),
                ('stripe_payment_method_id', models.CharField(blank=True, max_length=255, unique=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, help_text='Unique transaction identifier (auto-generated)', max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount in original currency', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('amount_usd', models.DecimalField(decimal_places=2, editable=False, help_text='Amount normalized to USD for reporting', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], db_index=True, default='pending', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('stripe_charge_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('stripe_transfer_id', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('succeeded_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('currency', models.ForeignKey(help_text='Currency of the transaction', on_delete=django.db.models.deletion.PROTECT, to='payments.currency')),
                ('exchange_rate', models.ForeignKey(blank=True, help_text='Exchange rate used for this transaction', null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.exchangerate')),
                ('payee', models.ForeignKey(help_text='User receiving the payment', on_delete=django.db.models.deletion.PROTECT, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
                ('payer', models.ForeignKey(help_text='User making the payment', on_delete=django.db.models.deletion.PROTECT, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payments.paymentmethod')),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('requires_payment_method', 'Requires Payment Method'), ('requires_confirmation', 'Requires Confirmation'), ('requires_action', 'Requires Action'), ('processing', 'Processing'), ('requires_capture', 'Requires Capture'), ('canceled', 'Canceled'), ('succeeded', 'Succeeded')], db_index=True, max_length=30)),
                ('client_secret', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentmethod')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_intent', to='payments.paymenttransaction')),
            ],
            options={
                'verbose_name': 'Payment Intent',
                'verbose_name_plural': 'Payment Intents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_id', models.CharField(db_index=True, help_text='Unique refund identifier (auto-generated)', max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Refund amount (can be partial)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=20)),
                ('reason', models.CharField(choices=[('duplicate', 'Duplicate Payment'), ('fraudulent', 'Fraudulent'), ('requested_by_customer', 'Requested by Customer'), ('service_not_provided', 'Service Not Provided'), ('product_defect', 'Product Defect'), ('other', 'Other')], default='requested_by_customer', max_length=50)),
                ('reason_details', models.TextField(blank=True)),
                ('stripe_refund_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_requested', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.paymenttransaction')),
            ],
            options={
                'verbose_name': 'Refund Request',
                'verbose_name_plural': 'Refund Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['code'], name='payments_cu_code_e21106_idx'),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['is_active'], name='payments_cu_is_acti_8ca675_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['from_currency', 'to_currency', 'date'], name='payments_ex_from_cu_4819c1_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['-date'], name='payments_ex_date_378d7f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('from_currency', 'to_currency', 'date')},
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['user', 'is_active'], name='payments_pa_user_id_bd2d73_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['stripe_payment_method_id'], name='payments_pa_stripe__ffc15c_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['transaction_id'], name='payments_pa_transac_c1fd68_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status', '-created_at'], name='payments_pa_status_a2ce56_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payer', '-created_at'], name='payments_pa_payer_i_f4192e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payee', '-created_at'], name='payments_pa_payee_i_dd1986_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['stripe_payment_intent_id'], name='payments_pa_stripe__3365e3_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['content_type', 'object_id'], name='payments_pa_content_51b568_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['stripe_payment_intent_id'], name='payments_pa_stripe__02a25f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['customer', '-created_at'], name='payments_pa_custome_df97cc_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['status', '-created_at'], name='payments_pa_status_6cb6dd_idx'),
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['refund_id'], name='payments_re_refund__0b6000_idx'),
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['transaction', '-requested_at'], name='payments_re_transac_5e1a13_idx'),
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['status', '-requested_at'], name='payments_re_status_fd703c_idx'),
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['stripe_refund_id'], name='payments_re_stripe__8ad3b7_idx'),
        ),
    ]
