# Generated by Django 5.2.7 on 2026-01-18 07:40

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicProjectStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(help_text='Date of this snapshot', unique=True)),
                ('total_projects', models.PositiveIntegerField(default=0)),
                ('open_projects', models.PositiveIntegerField(default=0)),
                ('total_companies', models.PositiveIntegerField(default=0)),
                ('by_category', models.JSONField(default=dict, help_text='Project counts by category')),
                ('by_country', models.JSONField(default=dict, help_text='Project counts by country')),
                ('by_budget_range', models.JSONField(default=dict, help_text='Project counts by budget range')),
                ('avg_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('avg_duration_weeks', models.FloatField(blank=True, null=True)),
                ('avg_proposals_per_project', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Public Project Stats',
                'verbose_name_plural': 'Public Project Stats',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='PublicProjectCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('tenant_project_id', models.IntegerField(help_text='Original project ID in tenant schema')),
                ('tenant_id', models.IntegerField(help_text='Tenant ID that posted this project')),
                ('tenant_schema', models.CharField(help_text='Tenant schema name', max_length=100)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('category_name', models.CharField(db_index=True, max_length=100)),
                ('category_slug', models.SlugField(max_length=120)),
                ('required_skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('experience_level', models.CharField(db_index=True, max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('estimated_duration_weeks', models.PositiveIntegerField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, db_index=True, null=True)),
                ('budget_type', models.CharField(db_index=True, max_length=20)),
                ('budget_min', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_max', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_currency', models.CharField(default='CAD', max_length=3)),
                ('location_type', models.CharField(db_index=True, max_length=20)),
                ('location_city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('location_country', models.CharField(blank=True, db_index=True, max_length=100)),
                ('location_coordinates', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Geographic coordinates for location-based search', null=True, srid=4326)),
                ('company_name', models.CharField(db_index=True, max_length=255)),
                ('company_logo_url', models.URLField(blank=True)),
                ('company_domain', models.CharField(max_length=253)),
                ('max_proposals', models.PositiveIntegerField(default=20)),
                ('proposal_count', models.PositiveIntegerField(default=0)),
                ('proposal_deadline', models.DateTimeField(blank=True, null=True)),
                ('is_open', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Public Project',
                'verbose_name_plural': 'Public Project Catalog',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['is_open', '-published_at'], name='projects_pu_is_open_a62bee_idx'), models.Index(fields=['category_slug', 'is_open'], name='projects_pu_categor_336ca9_idx'), models.Index(fields=['location_country', 'is_open'], name='projects_pu_locatio_a8f065_idx'), models.Index(fields=['budget_max', 'is_open'], name='projects_pu_budget__c0a451_idx'), models.Index(fields=['category_slug', 'location_type', 'is_open'], name='projects_pu_categor_62f19c_idx'), models.Index(fields=['experience_level', 'budget_type', 'is_open'], name='projects_pu_experie_ec36be_idx'), models.Index(fields=['tenant_id', 'tenant_project_id'], name='projects_pu_tenant__6b48bb_idx')],
                'unique_together': {('tenant_id', 'tenant_project_id')},
            },
        ),
    ]
