# Generated by Django 5.2.7 on 2026-01-18 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billinghistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, help_text='User who initiated the change', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billinghistory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_history', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='platforminvoice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_invoices', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='billinghistory',
            name='new_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_new_plan', to='billing.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='billinghistory',
            name='old_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_old_plan', to='billing.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_subscriptions', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='platforminvoice',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.tenantsubscription'),
        ),
        migrations.AddField(
            model_name='billinghistory',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='billing.tenantsubscription'),
        ),
        migrations.AddIndex(
            model_name='tenantsubscription',
            index=models.Index(fields=['tenant', 'status'], name='billing_ten_tenant__418b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantsubscription',
            index=models.Index(fields=['status', 'current_period_end'], name='billing_ten_status_170394_idx'),
        ),
        migrations.AddIndex(
            model_name='platforminvoice',
            index=models.Index(fields=['tenant', 'status'], name='billing_pla_tenant__f1c904_idx'),
        ),
        migrations.AddIndex(
            model_name='platforminvoice',
            index=models.Index(fields=['invoice_date'], name='billing_pla_invoice_44cacd_idx'),
        ),
        migrations.AddIndex(
            model_name='platforminvoice',
            index=models.Index(fields=['due_date', 'status'], name='billing_pla_due_dat_b20f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='billinghistory',
            index=models.Index(fields=['subscription', '-created_at'], name='billing_bil_subscri_ddae66_idx'),
        ),
        migrations.AddIndex(
            model_name='billinghistory',
            index=models.Index(fields=['tenant', '-created_at'], name='billing_bil_tenant__e9ccfc_idx'),
        ),
    ]
