# Generated by Django 5.2.7 on 2026-01-18 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0001_initial'),
        ('jobs', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='careersite',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this object belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='careercustompage',
            name='career_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_pages', to='careers.careersite'),
        ),
        migrations.AddField(
            model_name='jobalert',
            name='career_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_alerts', to='careers.careersite'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='career_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_listings', to='careers.careersite'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_listing', to='jobs.jobposting'),
        ),
        migrations.AddField(
            model_name='jobview',
            name='job_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='careers.joblisting'),
        ),
        migrations.AddField(
            model_name='publicapplication',
            name='ats_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.application'),
        ),
        migrations.AddField(
            model_name='publicapplication',
            name='ats_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.candidate'),
        ),
        migrations.AddField(
            model_name='publicapplication',
            name='career_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='careers.careersite'),
        ),
        migrations.AddField(
            model_name='publicapplication',
            name='job_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='public_applications', to='careers.joblisting'),
        ),
        migrations.AddField(
            model_name='talentpool',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='talentpoolmember',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='talentpoolmember',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_pools', to='jobs.candidate'),
        ),
        migrations.AddField(
            model_name='talentpoolmember',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='careers.talentpool'),
        ),
        migrations.AlterUniqueTogether(
            name='careercustompage',
            unique_together={('career_site', 'slug')},
        ),
        migrations.AddIndex(
            model_name='jobalert',
            index=models.Index(fields=['status', 'frequency'], name='careers_job_status_fcea36_idx'),
        ),
        migrations.AddIndex(
            model_name='jobalert',
            index=models.Index(fields=['confirmation_token'], name='careers_job_confirm_f63f52_idx'),
        ),
        migrations.AddIndex(
            model_name='jobalert',
            index=models.Index(fields=['unsubscribe_token'], name='careers_job_unsubsc_9c5814_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobalert',
            unique_together={('career_site', 'email')},
        ),
        migrations.AddIndex(
            model_name='jobview',
            index=models.Index(fields=['job_listing', 'viewed_at'], name='careers_job_job_lis_390a3a_idx'),
        ),
        migrations.AddIndex(
            model_name='jobview',
            index=models.Index(fields=['viewed_at'], name='careers_job_viewed__0c1ebc_idx'),
        ),
        migrations.AddIndex(
            model_name='publicapplication',
            index=models.Index(fields=['email', 'job_listing'], name='careers_pub_email_905352_idx'),
        ),
        migrations.AddIndex(
            model_name='publicapplication',
            index=models.Index(fields=['status', 'submitted_at'], name='careers_pub_status_f03604_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='talentpoolmember',
            unique_together={('pool', 'candidate')},
        ),
    ]
