# Generated by Django 5.2.7 on 2026-01-02 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('ats', '0001_initial'),
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiringanalytics',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hiring_analytics', to='configurations.department'),
        ),
        migrations.AddField(
            model_name='hiringfunnelmetric',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funnel_metrics', to='ats.jobposting'),
        ),
    ]
