# Generated by Django 5.2.7 on 2026-01-18 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hiringfunnelmetric',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funnel_metrics', to='jobs.jobposting'),
        ),
        migrations.AddField(
            model_name='pageview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='performancedistribution',
            index=models.Index(fields=['review_cycle', '-period_start'], name='analytics_p_review__1ba0db_idx'),
        ),
        migrations.AddIndex(
            model_name='performancedistribution',
            index=models.Index(fields=['department', '-period_start'], name='analytics_p_departm_f7895b_idx'),
        ),
        migrations.AddField(
            model_name='recruiterperformancemetric',
            name='recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_performance_metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruitingfunnel',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funnel_analytics', to='jobs.pipeline'),
        ),
        migrations.AddIndex(
            model_name='recruitmentmetric',
            index=models.Index(fields=['period_type', 'period_start'], name='analytics_r_period__d85cbe_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentmetric',
            index=models.Index(fields=['-period_start'], name='analytics_r_period__1ce900_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recruitmentmetric',
            unique_together={('period_type', 'period_start')},
        ),
        migrations.AddField(
            model_name='searchquery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_queries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sourceeffectivenessmetric',
            index=models.Index(fields=['-period_start', 'source'], name='analytics_s_period__150fd2_idx'),
        ),
        migrations.AddIndex(
            model_name='sourceeffectivenessmetric',
            index=models.Index(fields=['source', '-effectiveness_score'], name='analytics_s_source_ffa685_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sourceeffectivenessmetric',
            unique_together={('period_start', 'period_end', 'source', 'source_detail')},
        ),
        migrations.AddIndex(
            model_name='tenantdashboardmetric',
            index=models.Index(fields=['tenant_id', 'metric_type', '-period_start'], name='analytics_t_tenant__47973a_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantdashboardmetric',
            index=models.Index(fields=['metric_type', 'dimension', '-period_start'], name='analytics_t_metric__37a79f_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantdashboardmetric',
            index=models.Index(fields=['computed_at'], name='analytics_t_compute_7e01d1_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantdashboardmetric',
            index=models.Index(fields=['is_stale'], name='analytics_t_is_stal_44a621_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantdashboardmetric',
            unique_together={('tenant_id', 'metric_type', 'dimension', 'dimension_value', 'period_start')},
        ),
        migrations.AddIndex(
            model_name='timeoffanalytics',
            index=models.Index(fields=['period_type', '-period_start'], name='analytics_t_period__dcebb4_idx'),
        ),
        migrations.AddIndex(
            model_name='timeoffanalytics',
            index=models.Index(fields=['department', '-period_start'], name='analytics_t_departm_42320d_idx'),
        ),
        migrations.AddIndex(
            model_name='timetohiremetric',
            index=models.Index(fields=['-period_start'], name='analytics_t_period__887e3c_idx'),
        ),
        migrations.AddIndex(
            model_name='timetohiremetric',
            index=models.Index(fields=['department', '-period_start'], name='analytics_t_departm_f4cdb5_idx'),
        ),
        migrations.AddField(
            model_name='useraction',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='useraction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='hiringanalytics',
            index=models.Index(fields=['tenant_id', 'department', '-period_date'], name='analytics_h_tenant__af8e14_idx'),
        ),
        migrations.AddIndex(
            model_name='hiringanalytics',
            index=models.Index(fields=['period', '-period_date'], name='analytics_h_period_121e65_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hiringanalytics',
            unique_together={('tenant_id', 'department', 'period', 'period_date')},
        ),
        migrations.AddIndex(
            model_name='hiringfunnelmetric',
            index=models.Index(fields=['-period_start'], name='analytics_h_period__0126b1_idx'),
        ),
        migrations.AddIndex(
            model_name='hiringfunnelmetric',
            index=models.Index(fields=['job', '-period_start'], name='analytics_h_job_id_ae2ef9_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['path', '-timestamp'], name='analytics_p_path_89b690_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['user', '-timestamp'], name='analytics_p_user_id_3b7646_idx'),
        ),
        migrations.AddIndex(
            model_name='recruiterperformancemetric',
            index=models.Index(fields=['tenant_id', 'recruiter', '-period_start'], name='analytics_r_tenant__bfd35f_idx'),
        ),
        migrations.AddIndex(
            model_name='recruiterperformancemetric',
            index=models.Index(fields=['-period_start', '-performance_score'], name='analytics_r_period__e59a91_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitingfunnel',
            index=models.Index(fields=['tenant_id', 'pipeline', '-period_start'], name='analytics_r_tenant__89fde2_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitingfunnel',
            index=models.Index(fields=['-period_start'], name='analytics_r_period__7591d1_idx'),
        ),
        migrations.AddIndex(
            model_name='useraction',
            index=models.Index(fields=['user', 'action_type', '-timestamp'], name='analytics_u_user_id_84842d_idx'),
        ),
        migrations.AddIndex(
            model_name='useraction',
            index=models.Index(fields=['action_type', '-timestamp'], name='analytics_u_action__aab89a_idx'),
        ),
    ]
