# Generated by Django 5.2.7 on 2026-01-09 23:05

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingtaskprogress',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='User currently assigned to complete this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_onboarding_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onboardingtaskprogress',
            name='reassignment_history',
            field=models.JSONField(blank=True, default=list, help_text='History of task reassignments'),
        ),
        migrations.AlterField(
            model_name='onboardingtaskprogress',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_onboarding_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PerformanceImprovementPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('extended', 'Extended'), ('completed_success', 'Completed Successfully'), ('completed_fail', 'Completed Unsuccessfully'), ('terminated', 'Terminated'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('reason', models.TextField(help_text='Detailed reason for placing employee on PIP')),
                ('performance_concerns', models.JSONField(blank=True, default=list, help_text='List of specific performance concerns')),
                ('goals', models.JSONField(blank=True, default=list, help_text='Improvement goals with measurable targets')),
                ('support_provided', models.TextField(blank=True, help_text='Resources and support provided to employee')),
                ('expectations', models.TextField(blank=True, help_text='Clear expectations for improvement')),
                ('start_date', models.DateField()),
                ('target_end_date', models.DateField()),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('check_in_frequency_days', models.PositiveIntegerField(default=7, help_text='Days between check-in meetings')),
                ('next_check_in', models.DateField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('improved', 'Improved - PIP Closed'), ('terminated', 'Terminated'), ('demoted', 'Demoted'), ('transferred', 'Transferred'), ('extended', 'Extended'), ('resigned', 'Resigned During PIP')], default='pending', max_length=20)),
                ('final_assessment', models.TextField(blank=True)),
                ('final_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('employee_acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('manager_signed_at', models.DateTimeField(blank=True, null=True)),
                ('hr_signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pips', to='hr_core.employee')),
                ('hr_representative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_pips', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_pips', to=settings.AUTH_USER_MODEL)),
                ('source_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resulting_pips', to='hr_core.performancereview')),
            ],
            options={
                'verbose_name': 'Performance Improvement Plan',
                'verbose_name_plural': 'Performance Improvement Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PIPMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('success_criteria', models.TextField(blank=True, help_text='How success will be measured')),
                ('due_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('achieved', 'Achieved'), ('not_achieved', 'Not Achieved'), ('deferred', 'Deferred')], default='pending', max_length=20)),
                ('progress_notes', models.TextField(blank=True)),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='hr_core.performanceimprovementplan')),
            ],
            options={
                'verbose_name': 'PIP Milestone',
                'verbose_name_plural': 'PIP Milestones',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='PIPProgressNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('check_in', 'Check-in Meeting'), ('progress_update', 'Progress Update'), ('concern', 'Concern Raised'), ('achievement', 'Achievement'), ('extension', 'Extension'), ('formal_warning', 'Formal Warning'), ('other', 'Other')], default='progress_update', max_length=20)),
                ('content', models.TextField()),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('attendees', models.JSONField(blank=True, default=list)),
                ('action_items', models.JSONField(blank=True, default=list)),
                ('employee_response', models.TextField(blank=True)),
                ('employee_responded_at', models.DateTimeField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pip_notes_authored', to=settings.AUTH_USER_MODEL)),
                ('pip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_notes', to='hr_core.performanceimprovementplan')),
            ],
            options={
                'verbose_name': 'PIP Progress Note',
                'verbose_name_plural': 'PIP Progress Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
