# Generated by Django 5.2.7 on 2026-01-18 07:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr_core', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('requires_receipt', models.BooleanField(default=True, help_text='Whether receipts are required for this category')),
                ('requires_justification', models.BooleanField(default=False, help_text='Whether additional justification is required')),
                ('daily_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Daily spending limit for this category (null = no limit)', max_digits=10, null=True)),
                ('monthly_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly spending limit for this category (null = no limit)', max_digits=10, null=True)),
                ('is_taxable', models.BooleanField(default=True, help_text='Whether expenses in this category are taxable to employee')),
                ('gl_code', models.CharField(blank=True, help_text='General ledger code for accounting', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='expenses.expensecategory')),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Expense Category',
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(db_index=True, help_text='Unique expense report number (auto-generated)', max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('purpose', models.TextField(blank=True, help_text='Business purpose of expenses')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid')], db_index=True, default='draft', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total expense amount', max_digits=12)),
                ('reimbursable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount to be reimbursed to employee', max_digits=12)),
                ('non_reimbursable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Non-reimbursable amount (e.g., personal expenses)', max_digits=12)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('employee_notes', models.TextField(blank=True)),
                ('approver_notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_reports', to='hr_core.employee')),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Expense Report',
                'verbose_name_plural': 'Expense Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('general', 'General Expense'), ('mileage', 'Mileage'), ('per_diem', 'Per Diem')], default='general', max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('expense_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('merchant', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, help_text='City, state, or country', max_length=200)),
                ('mileage_distance', models.DecimalField(blank=True, decimal_places=2, help_text='Distance in miles/km', max_digits=8, null=True)),
                ('mileage_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Rate per mile/km', max_digits=6, null=True)),
                ('mileage_start_location', models.CharField(blank=True, max_length=200)),
                ('mileage_end_location', models.CharField(blank=True, max_length=200)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='expense_receipts/%Y/%m/')),
                ('receipt_url', models.URLField(blank=True)),
                ('is_reimbursable', models.BooleanField(default=True, help_text='Whether this expense should be reimbursed')),
                ('is_billable', models.BooleanField(default=False, help_text='Whether this expense is billable to a client')),
                ('client_name', models.CharField(blank=True, help_text='Client to bill (if billable)', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_items', to='expenses.expensecategory')),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('expense_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='expenses.expensereport')),
            ],
            options={
                'verbose_name': 'Expense Line Item',
                'verbose_name_plural': 'Expense Line Items',
                'ordering': ['expense_date'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver_role', models.CharField(help_text='Role of approver (Manager, Department Head, Finance, etc.)', max_length=50)),
                ('approval_level', models.PositiveSmallIntegerField(default=1, help_text='Approval level (1 = first level, 2 = second level, etc.)')),
                ('action', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned for Revision')], db_index=True, default='pending', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_approvals_given', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('expense_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='expenses.expensereport')),
            ],
            options={
                'verbose_name': 'Expense Approval',
                'verbose_name_plural': 'Expense Approvals',
                'ordering': ['approval_level', 'requested_at'],
            },
        ),
        migrations.CreateModel(
            name='MileageRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='US', max_length=2)),
                ('region', models.CharField(blank=True, help_text='State, province, or region', max_length=100)),
                ('rate', models.DecimalField(decimal_places=4, help_text='Rate per mile/km', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('unit', models.CharField(choices=[('mile', 'Mile'), ('km', 'Kilometer')], default='mile', max_length=10)),
                ('purpose', models.CharField(choices=[('business', 'Business'), ('medical', 'Medical/Moving'), ('charity', 'Charity')], default='business', max_length=50)),
                ('effective_start', models.DateField()),
                ('effective_end', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Mileage Rate',
                'verbose_name_plural': 'Mileage Rates',
                'ordering': ['-effective_start'],
            },
        ),
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reimbursement_id', models.CharField(db_index=True, help_text='Unique reimbursement identifier (auto-generated)', max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Reimbursement amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('direct_deposit', 'Direct Deposit'), ('check', 'Check'), ('payroll', 'Include in Next Payroll')], default='direct_deposit', max_length=20)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reimbursements', to='hr_core.employee')),
                ('expense_report', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reimbursement', to='expenses.expensereport')),
            ],
            options={
                'verbose_name': 'Reimbursement',
                'verbose_name_plural': 'Reimbursements',
                'ordering': ['-created_at'],
            },
        ),
    ]
