# Generated by Django 5.2.7 on 2026-01-18 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
        ('payments', '0001_initial'),
        ('payroll', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='payment_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_reimbursements', to='payments.paymenttransaction'),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='payroll_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_reimbursements', to='payroll.payrollrun'),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['slug'], name='expenses_ex_slug_55fd7c_idx'),
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['is_active'], name='expenses_ex_is_acti_8ba8b6_idx'),
        ),
        migrations.AddIndex(
            model_name='expensereport',
            index=models.Index(fields=['report_number'], name='expenses_ex_report__bb0192_idx'),
        ),
        migrations.AddIndex(
            model_name='expensereport',
            index=models.Index(fields=['employee', 'status'], name='expenses_ex_employe_4717eb_idx'),
        ),
        migrations.AddIndex(
            model_name='expensereport',
            index=models.Index(fields=['status', '-created_at'], name='expenses_ex_status_8623ff_idx'),
        ),
        migrations.AddIndex(
            model_name='expenselineitem',
            index=models.Index(fields=['expense_report', 'expense_date'], name='expenses_ex_expense_f05c67_idx'),
        ),
        migrations.AddIndex(
            model_name='expenselineitem',
            index=models.Index(fields=['category', 'expense_date'], name='expenses_ex_categor_5035f5_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseapproval',
            index=models.Index(fields=['expense_report', 'approval_level'], name='expenses_ex_expense_8aa851_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseapproval',
            index=models.Index(fields=['approver', 'action'], name='expenses_ex_approve_0f1283_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='expenseapproval',
            unique_together={('expense_report', 'approval_level')},
        ),
        migrations.AddIndex(
            model_name='mileagerate',
            index=models.Index(fields=['country', 'effective_start'], name='expenses_mi_country_7937cd_idx'),
        ),
        migrations.AddIndex(
            model_name='mileagerate',
            index=models.Index(fields=['is_active', 'effective_start'], name='expenses_mi_is_acti_68bacc_idx'),
        ),
        migrations.AddIndex(
            model_name='reimbursement',
            index=models.Index(fields=['reimbursement_id'], name='expenses_re_reimbur_e34ae5_idx'),
        ),
        migrations.AddIndex(
            model_name='reimbursement',
            index=models.Index(fields=['employee', 'status'], name='expenses_re_employe_e55954_idx'),
        ),
        migrations.AddIndex(
            model_name='reimbursement',
            index=models.Index(fields=['status', '-created_at'], name='expenses_re_status_568d2e_idx'),
        ),
    ]
