# Generated by Django - Initial migration for tenants app
# Creates all tenant models for multi-tenancy support

import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.contrib.postgres.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Plan model
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('plan_type', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('stripe_price_id_monthly', models.CharField(blank=True, max_length=255)),
                ('stripe_price_id_yearly', models.CharField(blank=True, max_length=255)),
                ('stripe_product_id', models.CharField(blank=True, max_length=255)),
                ('max_users', models.PositiveIntegerField(default=5)),
                ('max_job_postings', models.PositiveIntegerField(default=10)),
                ('max_candidates_per_month', models.PositiveIntegerField(default=100)),
                ('max_circusales', models.PositiveIntegerField(default=1)),
                ('storage_limit_gb', models.PositiveIntegerField(default=5)),
                ('feature_ats', models.BooleanField(default=True)),
                ('feature_hr_core', models.BooleanField(default=False)),
                ('feature_analytics', models.BooleanField(default=False)),
                ('feature_api_access', models.BooleanField(default=False)),
                ('feature_custom_pipelines', models.BooleanField(default=False)),
                ('feature_ai_matching', models.BooleanField(default=False)),
                ('feature_video_interviews', models.BooleanField(default=False)),
                ('feature_esignature', models.BooleanField(default=False)),
                ('feature_sso', models.BooleanField(default=False)),
                ('feature_audit_logs', models.BooleanField(default=False)),
                ('feature_custom_branding', models.BooleanField(default=False)),
                ('feature_priority_support', models.BooleanField(default=False)),
                ('feature_data_export', models.BooleanField(default=True)),
                ('feature_bulk_actions', models.BooleanField(default=False)),
                ('feature_advanced_filters', models.BooleanField(default=False)),
                ('feature_diversity_analytics', models.BooleanField(default=False)),
                ('feature_compliance_tools', models.BooleanField(default=False)),
                ('feature_marketplace', models.BooleanField(default=False)),
                ('feature_escrow_payments', models.BooleanField(default=False)),
                ('feature_real_time_messaging', models.BooleanField(default=True)),
                ('feature_appointments', models.BooleanField(default=True)),
                ('feature_newsletter', models.BooleanField(default=False)),
                ('feature_crm', models.BooleanField(default=False)),
                ('feature_geospatial', models.BooleanField(default=False)),
                ('feature_multi_circusale', models.BooleanField(default=False)),
                ('feature_custom_domains', models.BooleanField(default=False)),
                ('feature_webhooks', models.BooleanField(default=False)),
                ('feature_2fa_required', models.BooleanField(default=False)),
                ('feature_ip_whitelist', models.BooleanField(default=False)),
                ('feature_wagtail_cms', models.BooleanField(default=False)),
                ('feature_career_pages', models.BooleanField(default=True)),
                ('feature_events', models.BooleanField(default=False)),
                ('feature_slack_integration', models.BooleanField(default=False)),
                ('feature_calendar_sync', models.BooleanField(default=False)),
                ('feature_linkedin_import', models.BooleanField(default=False)),
                ('feature_background_checks', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['sort_order', 'price_monthly'],
            },
        ),
        # Tenant model
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Setup'), ('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('trial', 'Trial')], default='trial', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('paid_until', models.DateTimeField(blank=True, null=True)),
                ('on_trial', models.BooleanField(default=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255)),
                ('owner_email', models.EmailField(max_length=254)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('company_size', models.CharField(blank=True, choices=[('1-10', '1-10'), ('11-50', '11-50'), ('51-200', '51-200'), ('201-500', '201-500'), ('501-1000', '501-1000'), ('1000+', '1000+')], max_length=20)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenant_logos/')),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, default='CA', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='tenants.plan')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['-created_at'],
            },
        ),
        # Domain model
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('is_careers_domain', models.BooleanField(default=False)),
                ('ssl_enabled', models.BooleanField(default=True)),
                ('ssl_certificate', models.TextField(blank=True)),
                ('ssl_private_key', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
            },
        ),
    ]
