# Generated by Django - Additional tenant models
# TenantSettings, TenantUsage, AuditLog, Circusale, CircusaleUser, TenantInvitation

import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.contrib.postgres.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # TenantSettings model
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#3B82F6', max_length=7)),
                ('secondary_color', models.CharField(default='#1E40AF', max_length=7)),
                ('accent_color', models.CharField(default='#10B981', max_length=7)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='tenant_favicons/')),
                ('default_language', models.CharField(default='en', max_length=10)),
                ('default_timezone', models.CharField(default='America/Toronto', max_length=50)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=20)),
                ('time_format', models.CharField(choices=[('12h', '12-hour'), ('24h', '24-hour')], default='24h', max_length=10)),
                ('currency', models.CharField(default='CAD', max_length=3)),
                ('default_pipeline_stages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('require_cover_letter', models.BooleanField(default=False)),
                ('auto_reject_after_days', models.PositiveIntegerField(default=0)),
                ('send_rejection_email', models.BooleanField(default=True)),
                ('fiscal_year_start_month', models.PositiveSmallIntegerField(default=1)),
                ('default_pto_days', models.PositiveIntegerField(default=15)),
                ('approval_workflow_enabled', models.BooleanField(default=True)),
                ('require_2fa', models.BooleanField(default=False)),
                ('session_timeout_minutes', models.PositiveIntegerField(default=480)),
                ('password_expiry_days', models.PositiveIntegerField(default=0)),
                ('allowed_email_domains', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('ip_whitelist', django.contrib.postgres.fields.ArrayField(base_field=models.GenericIPAddressField(), blank=True, default=list, size=None)),
                ('notify_new_application', models.BooleanField(default=True)),
                ('notify_interview_scheduled', models.BooleanField(default=True)),
                ('notify_offer_accepted', models.BooleanField(default=True)),
                ('daily_digest_enabled', models.BooleanField(default=False)),
                ('career_page_enabled', models.BooleanField(default=True)),
                ('career_page_title', models.CharField(default='Careers', max_length=200)),
                ('career_page_description', models.TextField(blank=True)),
                ('career_page_custom_css', models.TextField(blank=True)),
                ('show_salary_range', models.BooleanField(default=False)),
                ('integration_slack_enabled', models.BooleanField(default=False)),
                ('integration_slack_webhook', models.URLField(blank=True)),
                ('integration_calendar_enabled', models.BooleanField(default=False)),
                ('integration_calendar_provider', models.CharField(blank=True, choices=[('google', 'Google Calendar'), ('outlook', 'Outlook Calendar')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Settings',
                'verbose_name_plural': 'Tenant Settings',
            },
        ),
        # TenantUsage model
        migrations.CreateModel(
            name='TenantUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_count', models.PositiveIntegerField(default=0)),
                ('active_job_count', models.PositiveIntegerField(default=0)),
                ('total_job_count', models.PositiveIntegerField(default=0)),
                ('candidate_count_this_month', models.PositiveIntegerField(default=0)),
                ('total_candidate_count', models.PositiveIntegerField(default=0)),
                ('circusale_count', models.PositiveIntegerField(default=0)),
                ('employee_count', models.PositiveIntegerField(default=0)),
                ('storage_used_bytes', models.BigIntegerField(default=0)),
                ('api_calls_this_month', models.PositiveIntegerField(default=0)),
                ('last_calculated_at', models.DateTimeField(auto_now=True)),
                ('month_reset_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Usage',
                'verbose_name_plural': 'Tenant Usage',
            },
        ),
        # AuditLog model
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Export'), ('permission_change', 'Permission Change'), ('setting_change', 'Setting Change')], max_length=30)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenants.tenant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['tenant', 'created_at'], name='tenants_aud_tenant__e5cfb8_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['tenant', 'action'], name='tenants_aud_tenant__5f0a1c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['tenant', 'resource_type'], name='tenants_aud_tenant__c5c06f_idx'),
        ),
        # Circusale model
        migrations.CreateModel(
            name='Circusale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending Setup')], default='active', max_length=20)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, default='CA', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='CAD', max_length=3)),
                ('cost_center', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('manager_name', models.CharField(blank=True, max_length=100)),
                ('timezone', models.CharField(default='America/Toronto', max_length=50)),
                ('is_headquarters', models.BooleanField(default=False)),
                ('accepts_applications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='tenants.circusale')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circusales', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Circusale',
                'verbose_name_plural': 'Circusales',
                'ordering': ['name'],
                'unique_together': {('tenant', 'slug')},
            },
        ),
        migrations.AddIndex(
            model_name='circusale',
            index=models.Index(fields=['tenant', 'status'], name='tenants_cir_tenant__bae02c_idx'),
        ),
        migrations.AddIndex(
            model_name='circusale',
            index=models.Index(fields=['tenant', 'is_headquarters'], name='tenants_cir_tenant__c2c0f2_idx'),
        ),
        # CircusaleUser model
        migrations.CreateModel(
            name='CircusaleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('supervisor', 'Supervisor'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('circusale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tenants.circusale')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circusale_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Circusale User',
                'verbose_name_plural': 'Circusale Users',
                'unique_together': {('user', 'circusale')},
            },
        ),
        # TenantInvitation model
        migrations.CreateModel(
            name='TenantInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(default='member', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Invitation',
                'verbose_name_plural': 'Tenant Invitations',
                'unique_together': {('tenant', 'email')},
            },
        ),
    ]
