# Generated by Django 5.2.7 on 2026-01-12 02:10

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_add_public_job_provider_catalogs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicjobcatalog',
            options={'ordering': ['-is_featured', '-published_at'], 'verbose_name': 'Public Job Catalog Entry', 'verbose_name_plural': 'Public Job Catalog'},
        ),
        migrations.AlterModelOptions(
            name='publicprovidercatalog',
            options={'ordering': ['-is_featured', '-rating_avg', '-published_at'], 'verbose_name': 'Public Provider Catalog Entry', 'verbose_name_plural': 'Public Provider Catalog'},
        ),
        migrations.RemoveIndex(
            model_name='publicjobcatalog',
            name='jcat_type_remote',
        ),
        migrations.RemoveIndex(
            model_name='publicjobcatalog',
            name='jcat_category',
        ),
        migrations.RenameIndex(
            model_name='publicjobcatalog',
            new_name='job_catalog_tenant_featured',
            old_name='jcat_ten_featured',
        ),
        migrations.RenameIndex(
            model_name='publicjobcatalog',
            new_name='job_catalog_location',
            old_name='jcat_location',
        ),
        migrations.RenameIndex(
            model_name='publicjobcatalog',
            new_name='job_catalog_sync_ref',
            old_name='jcat_sync_ref',
        ),
        migrations.RenameIndex(
            model_name='publicjobcatalog',
            new_name='job_catalog_published',
            old_name='jcat_published',
        ),
        migrations.RemoveField(
            model_name='publicjobcatalog',
            name='currency',
        ),
        migrations.AddField(
            model_name='publicjobcatalog',
            name='application_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicjobcatalog',
            name='meta_description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='publicjobcatalog',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='publicjobcatalog',
            name='nice_to_have',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publicjobcatalog',
            name='salary_currency',
            field=models.CharField(default='CAD', max_length=3),
        ),
        migrations.AddField(
            model_name='publicjobcatalog',
            name='salary_period',
            field=models.CharField(default='yearly', help_text='hourly, daily, weekly, monthly, yearly', max_length=20),
        ),
        migrations.AddField(
            model_name='publicjobcatalog',
            name='show_salary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='publicjobcatalog',
            name='benefits',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='publicjobcatalog',
            name='category_name',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='publicjobcatalog',
            name='category_slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='publicjobcatalog',
            name='company_logo_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='publicjobcatalog',
            name='company_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='publicjobcatalog',
            name='description',
            field=models.TextField(blank=True, help_text='Sanitized HTML'),
        ),
        migrations.AlterField(
            model_name='publicjobcatalog',
            name='experience_level',
            field=models.CharField(db_index=True, help_text='entry, junior, mid, senior, lead, executive', max_length=20),
        ),
        migrations.AlterField(
            model_name='publicjobcatalog',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Featured jobs appear prominently on careers page'),
        ),
        migrations.AlterField(
            model_name='publicjobcatalog',
            name='job_type',
            field=models.CharField(db_index=True, help_text='full_time, part_time, contract, internship, temporary, freelance', max_length=20),
        ),
        migrations.AlterField(
            model_name='publicjobcatalog',
            name='job_uuid',
            field=models.UUIDField(db_index=True, help_text='UUID of job in tenant schema'),
        ),
        migrations.AlterField(
            model_name='publicjobcatalog',
            name='location_city',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='publicjobcatalog',
            name='location_coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='publicjobcatalog',
            name='location_country',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='publicjobcatalog',
            name='location_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='publicjobcatalog',
            name='positions_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='publicjobcatalog',
            name='preferred_skills',
            field=models.JSONField(blank=True, default=list, help_text='List of preferred skills'),
        ),
        migrations.AlterField(
            model_name='publicjobcatalog',
            name='published_at',
            field=models.DateTimeField(db_index=True, help_text='When job was first published to catalog'),
        ),
        migrations.AlterField(
            model_name='publicjobcatalog',
            name='reference_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='publicjobcatalog',
            name='remote_policy',
            field=models.CharField(db_index=True, help_text='on_site, remote, hybrid, flexible', max_length=20),
        ),
        migrations.AlterField(
            model_name='publicjobcatalog',
            name='required_skills',
            field=models.JSONField(blank=True, default=list, help_text='List of required skills'),
        ),
        migrations.AlterField(
            model_name='publicjobcatalog',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='publicjobcatalog',
            name='responsibilities',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='publicjobcatalog',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='publicjobcatalog',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Only included if job.show_salary=True', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='publicjobcatalog',
            name='slug',
            field=models.SlugField(blank=True, max_length=220),
        ),
        migrations.AlterField(
            model_name='publicjobcatalog',
            name='synced_at',
            field=models.DateTimeField(auto_now=True, help_text='Last sync timestamp from tenant schema'),
        ),
        migrations.AlterField(
            model_name='publicjobcatalog',
            name='team',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='publicjobcatalog',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant/company offering this job', on_delete=django.db.models.deletion.CASCADE, related_name='published_jobs', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='publicjobcatalog',
            name='tenant_schema_name',
            field=models.CharField(help_text='Schema name of tenant (for sync reference)', max_length=63),
        ),
        migrations.AlterField(
            model_name='publicjobcatalog',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='publicjobcatalog',
            name='uuid',
            field=models.UUIDField(db_index=True, help_text='Job UUID (same as source JobPosting)', unique=True),
        ),
        migrations.AlterField(
            model_name='publicprovidercatalog',
            name='availability_status',
            field=models.CharField(db_index=True, default='available', help_text='available, busy, unavailable', max_length=20),
        ),
        migrations.AlterField(
            model_name='publicprovidercatalog',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='publicprovidercatalog',
            name='avg_response_time_hours',
            field=models.PositiveSmallIntegerField(default=0, help_text='Average response time in hours'),
        ),
        migrations.AlterField(
            model_name='publicprovidercatalog',
            name='bio',
            field=models.TextField(blank=True, help_text='Sanitized bio (max 2000 chars)', max_length=2000),
        ),
        migrations.AlterField(
            model_name='publicprovidercatalog',
            name='can_work_onsite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='publicprovidercatalog',
            name='can_work_remotely',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='publicprovidercatalog',
            name='category_names',
            field=models.JSONField(blank=True, default=list, help_text='List of category names'),
        ),
        migrations.AlterField(
            model_name='publicprovidercatalog',
            name='category_slugs',
            field=models.JSONField(blank=True, default=list, help_text='List of category slugs for filtering'),
        ),
        migrations.AlterField(
            model_name='publicprovidercatalog',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='publicprovidercatalog',
            name='completed_jobs_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of completed projects/jobs'),
        ),
        migrations.AlterField(
            model_name='publicprovidercatalog',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='publicprovidercatalog',
            name='cover_image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='publicprovidercatalog',
            name='currency',
            field=models.CharField(default='CAD', max_length=3),
        ),
        migrations.AlterField(
            model_name='publicprovidercatalog',
            name='display_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='publicprovidercatalog',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate if applicable', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='publicprovidercatalog',
            name='is_accepting_projects',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='publicprovidercatalog',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Featured providers shown prominently'),
        ),
        migrations.AlterField(
            model_name='publicprovidercatalog',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False, help_text='KYC verified provider'),
        ),
        migrations.AlterField(
            model_name='publicprovidercatalog',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='publicprovidercatalog',
            name='minimum_budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum project budget', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='publicprovidercatalog',
            name='provider_type',
            field=models.CharField(db_index=True, help_text='individual, agency, company', max_length=20),
        ),
        migrations.AlterField(
            model_name='publicprovidercatalog',
            name='provider_uuid',
            field=models.UUIDField(db_index=True, help_text='UUID of provider in tenant schema'),
        ),
        migrations.AlterField(
            model_name='publicprovidercatalog',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When provider was first published to catalog'),
        ),
        migrations.AlterField(
            model_name='publicprovidercatalog',
            name='rating_avg',
            field=models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), help_text='Average rating across all reviews', max_digits=3),
        ),
        migrations.AlterField(
            model_name='publicprovidercatalog',
            name='response_rate',
            field=models.PositiveSmallIntegerField(default=0, help_text='Percentage of messages responded to (0-100)'),
        ),
        migrations.AlterField(
            model_name='publicprovidercatalog',
            name='skills_data',
            field=models.JSONField(blank=True, default=list, help_text='List of {name, level, years_experience} dicts'),
        ),
        migrations.AlterField(
            model_name='publicprovidercatalog',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='publicprovidercatalog',
            name='synced_at',
            field=models.DateTimeField(auto_now=True, help_text='Last sync timestamp from tenant schema'),
        ),
        migrations.AlterField(
            model_name='publicprovidercatalog',
            name='tagline',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='publicprovidercatalog',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant/company where provider operates', on_delete=django.db.models.deletion.CASCADE, related_name='published_providers', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='publicprovidercatalog',
            name='tenant_schema_name',
            field=models.CharField(help_text='Schema name of tenant (for sync reference)', max_length=63),
        ),
        migrations.AlterField(
            model_name='publicprovidercatalog',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0, help_text='Total number of reviews received'),
        ),
        migrations.AlterField(
            model_name='publicprovidercatalog',
            name='uuid',
            field=models.UUIDField(db_index=True, help_text='Provider UUID (same as source ServiceProvider)', unique=True),
        ),
        migrations.AddIndex(
            model_name='publicjobcatalog',
            index=models.Index(fields=['job_type', 'experience_level'], name='job_catalog_type_level'),
        ),
        migrations.AddIndex(
            model_name='publicjobcatalog',
            index=models.Index(fields=['remote_policy'], name='job_catalog_remote'),
        ),
    ]
