# Generated by Django 5.2.7 on 2026-01-15 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_add_location_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='geocode_attempted',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='geocode_error',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='location_coordinates',
        ),
    ]
