# Generated by Django 5.2.7 on 2026-01-11 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='post',
            new_name='message',
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('message', 'sortorder')},
        ),
    ]
