# Generated by Django 5.2.7 on 2026-01-18 07:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicJobCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Primary key for public catalog entry', primary_key=True, serialize=False)),
                ('jobposting_uuid', models.UUIDField(db_index=True, help_text='UUID of source JobPosting in tenant schema', unique=True)),
                ('tenant_id', models.IntegerField(db_index=True, help_text='ID of source tenant')),
                ('tenant_schema_name', models.CharField(db_index=True, help_text='Schema name of source tenant', max_length=100)),
                ('company_name', models.CharField(db_index=True, help_text='Company name from tenant', max_length=255)),
                ('company_logo_url', models.URLField(blank=True, help_text='Company logo URL (if available)')),
                ('title', models.CharField(db_index=True, help_text='Job title', max_length=255)),
                ('description_html', models.TextField(help_text='Sanitized HTML job description')),
                ('employment_type', models.CharField(blank=True, db_index=True, help_text='Employment type: full-time, part-time, contract, etc.', max_length=50)),
                ('location_city', models.CharField(blank=True, db_index=True, help_text='Job location city', max_length=100)),
                ('location_state', models.CharField(blank=True, help_text='Job location state/province', max_length=100)),
                ('location_country', models.CharField(blank=True, db_index=True, default='', help_text='Job location country', max_length=100)),
                ('is_remote', models.BooleanField(db_index=True, default=False, help_text='Whether job allows remote work')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum salary (optional)', max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum salary (optional)', max_digits=10, null=True)),
                ('salary_currency', models.CharField(default='USD', help_text='Salary currency code (ISO 4217)', max_length=3)),
                ('category_names', models.JSONField(default=list, help_text="List of category names (e.g., ['Engineering', 'Product'])")),
                ('category_slugs', models.JSONField(db_index=True, default=list, help_text="List of category slugs for filtering (e.g., ['engineering', 'product'])")),
                ('required_skills', models.JSONField(default=list, help_text="List of required skill names (e.g., ['Python', 'Django', 'React'])")),
                ('published_at', models.DateTimeField(db_index=True, help_text='When job was published on career page')),
                ('synced_at', models.DateTimeField(auto_now=True, help_text='When this catalog entry was last synced from tenant')),
                ('application_url', models.URLField(help_text='URL to apply for this job (redirects to tenant domain)')),
            ],
            options={
                'verbose_name': 'Public Job Catalog Entry',
                'verbose_name_plural': 'Public Job Catalog Entries',
                'db_table': 'ats_public_job_catalog',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['title'], name='ats_pub_title_idx'), models.Index(fields=['location_city', 'location_state'], name='ats_pub_location_idx'), models.Index(fields=['employment_type', 'is_remote'], name='ats_pub_type_idx'), models.Index(fields=['-published_at'], name='ats_pub_published_idx'), models.Index(fields=['company_name'], name='ats_pub_company_idx')],
            },
        ),
    ]
