from django.urls import path, include
from .views import *

urlpatterns = [
    path('', dashboard_view, name='dashboard'),
    path('alert/', include('dashboard_alert.urls')),
    path('service/', include('dashboard_service.urls')),
    path('project/', include('dashboard_project.urls')),
    path('allert/', include('dashboard_alert.urls')),
    path('account/', include('custom_account_u.urls')),
    path('candidates/active-work/', candidates_active_work, name='candidates_active_work'),
    path('candidates/applied/', candidates_applied, name='candidates_applied'),
    path('bookmarks/', bookmarks_view, name='bookmarks'),
    path('candidates/choose-package/', candidates_choose_package, name='candidates_choose_package'),
    path('candidates/default/', candidates_default, name='candidates_default'),
    path('candidates/detail1/', candidates_detail1, name='candidates_detail1'),
    path('candidates/detail2/', candidates_detail2, name='candidates_detail2'),
    path('candidates/earnings/', candidates_earnings, name='candidates_earnings'),
    path('candidates/fullwidth-grid/', candidates_fullwidth_grid, name='candidates_fullwidth_grid'),
    path('candidates/fullwidth-list/', candidates_fullwidth_list, name='candidates_fullwidth_list'),
    path('candidates/grid/', candidates_grid, name='candidates_grid'),
    path('candidates/half-map-grid/', candidates_half_map_grid, name='candidates_half_map_grid'),
    path('candidates/half-map-list/', candidates_half_map_list, name='candidates_half_map_list'),
    path('candidates/list/', candidates_list, name='candidates_list'),
    path('meetings/', meetings, name='meetings'),
    path('messages/', messages, name='messages'),
    path('payouts/', payouts, name='payouts'),
    path('candidates/proposals/', candidates_proposals, name='candidates_proposals'),
    path('candidates/sidebar-grid/', candidates_sidebar_grid, name='candidates_sidebar_grid'),
    path('candidates/sidebar-list/', candidates_sidebar_list, name='candidates_sidebar_list'),
    path('candidates/top-map-grid/', candidates_top_map_grid, name='candidates_top_map_grid'),
    path('candidates/top-map-list/', candidates_top_map_list, name='candidates_top_map_list'),
    path('employers/applicants-jobs/', employers_applicants_jobs, name='employers_applicants_jobs'),
    path('employers/billings/', employers_billings, name='employers_billings'),
    path('employers/choose-job-package/', employers_choose_job_package, name='employers_choose_job_package'),
    path('employers/choose-project-package/', employers_choose_project_package, name='employers_choose_project_package'),
    path('employers/default/', employers_default, name='employers_default'),
    path('employers/detail1/', employers_detail1, name='employers_detail1'),
    path('employers/detail2/', employers_detail2, name='employers_detail2'),
    path('employers/fullwidth/', employers_fullwidth, name='employers_fullwidth'),
    path('employers/grid/', employers_grid, name='employers_grid'),
    path('employers/half-map-grid/', employers_half_map_grid, name='employers_half_map_grid'),
    path('employers/half-map-list/', employers_half_map_list, name='employers_half_map_list'),
    path('employers/list/', employers_list, name='employers_list'),
    path('employers/my-projects/', employers_my_projects, name='employers_my_projects'),
    path('employers/proposals-projects/', employers_proposals_projects, name='employers_proposals_projects'),
    path('employers/sidebar-grid-2cols/', employers_sidebar_grid_2cols, name='employers_sidebar_grid_2cols'),
    path('employers/sidebar-grid-3cols/', employers_sidebar_grid_3cols, name='employers_sidebar_grid_3cols'),
    path('employers/sidebar-list/', employers_sidebar_list, name='employers_sidebar_list'),
    path('employers/submit-projects/', employers_submit_projects, name='employers_submit_projects'),
    path('employers/top-map-grid/', employers_top_map_grid, name='employers_top_map_grid'),
    path('employers/top-map-list/', employers_top_map_list, name='employers_top_map_list'),
    path('employers/view-proposals-projects/', employers_view_proposals_projects, name='employers_view_proposals_projects'),
    path('employers/view-service-detail/', employers_view_service_detail, name='employers_view_service_detail'),
]
