"""
Django settings for zumodra project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment variables
env = environ.Env()
environ.Env.read_env(str(BASE_DIR / '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['*'])

# Application definition
SHARED_APPS = [
    
]

TENANT_APPS = [
    'django.contrib.sites',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sitemaps',
    'django.contrib.gis',

    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_hotp',
    'django_otp.plugins.otp_email',
    'django_otp.plugins.otp_static',

    'allauth_2fa',
    'allauth',
    'allauth.mfa',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.linkedin',
]

INSTALLED_APPS = [
    'django.contrib.sites',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sitemaps',
    'django.contrib.gis',

    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_hotp',
    'django_otp.plugins.otp_email',
    'django_otp.plugins.otp_static',

    'allauth_2fa',
    'allauth',
    'allauth.mfa',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.linkedin',

    'widget_tweaks',
    'tinymce',
    'leaflet',
    # 'campaign',

    'analytical',                # django-analytical for analytics
    'newsletter',                # newsletters
    # 'drip',                  # django-campaign for newsletter campaigns
    # 'leads',              # leads management
    # 'clickify',           # click tracking
    # 'simple_history',            # model history
    'auditlog',                  # audit logs
    'user_agents',               # user agent detection
    # 'geoip2',                    # geo ip lookup
    'import_export',             # admin import/export
    # 'django_celery',             # async tasks
    'rest_framework',            # API framework
    'crispy_forms',              # enhanced forms
    'sorl.thumbnail',            # thumbnails
    'phonenumber_field',

    'admin_honeypot',
    'csp',
    'axes',
    'sslserver',

    'django_q',
    'django_extensions',

    'wagtail.contrib.forms',
    'wagtail.contrib.redirects',
    'wagtail.embeds',
    'wagtail.sites',
    'wagtail.users',
    'wagtail.snippets',
    'wagtail.documents',
    'wagtail.images',
    'wagtail.search',
    'wagtail.admin',
    'wagtail_localize',
    'wagtail_localize.locales',
    'wagtail',

    'modelcluster',
    'taggit',

    'custom_account_u',
    'main',
    'blog',
    'finance',
    'channels',
    'messages_sys',
    'configurations',
    'dashboard_service',
    'dashboard_project',
    'dashboard',
    'services',
    'appointment.apps.AppointmentConfig',
]

INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

TENANT_MODEL = "main.Tenant"

TENANT_DOMAIN_MODEL = "main.Domain"

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
]

MIDDLEWARE = [
    'django_tenants.middleware.main.TenantMainMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'custom_account_u.middleware.Require2FAMiddleware',
    'allauth_2fa.middleware.AllauthTwoFactorMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'custom_account_u.middleware.AuthSecurityMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    'auditlog.middleware.AuditlogMiddleware',
    'csp.middleware.CSPMiddleware',
    'axes.middleware.AxesMiddleware',
    'wagtail.contrib.redirects.middleware.RedirectMiddleware',
    # 'wagtail.core.middleware.SiteMiddleware',
    # 'wagtailtrans.middleware.TranslationMiddleware',
    # 'wagtail_localize.middleware.LocalizeMiddleware',
]

ROOT_URLCONF = 'zumodra.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates', BASE_DIR / 'templates_auth' ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.template.context_processors.csrf',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'zumodra.wsgi.application'
ASGI_APPLICATION = 'zumodra.asgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'sqlite': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'production': {
        'ENGINE': env('DB_ENGINE'),
        'NAME': env('DB_DEFAULT_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_DEFAULT_PORT'),
    },
    'default': {
        'ENGINE': 'django_tenants.postgresql_backend',
        'NAME': 'zumodra',
        'USER': 'postgres',
        'PASSWORD': 'mysecretpassword',
        'HOST': 'localhost',
        'PORT': '5433',
    },
    'users': {
        'ENGINE': env('DB_ENGINE'),
        'NAME': env('DB_USER_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT':env('DB_USER_PORT'),
    }
}

ORIGINAL_BACKEND = "django.contrib.gis.db.backends.postgis"

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ROUTERS FOR TENANTS
DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ('en', 'English'),
    ('es', 'Spanish'),
    ('fr', 'French'),
    ('de', 'German'),
    ('it', 'Italian'),
    ('pt', 'Portuguese'),
    ('ru', 'Russian'),
    ('zh-hans', 'Simplified Chinese'),
    ('zh-hant', 'Traditional Chinese'),
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/files/'

STATICFILES_DIRS = [
    BASE_DIR / "staticfiles",
    BASE_DIR / "staticfiles_auth",
]

STATIC_ROOT = BASE_DIR / 'static'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'custom_account_u.CustomUser'

# Email Settings
EMAIL_BACKEND = env('EMAIL_BACKEND')
EMAIL_HOST = env('EMAIL_HOST')
EMAIL_PORT = env.int('EMAIL_PORT')
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS')
EMAIL_USE_SSL = env.bool('EMAIL_USE_SSL')
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL')

# Stripe Settings
STRIPE_SECRET_KEY = env('STRIPE_SECRET_KEY')
STRIPE_PUBLIC_KEY = env('STRIPE_PUBLIC_KEY')

# Allauth Settings
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_USER_MODEL_USERNAME_FIELD = 'username'
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_ADAPTER = 'allauth_2fa.adapter.OTPAdapter'

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    },
    'github': {
        'SCOPE': ['user', 'user:email'],
    },
    'facebook': {
        'METHOD': 'oauth2',
        'SCOPE': ['email', 'public_profile'],
        'FIELDS': [
            'id', 'email', 'name', 'first_name', 'last_name',
            'verified', 'locale', 'timezone', 'link', 'gender',
        ],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'INIT_PARAMS': {'cookie': True},
        'VERIFIED_EMAIL': False,
    },
    'linkedin': {
        'SCOPE': ['r_liteprofile', 'r_emailaddress'],
        'PROFILE_FIELDS': [
            'id', 'firstName', 'lastName', 'profilePicture(displayImage~:playableStreams)',
            'emailAddress'
        ],
    },
}


# 2FA Settings
ALLAUTH_2FA_FORCE_2FA = True
TWO_FACTOR_MANDATORY = True

# Login and Logout Redirect URLs
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

LOGIN_URL = '/accounts/login/'

# Session Settings
SESSION_COOKIE_AGE = 1209600  # Two weeks in seconds
SESSION_SAVE_EVERY_REQUEST = True

# Custom Settings
MAX_LOGIN_ATTEMPTS = 7
LOGIN_ATTEMPT_TIMEOUT = 86400  # in seconds (72 hours)
ACCOUNT_FORMS = {'signup': 'custom_account_u.forms.CustomSignupForm'}

# django-analytical settings
GOOGLE_ANALYTICS_PROPERTY_ID = 'UA-XXXXXXX-1'
CLICKY_SITE_ID = '1234567'
CRAZY_EGG_ACCOUNT_NUMBER = '7654321'

# django-user-tracking settings
USER_TRACKING_AUTO_IDENTIFY = True            # Track authenticated users
USER_TRACKING_EXCLUDE_SUPERUSER = True        # Don't track admin users to reduce noise

# django-campaign-manager (alpha) example settings
CAMPAIGN_MANAGER_USE_API = False                # Using direct DB or API (planned future)

# django-celery example configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

# REST framework example settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
}

# crispy forms layout setting
CRISPY_TEMPLATE_PACK = 'bootstrap4'

# GeoIP Path for geoip2
GEOIP_PATH = 'path/to/geoip_data'

# Logging for auditlog
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'auditlog': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}

# Using sorl-thumbnail
NEWSLETTER_THUMBNAIL = 'sorl-thumbnail'
# django-newsletter settings example
NEWSLETTER_SEND_ASYNC = True                   # Use async sending if configured
# NEWSLETTER_THUMBNAIL = 'easy-thumbnails'  # alternative supported option
NEWSLETTER_FROM_EMAIL = DEFAULT_FROM_EMAIL
NEWSLETTER_UNSUBSCRIBE_CONFIRMATION = True

# Channels
# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.core.RedisChannelLayer',  # for production
#         'CONFIG': {
#             "hosts": [('127.0.0.1', 6379)],
#         },
#     },
# }
# For scalable production use with Redis, add:
# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {
#             "hosts": [("127.0.0.1", 6379)],
#         },
#     },
# }
# Development only
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    }
}
# End Channels

# Messaging system settings
DATA_UPLOAD_MAX_MEMORY_SIZE = 55 * 1024 * 1024  # 55 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 55 * 1024 * 1024  # 55 MB

DATA_UPLOAD_MAX_NUMBER_FIELDS = 10_000

# wagtail settings
WAGTAIL_SITE_NAME = 'zumodra'
WAGTAILADMIN_BASE_URL = 'admin'
WAGTAILDOCS_EXTENSIONS = ['csv', 'docx', 'key', 'odt', 'pdf', 'pptx', 'rtf', 'txt', 'xlsx', 'zip']
WAGTAIL_I18N_ENABLED = True
WAGTAIL_CONTENT_LANGUAGES = LANGUAGES

# Axes settings
AXES_FAILURE_LIMIT = 5
AXES_NEVER_LOCKOUT_WHITELIST = ['127.0.0.1']

# django-csp settings
# CSP_REPORT_ONLY = True

#___________________________TinyMCE____________________________________________#
# TinyMCE settings
TINYMCE_DEFAULT_CONFIG = {
    # Taille de l'éditeur
    'height': 500,
    'width': '100%',      # Largeur (peut être en pixels ou %)
    'min_height': 200,    # Hauteur minimale en px
    'max_height': 800,    # Hauteur maximale en px
    'min_width': 300,     # Largeur minimale en px
    'max_width': 1000,    # Largeur maximale en px

    # Barre de menu
    'menubar': True,      # Affiche la barre de menu en haut

    # Plugins à charger
    'plugins': '''
        advlist autolink lists link image charmap print preview anchor
        searchreplace visualblocks code fullscreen insertdatetime media autoresize save
        table directionality emoticons paste codesample wordcount spellchecker style a11ychecker
    ''',

    # Configurer_toolbar (peut être divisé si tu veux plusieurs barres)
    'toolbar': '''
        undo redo | styleselect | fontselect fontsizeselect formatselect | bold italic underline strikethrough |
        forecolor backcolor casechange permanentpen formatpainter | pagebreak | charmap | alignleft aligncenter alignright alignjustify |
        bullist numlist checklist outdent indent | removeformat | code | link image |
        preview fullscreen | emoticons wordcount | help | preview save print |
        insertfile media pageembed template anchor codesample | a11ycheck ltr rtl |
    ''',

    # # Autres options utiles
    'statusbar': True,       # Affiche la barre de statut en bas
    'autoresize_bottom_margin': 20,  # Marge en px pour l'autoresize
    'resize': True,          # Permet à l'utilisateur de redimensionner l'éditeur

    # # Options spécifiques
    'branding': False,       # Supprime le branding TinyMCE
    # 'relative_urls': False,  # Désactive les URLs relatives (utile pour médias)
    # 'convert_urls': True,    # Convertit les URLs pour correspondre au site

    # # Configurations avancées pour images et médias
    'image_advtab': True,    # Onglet avancé sur images
    'file_picker_types': 'image media',  # Types de fichiers autorisés

    # # Sécurité / nettoyage
    'cleanup_on_startup': True,
    'valid_elements': '*[*]',  # Accepte tous les éléments (attention)

    'formats': {
        'p': {'classes': 'mil-mb-30'},
        'blockquote': {'classes': 'mil-mb-60'},
        'img': {'classes': 'img-fluid rounded'},
        "a": {"classes": "mil-link mil-link-hover mil-link-underline mil-link-underline-hover mil-link-underline-hover"},
        "span": {"classes": "mil-dark-soft"},
        "ol": {"classes": "mil-mb-15 list-blog"},
        "ul": {"classes": "mil-mb-15 list-blog"},
        'h1': {'classes': 'mil-mb-30'},
        'h2': {'classes': 'mil-mb-30'},
        'h3': {'classes': 'mil-mb-30'},
        'h4': {'classes': 'mil-mb-30'},
        'h5': {'classes': 'mil-mb-30'},
        'h6': {'classes': 'mil-mb-30'},
    },
    'style_formats': [
        {'title': 'Paragraph (lead)', 'block': 'p', 'classes': 'mil-mb-30 lead'},
        {'title': 'Muted Text', 'inline': 'span', 'classes': 'mil-dark-soft'},
        {'title': 'Span Primary Text', 'inline': 'span', 'classes': 'mil-accent'},
        {'title': 'Uppercase Title', 'block': 'h2', 'classes': 'mil-uppercase mil-mb-30'},
        {'title': 'Conclusion', 'block': 'p', 'classes': 'mil-mb-60'},
        {'title': 'Blockquote', 'block': 'blockquote', 'classes': 'mil-mb-60'},
        {'title': 'Button Style', 'inline': 'a', 'classes': 'mil-button mil-border'},
        {'title': 'Image Rounded', 'selector': 'img', 'classes': 'img-fluid rounded'},
        {'title': 'Image Circle', 'selector': 'img', 'classes': 'img-fluid rounded-circle'},
        {'title': 'Image Blog', 'block': 'div', 'selector': 'img', 'classes': 'img-fluid mil-post-image mil-mb-30'},
    ],
    'style_formats_merge': True,

}
TINYMCE_SPELLCHECKER = True

# Leaflet settings

LEAFLET_CONFIG = {
    'DEFAULT_CENTER': (0, 0),      # Centre sur l'intersection de l'équateur et du méridien de Greenwich
    'DEFAULT_ZOOM': 2,            # Zoom global sur le monde
    'MIN_ZOOM': 2,
    'MAX_ZOOM': 18,
    'SCALE': 'metric',
}

LEAFLET_MAP_OPTIONS = {
    'min_zoom': 2,
    'max_zoom': 18,
    'min_native_zoom': 2,
    'max_native_zoom': 18,
}

# Appointment settings

APPOINTMENT_START_TIME = 8
APPOINTMENT_END_TIME = 18
APPOINTMENT_SERVICE_MODEL = 'dashboard_service.Service'


# Django Q

Q_CLUSTER = {
    'name': 'django-appointment',
    'workers': 4,
    'timeout': 90,
    'retry': 120,
    'queue_limit': 50,
    'bulk': 10,
    'orm': 'default',
}
USE_DJANGO_Q_FOR_EMAILS = True  # Use Django Q for sending ALL emails


SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
