"""
Django settings for zumodra project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

import environ
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment variables
env = environ.Env()
environ.Env.read_env(str(BASE_DIR / '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

# SECURITY: ALLOWED_HOSTS should be explicitly set in production
# Default to localhost for development only - NEVER use '*' in production
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1', '.localhost'])

# =============================================================================
# MULTI-TENANT CONFIGURATION
# =============================================================================
# django-tenants: Shared apps run on public schema, tenant apps on tenant schemas

SHARED_APPS = [
    'django_tenants',            # Must be first for multi-tenancy
    'django.contrib.contenttypes',
    'django.contrib.sites',
    'django.contrib.auth',
    'custom_account_u',          # Custom user model - must be before admin
    'django.contrib.admin',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Tenant management apps (shared across all tenants)
    'tenants',
    'main',
]

TENANT_APPS = [
    'django.contrib.sites',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sitemaps',
    'django.contrib.gis',

    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_hotp',
    'django_otp.plugins.otp_email',
    'django_otp.plugins.otp_static',

    'allauth_2fa',
    'allauth',
    'allauth.mfa',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.linkedin',
]

# Combined list of all installed apps
INSTALLED_APPS = [
    # Django Tenants (must be first)
    'django_tenants',

    # Django Core Apps
    'django.contrib.sites',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sitemaps',
    'django.contrib.gis',

    # Two-Factor Authentication
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_hotp',
    'django_otp.plugins.otp_email',
    'django_otp.plugins.otp_static',

    # Allauth Authentication
    'allauth_2fa',
    'allauth',
    'allauth.mfa',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.linkedin',

    # Third-Party UI/Forms
    'widget_tweaks',
    'tinymce',
    'leaflet',
    'crispy_forms',

    # Analytics & Tracking
    'analytical',
    'newsletter',
    'auditlog',
    'user_agents',
    'import_export',
    'sorl.thumbnail',
    'phonenumber_field',

    # Security
    'admin_honeypot',
    'csp',
    'axes',
    'sslserver',

    # Task Scheduling
    'django_q',
    'django_celery_beat',
    'django_extensions',

    # Wagtail CMS
    'wagtail.contrib.forms',
    'wagtail.contrib.redirects',
    'wagtail.embeds',
    'wagtail.sites',
    'wagtail.users',
    'wagtail.snippets',
    'wagtail.documents',
    'wagtail.images',
    'wagtail.search',
    'wagtail.admin',
    'wagtail_localize',
    'wagtail_localize.locales',
    'wagtail',

    'modelcluster',
    'taggit',

    # REST API & Documentation
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'corsheaders',
    'drf_spectacular',

    # WebSockets
    'channels',

    # Zumodra Core Apps
    'custom_account_u',
    'main',
    'blog',
    'finance',
    'messages_sys',
    'configurations',
    'dashboard_service',
    'dashboard',
    'services',
    'appointment.apps.AppointmentConfig',

    # API & Features
    'api',
    'notifications',
    'analytics',

    # HR & ATS apps
    'ats',
    'careers',
    'hr_core',
    'tenants',
    'accounts',
    'ai_matching',
    'integrations',

    # Infrastructure & Utilities
    'core',
    'security',
    'marketing',
]

# INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

# Multi-tenant model configuration
# NOTE: Models are defined in tenants.models but re-exported from main.models
# for backwards compatibility. Either path works due to the re-export.
TENANT_MODEL = "tenants.Tenant"
TENANT_DOMAIN_MODEL = "tenants.Domain"

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
]

MIDDLEWARE = [
    # Multi-Tenancy (must be first)
    'django_tenants.middleware.main.TenantMainMiddleware',

    # Security
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',

    # CORS (must be before CommonMiddleware)
    'corsheaders.middleware.CorsMiddleware',

    # Session & Common
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',

    # Authentication
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'custom_account_u.middleware.Require2FAMiddleware',
    'allauth_2fa.middleware.AllauthTwoFactorMiddleware',

    # Messages & Security
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'custom_account_u.middleware.AuthSecurityMiddleware',

    # Audit & History
    'simple_history.middleware.HistoryRequestMiddleware',
    'auditlog.middleware.AuditlogMiddleware',

    # Content Security Policy
    'csp.middleware.CSPMiddleware',

    # Rate Limiting
    'axes.middleware.AxesMiddleware',

    # Wagtail
    'wagtail.contrib.redirects.middleware.RedirectMiddleware',
]

ROOT_URLCONF = 'zumodra.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates', BASE_DIR / 'templates_auth' ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.template.context_processors.csrf',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'zumodra.wsgi.application'
ASGI_APPLICATION = 'zumodra.asgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# =============================================================================
# DATABASE ENV VARS - Supports both short and legacy names:
#   DB_NAME / DB_DEFAULT_NAME  - Database name (default: zumodra)
#   DB_PORT / DB_DEFAULT_PORT  - Database port (default: 5432)
#   DB_HOST                    - Database host (default: localhost)
#   DB_USER                    - Database user (default: postgres)
#   DB_PASSWORD                - Database password (required)
# =============================================================================

DATABASES = {
    'default': {
        # Use django-tenants database backend wrapper for PostGIS
        'ENGINE': 'django_tenants.postgresql_backend',
        # Support both DB_NAME and DB_DEFAULT_NAME (DB_NAME takes priority)
        'NAME': env('DB_NAME', default=env('DB_DEFAULT_NAME', default='zumodra')),
        'USER': env('DB_USER', default='postgres'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST', default='localhost'),
        # Support both DB_PORT and DB_DEFAULT_PORT (DB_PORT takes priority)
        'PORT': env('DB_PORT', default=env('DB_DEFAULT_PORT', default='5432')),
    }
}

# Original backend for django-tenants to wrap (PostGIS for geospatial support)
ORIGINAL_BACKEND = "django.contrib.gis.db.backends.postgis"

# Database routers for multi-tenancy
DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ROUTERS FOR TENANTS
# DATABASE_ROUTERS = (
#     'django_tenants.routers.TenantSyncRouter',
# )

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ('en', 'English'),
    ('es', 'Spanish'),
    ('fr', 'French'),
    ('de', 'German'),
    ('it', 'Italian'),
    ('pt', 'Portuguese'),
    ('ru', 'Russian'),
    ('zh-hans', 'Simplified Chinese'),
    ('zh-hant', 'Traditional Chinese'),
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/files/'

STATICFILES_DIRS = [
    BASE_DIR / "staticfiles",
    BASE_DIR / "staticfiles_auth",
]

STATIC_ROOT = BASE_DIR / 'static'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'custom_account_u.CustomUser'

# Email Settings
EMAIL_BACKEND = env('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = env('EMAIL_HOST', default='business43.web-hosting.com')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_USE_SSL = env.bool('EMAIL_USE_SSL', default=False)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='support@rhematek-solutions.com')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='support@rhematek-solutions.com')

# Stripe Settings
STRIPE_SECRET_KEY = env('STRIPE_SECRET_KEY', default='')
STRIPE_PUBLIC_KEY = env('STRIPE_PUBLIC_KEY', default='')

# Allauth Settings
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_USER_MODEL_USERNAME_FIELD = 'username'
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_ADAPTER = 'allauth_2fa.adapter.OTPAdapter'

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    },
    'github': {
        'SCOPE': ['user', 'user:email'],
    },
    'facebook': {
        'METHOD': 'oauth2',
        'SCOPE': ['email', 'public_profile'],
        'FIELDS': [
            'id', 'email', 'name', 'first_name', 'last_name',
            'verified', 'locale', 'timezone', 'link', 'gender',
        ],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'INIT_PARAMS': {'cookie': True},
        'VERIFIED_EMAIL': False,
    },
    'linkedin': {
        'SCOPE': ['r_liteprofile', 'r_emailaddress'],
        'PROFILE_FIELDS': [
            'id', 'firstName', 'lastName', 'profilePicture(displayImage~:playableStreams)',
            'emailAddress'
        ],
    },
}


# 2FA Settings
ALLAUTH_2FA_FORCE_2FA = True
TWO_FACTOR_MANDATORY = True

# Login and Logout Redirect URLs
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

LOGIN_URL = '/accounts/login/'

# Session Settings - SECURITY HARDENED
# Reduced session age from 2 weeks to 8 hours for security
SESSION_COOKIE_AGE = 28800  # 8 hours in seconds
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookie
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection for cross-site requests
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Session persists for SESSION_COOKIE_AGE

# Custom Settings
MAX_LOGIN_ATTEMPTS = 7
LOGIN_ATTEMPT_TIMEOUT = 86400  # in seconds (72 hours)
ACCOUNT_FORMS = {'signup': 'custom_account_u.forms.CustomSignupForm'}

# django-analytical settings
GOOGLE_ANALYTICS_PROPERTY_ID = 'UA-XXXXXXX-1'
CLICKY_SITE_ID = '1234567'
CRAZY_EGG_ACCOUNT_NUMBER = '7654321'

# django-user-tracking settings
USER_TRACKING_AUTO_IDENTIFY = True            # Track authenticated users
USER_TRACKING_EXCLUDE_SUPERUSER = True        # Don't track admin users to reduce noise

# django-campaign-manager (alpha) example settings
CAMPAIGN_MANAGER_USE_API = False                # Using direct DB or API (planned future)


# ==================== CELERY CONFIGURATION ====================

# Broker settings (Redis)
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default='redis://localhost:6379/1')

# Serialization
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Timezone
CELERY_TIMEZONE = 'UTC'
CELERY_ENABLE_UTC = True

# Task result settings
CELERY_RESULT_EXPIRES = 86400  # 24 hours
CELERY_RESULT_EXTENDED = True

# Task execution settings
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_TASK_TIME_LIMIT = 3600  # 1 hour hard limit
CELERY_TASK_SOFT_TIME_LIMIT = 3300  # 55 minutes soft limit

# Worker settings
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000
CELERY_WORKER_PREFETCH_MULTIPLIER = 4
CELERY_WORKER_CONCURRENCY = env.int('CELERY_WORKER_CONCURRENCY', default=4)

# Compression
CELERY_TASK_COMPRESSION = 'gzip'
CELERY_RESULT_COMPRESSION = 'gzip'

# Retry settings
CELERY_TASK_DEFAULT_RETRY_DELAY = 60  # 1 minute
CELERY_TASK_MAX_RETRIES = 3

# Task routing
CELERY_TASK_ROUTES = {
    # Email tasks
    'newsletter.tasks.*': {'queue': 'emails'},
    'notifications.tasks.send_*': {'queue': 'emails'},
    'zumodra.tasks.send_daily_digest': {'queue': 'emails'},

    # Payment tasks
    'finance.tasks.*': {'queue': 'payments'},
    'tenants.tasks.process_subscription_*': {'queue': 'payments'},

    # Analytics tasks
    'analytics.tasks.*': {'queue': 'analytics'},

    # Notification tasks
    'notifications.tasks.*': {'queue': 'notifications'},
    'messages_sys.tasks.*': {'queue': 'notifications'},

    # HR tasks
    'hr_core.tasks.*': {'queue': 'hr'},
    'accounts.tasks.*': {'queue': 'hr'},

    # ATS tasks
    'ats.tasks.*': {'queue': 'ats'},
    'careers.tasks.*': {'queue': 'ats'},
}

# Task rate limits
CELERY_TASK_ANNOTATIONS = {
    'newsletter.tasks.send_newsletter': {'rate_limit': '50/m'},
    'notifications.tasks.send_email_notification': {'rate_limit': '100/m'},
    'finance.tasks.process_payment': {'rate_limit': '30/m'},
    'analytics.tasks.calculate_daily_metrics': {'rate_limit': '2/m'},
    'ats.tasks.calculate_match_scores': {'rate_limit': '20/m'},
}

# Celery Beat scheduler
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# ==================== END CELERY CONFIGURATION ====================


# crispy forms layout setting
CRISPY_TEMPLATE_PACK = 'bootstrap4'

# GeoIP Path for geoip2
GEOIP_PATH = 'path/to/geoip_data'

# Logging for auditlog
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'auditlog': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}

# Using sorl-thumbnail
NEWSLETTER_THUMBNAIL = 'sorl-thumbnail'
# django-newsletter settings example
NEWSLETTER_SEND_ASYNC = True                   # Use async sending if configured
# NEWSLETTER_THUMBNAIL = 'easy-thumbnails'  # alternative supported option
NEWSLETTER_FROM_EMAIL = DEFAULT_FROM_EMAIL
NEWSLETTER_UNSUBSCRIBE_CONFIRMATION = True

# Channels configuration is defined in the CHANNELS / WEBSOCKET CONFIGURATION section below

# Messaging system settings
DATA_UPLOAD_MAX_MEMORY_SIZE = 55 * 1024 * 1024  # 55 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 55 * 1024 * 1024  # 55 MB

DATA_UPLOAD_MAX_NUMBER_FIELDS = 10_000

# wagtail settings
WAGTAIL_SITE_NAME = 'zumodra'
WAGTAILADMIN_BASE_URL = 'admin'
WAGTAILDOCS_EXTENSIONS = ['csv', 'docx', 'key', 'odt', 'pdf', 'pptx', 'rtf', 'txt', 'xlsx', 'zip']
WAGTAIL_I18N_ENABLED = True
WAGTAIL_CONTENT_LANGUAGES = LANGUAGES

# Axes settings
AXES_FAILURE_LIMIT = 5
AXES_NEVER_LOCKOUT_WHITELIST = ['127.0.0.1']

# django-csp settings
# CSP_REPORT_ONLY = True

#___________________________TinyMCE____________________________________________#
# TinyMCE settings
TINYMCE_DEFAULT_CONFIG = {
    # Taille de l'éditeur
    'height': 500,
    'width': '100%',      # Largeur (peut être en pixels ou %)
    'min_height': 200,    # Hauteur minimale en px
    'max_height': 800,    # Hauteur maximale en px
    'min_width': 300,     # Largeur minimale en px
    'max_width': 1000,    # Largeur maximale en px

    # Barre de menu
    'menubar': True,      # Affiche la barre de menu en haut

    # Plugins à charger
    'plugins': '''
        advlist autolink lists link image charmap print preview anchor
        searchreplace visualblocks code fullscreen insertdatetime media autoresize save
        table directionality emoticons paste codesample wordcount spellchecker style a11ychecker
    ''',

    # Configurer_toolbar (peut être divisé si tu veux plusieurs barres)
    'toolbar': '''
        undo redo | styleselect | fontselect fontsizeselect formatselect | bold italic underline strikethrough |
        forecolor backcolor casechange permanentpen formatpainter | pagebreak | charmap | alignleft aligncenter alignright alignjustify |
        bullist numlist checklist outdent indent | removeformat | code | link image |
        preview fullscreen | emoticons wordcount | help | preview save print |
        insertfile media pageembed template anchor codesample | a11ycheck ltr rtl |
    ''',

    # # Autres options utiles
    'statusbar': True,       # Affiche la barre de statut en bas
    'autoresize_bottom_margin': 20,  # Marge en px pour l'autoresize
    'resize': True,          # Permet à l'utilisateur de redimensionner l'éditeur

    # # Options spécifiques
    'branding': False,       # Supprime le branding TinyMCE
    # 'relative_urls': False,  # Désactive les URLs relatives (utile pour médias)
    # 'convert_urls': True,    # Convertit les URLs pour correspondre au site

    # # Configurations avancées pour images et médias
    'image_advtab': True,    # Onglet avancé sur images
    'file_picker_types': 'image media',  # Types de fichiers autorisés

    # # Sécurité / nettoyage - SECURITY HARDENED
    'cleanup_on_startup': True,
    # SECURITY: Whitelist only safe HTML elements to prevent XSS
    # This replaces the dangerous '*[*]' that allowed any HTML
    'valid_elements': (
        'p[class],br,strong/b,em/i,u,s,strike,sub,sup,'
        'h1[class],h2[class],h3[class],h4[class],h5[class],h6[class],'
        'blockquote[class],pre,code,'
        'ul[class],ol[class],li,'
        'a[href|target|class|rel],img[src|alt|class|width|height],'
        'table[class],thead,tbody,tr,th[class],td[class],'
        'div[class],span[class],'
        'hr,figure[class],figcaption'
    ),
    # Block dangerous attributes that could execute scripts
    'invalid_elements': 'script,iframe,object,embed,form,input,button,select,textarea,style,link,meta',
    # Sanitize pasted content
    'paste_data_images': True,
    'paste_remove_styles_if_webkit': True,
    'paste_strip_class_attributes': 'mso',
    # Remove event handlers from pasted content
    'extended_valid_elements': 'a[href|target=_blank|class|rel=noopener]',

    'formats': {
        'p': {'classes': 'mil-mb-30'},
        'blockquote': {'classes': 'mil-mb-60'},
        'img': {'classes': 'img-fluid rounded'},
        "a": {"classes": "mil-link mil-link-hover mil-link-underline mil-link-underline-hover mil-link-underline-hover"},
        "span": {"classes": "mil-dark-soft"},
        "ol": {"classes": "mil-mb-15 list-blog"},
        "ul": {"classes": "mil-mb-15 list-blog"},
        'h1': {'classes': 'mil-mb-30'},
        'h2': {'classes': 'mil-mb-30'},
        'h3': {'classes': 'mil-mb-30'},
        'h4': {'classes': 'mil-mb-30'},
        'h5': {'classes': 'mil-mb-30'},
        'h6': {'classes': 'mil-mb-30'},
    },
    'style_formats': [
        {'title': 'Paragraph (lead)', 'block': 'p', 'classes': 'mil-mb-30 lead'},
        {'title': 'Muted Text', 'inline': 'span', 'classes': 'mil-dark-soft'},
        {'title': 'Span Primary Text', 'inline': 'span', 'classes': 'mil-accent'},
        {'title': 'Uppercase Title', 'block': 'h2', 'classes': 'mil-uppercase mil-mb-30'},
        {'title': 'Conclusion', 'block': 'p', 'classes': 'mil-mb-60'},
        {'title': 'Blockquote', 'block': 'blockquote', 'classes': 'mil-mb-60'},
        {'title': 'Button Style', 'inline': 'a', 'classes': 'mil-button mil-border'},
        {'title': 'Image Rounded', 'selector': 'img', 'classes': 'img-fluid rounded'},
        {'title': 'Image Circle', 'selector': 'img', 'classes': 'img-fluid rounded-circle'},
        {'title': 'Image Blog', 'block': 'div', 'selector': 'img', 'classes': 'img-fluid mil-post-image mil-mb-30'},
    ],
    'style_formats_merge': True,

}
TINYMCE_SPELLCHECKER = True

# Leaflet settings

LEAFLET_CONFIG = {
    'DEFAULT_CENTER': (0, 0),      # Centre sur l'intersection de l'équateur et du méridien de Greenwich
    'DEFAULT_ZOOM': 2,            # Zoom global sur le monde
    'MIN_ZOOM': 2,
    'MAX_ZOOM': 18,
    'SCALE': 'metric',
}

LEAFLET_MAP_OPTIONS = {
    'min_zoom': 2,
    'max_zoom': 18,
    'min_native_zoom': 2,
    'max_native_zoom': 18,
}

# Appointment settings

APPOINTMENT_START_TIME = 8
APPOINTMENT_END_TIME = 18
APPOINTMENT_SERVICE_MODEL = 'dashboard_service.Service'


# Django Q

Q_CLUSTER = {
    'name': 'django-appointment',
    'workers': 4,
    'timeout': 90,
    'retry': 120,
    'queue_limit': 50,
    'bulk': 10,
    'orm': 'default',
}
USE_DJANGO_Q_FOR_EMAILS = True  # Use Django Q for sending ALL emails


# Security Settings - Only enable in production
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
else:
    # Development settings
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

# ==================== REST FRAMEWORK CONFIGURATION ====================

REST_FRAMEWORK = {
    # Schema for API documentation
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

    # Authentication
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],

    # Permissions - Default to IsAuthenticated for security
    # Public endpoints must explicitly use IsAuthenticatedOrReadOnly or AllowAny
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],

    # Pagination
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,

    # Filtering
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],

    # Rate Limiting - Stricter for security
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
        # Strict rate limits for sensitive endpoints
        'auth': '5/minute',           # Login/logout
        'token': '10/minute',         # JWT token endpoints
        'password': '3/minute',       # Password reset/change
        'registration': '5/hour',     # User registration
        'file_upload': '20/hour',     # File uploads
        'export': '10/hour',          # Data exports
    },

    # Renderers - BrowsableAPIRenderer disabled in production for security
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ] + (
        ['rest_framework.renderers.BrowsableAPIRenderer'] if DEBUG else []
    ),

    # Versioning
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.URLPathVersioning',
    'DEFAULT_VERSION': 'v1',
    'ALLOWED_VERSIONS': ['v1', 'v2'],

    # Exception Handling
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
}

# ==================== JWT CONFIGURATION ====================

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# ==================== CORS CONFIGURATION ====================

# Production CORS origins - configure via environment variable
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[])

# Development CORS origins - only in DEBUG mode
if DEBUG:
    CORS_ALLOWED_ORIGINS += [
        "http://localhost:3000",  # React dev server
        "http://localhost:8080",  # Vue dev server
        "http://127.0.0.1:3000",
        "http://127.0.0.1:8080",
    ]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# ==================== RATE LIMITING CONFIGURATION ====================

# Using Django Ratelimit (install with: pip install django-ratelimit)
RATELIMIT_ENABLE = True
RATELIMIT_USE_CACHE = 'default'

# Custom rate limits for specific views
RATELIMIT_VIEW = '100/h'  # Default rate limit for views

# ==================== LOGGING CONFIGURATION ====================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'formatter': 'verbose'
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOGS_DIR, exist_ok=True)

# ==================== ANALYTICS MIDDLEWARE ====================

# Add to MIDDLEWARE (already exists, but noting for reference)
# 'analytics.middleware.AnalyticsMiddleware',  # Track page views

# ==================== API DOCUMENTATION (drf-spectacular) ====================

SPECTACULAR_SETTINGS = {
    'TITLE': 'Zumodra API',
    'DESCRIPTION': '''
    Zumodra Multi-Tenant SaaS Platform REST API

    A comprehensive freelance services marketplace with integrated CRM tools,
    appointment booking, escrow payments, real-time messaging, email marketing,
    and content management.

    ## Features
    - Multi-tenant architecture for enterprise scalability
    - JWT and Session authentication
    - Role-based access control (RBAC)
    - Real-time WebSocket messaging
    - Geospatial service matching via PostGIS
    - Stripe escrow payments and subscriptions
    - HR/ATS workflow management

    ## Authentication
    Use Bearer token authentication for API requests:
    ```
    Authorization: Bearer <your-access-token>
    ```
    ''',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,

    # Schema configuration
    'SCHEMA_PATH_PREFIX': r'/api/v[0-9]',
    'SERVE_PERMISSIONS': ['rest_framework.permissions.IsAdminUser'],

    # Swagger UI settings
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
        'filter': True,
    },

    # ReDoc settings
    'REDOC_UI_SETTINGS': {
        'hideDownloadButton': False,
    },

    # Contact information
    'CONTACT': {
        'name': 'Zumodra Support',
        'email': 'support@zumodra.com',
    },

    # License
    'LICENSE': {
        'name': 'Proprietary',
    },

    # Tags for API organization
    'TAGS': [
        {'name': 'Authentication', 'description': 'User authentication and JWT token management'},
        {'name': 'Users', 'description': 'User profile and account management'},
        {'name': 'Services', 'description': 'Service listing and marketplace operations'},
        {'name': 'Appointments', 'description': 'Appointment booking and scheduling'},
        {'name': 'Finance', 'description': 'Payments, escrow, and subscriptions'},
        {'name': 'Messages', 'description': 'Real-time messaging system'},
        {'name': 'HR', 'description': 'Human resources and talent management'},
        {'name': 'ATS', 'description': 'Applicant tracking system'},
        {'name': 'Analytics', 'description': 'Platform analytics and reporting'},
        {'name': 'Tenants', 'description': 'Multi-tenant management'},
    ],

    # Component split for better organization
    'COMPONENT_SPLIT_REQUEST': True,
    'COMPONENT_NO_READ_ONLY_REQUIRED': True,

    # Enum naming
    'ENUM_NAME_OVERRIDES': {},

    # Extensions
    'EXTENSIONS_INFO': {},
}

# ==================== CELERY CONFIGURATION ====================

CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_CONCURRENCY = 4

# Celery Beat schedule for periodic tasks
CELERY_BEAT_SCHEDULE = {
    'cleanup-expired-sessions': {
        'task': 'main.tasks.cleanup_expired_sessions',
        'schedule': 3600.0,  # Every hour
    },
    'send-scheduled-newsletters': {
        'task': 'newsletter.tasks.send_scheduled_newsletters',
        'schedule': 300.0,  # Every 5 minutes
    },
    'update-analytics': {
        'task': 'analytics.tasks.update_daily_analytics',
        'schedule': 86400.0,  # Every day
    },
}

# ==================== CHANNELS / WEBSOCKET CONFIGURATION ====================
# Optimized for 500K concurrent users

# Parse Redis hosts for potential cluster configuration
REDIS_CHANNEL_URL = env('REDIS_CHANNEL_URL', default=env('REDIS_URL', default='redis://127.0.0.1:6379/1'))

# Production Redis configuration (scaled for 500K concurrent users)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [REDIS_CHANNEL_URL],
            # Capacity: Max messages per channel before oldest are dropped
            # For 500K users: ~100K concurrent connections per server
            'capacity': 100000,
            # Expiry: How long messages stay in channel (seconds)
            'expiry': 60,
            # Group expiry: How long group membership lasts
            'group_expiry': 86400,  # 24 hours
            # Symmetric encryption key (set in production for security)
            # 'symmetric_encryption_keys': [env('CHANNEL_ENCRYPTION_KEY', default='')],
        },
    },
}

# Redis connection pool settings for high concurrency
CHANNEL_REDIS_CONNECTION_POOL_SIZE = env.int('CHANNEL_REDIS_POOL_SIZE', default=100)

# WebSocket rate limiting settings
WEBSOCKET_MAX_MESSAGES_PER_SECOND = env.int('WEBSOCKET_RATE_LIMIT', default=10)
WEBSOCKET_MAX_FILE_SIZE_MB = env.int('WEBSOCKET_MAX_FILE_MB', default=50)

# Development configuration (InMemory - uncomment for local dev without Redis)
# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels.layers.InMemoryChannelLayer",
#     }
# }

# ==================== CACHING CONFIGURATION ====================

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': env('REDIS_URL', default='redis://127.0.0.1:6379/2'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'KEY_PREFIX': 'zumodra',
    },
    'axes': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': env('REDIS_URL', default='redis://127.0.0.1:6379/3'),
    },
}

# Session backend using cache
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'

# ==================== FILE STORAGE CONFIGURATION ====================

# AWS S3 Configuration (enable for production)
AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID', default='')
AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY', default='')
AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME', default='zumodra-media')
AWS_S3_REGION_NAME = env('AWS_S3_REGION_NAME', default='us-east-1')
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}
AWS_DEFAULT_ACL = 'public-read'
AWS_S3_FILE_OVERWRITE = False

# Use S3 for media storage in production
if not DEBUG and AWS_ACCESS_KEY_ID:
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# ==================== TWILIO CONFIGURATION ====================

TWILIO_ACCOUNT_SID = env('TWILIO_ACCOUNT_SID', default='')
TWILIO_AUTH_TOKEN = env('TWILIO_AUTH_TOKEN', default='')
TWILIO_PHONE_NUMBER = env('TWILIO_PHONE_NUMBER', default='')

# ==================== OPENAI CONFIGURATION ====================

OPENAI_API_KEY = env('OPENAI_API_KEY', default='')
OPENAI_MODEL = env('OPENAI_MODEL', default='gpt-4')

# ==================== TENANT CONFIGURATION ====================

# Public schema URL routing
PUBLIC_SCHEMA_URLCONF = 'zumodra.urls_public'

# Default tenant schema
DEFAULT_SCHEMA_NAME = 'public'

# Auto-create public tenant
AUTO_CREATE_PUBLIC_SCHEMA = True

# Tenant subfolder prefix for static/media
MULTITENANT_RELATIVE_MEDIA_ROOT = '%s/media'

# ==================== SECURITY HEADERS ====================

# Content Security Policy (configured via django-csp middleware 4.0+)
# Note: unsafe-inline/unsafe-eval needed for HTMX and some JS libraries
# In strict production, use nonces instead and remove these directives
CONTENT_SECURITY_POLICY = {
    'DIRECTIVES': {
        'default-src': ("'self'",),
        'script-src': (
            "'self'",
            "https://cdn.jsdelivr.net",
            "https://unpkg.com",
            "https://js.stripe.com",
            "'unsafe-inline'",
            "'unsafe-eval'",
        ),
        'style-src': (
            "'self'",
            "'unsafe-inline'",
            "https://fonts.googleapis.com",
            "https://cdn.jsdelivr.net",
        ),
        'font-src': ("'self'", "https://fonts.gstatic.com", "data:"),
        'img-src': ("'self'", "data:", "https:", "blob:"),
        'connect-src': (
            "'self'",
            "wss:",
            "https:",
            "https://api.stripe.com",
        ),
        'frame-src': ("'self'", "https://js.stripe.com"),
        'frame-ancestors': ("'self'",),
        'object-src': ("'none'",),
        'base-uri': ("'self'",),
        'form-action': ("'self'",),
    }
}

# ==================== FEATURE FLAGS ====================

FEATURE_FLAGS = {
    'ENABLE_2FA': env.bool('FEATURE_ENABLE_2FA', default=True),
    'ENABLE_ESCROW': env.bool('FEATURE_ENABLE_ESCROW', default=True),
    'ENABLE_WEBSOCKETS': env.bool('FEATURE_ENABLE_WEBSOCKETS', default=True),
    'ENABLE_AI_MATCHING': env.bool('FEATURE_ENABLE_AI_MATCHING', default=False),
    'ENABLE_SMS_NOTIFICATIONS': env.bool('FEATURE_ENABLE_SMS_NOTIFICATIONS', default=False),
}
