# Generated by Django 5.2.7 on 2026-01-10 18:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketing_id', models.CharField(db_index=True, max_length=32)),
                ('event_name', models.CharField(max_length=128)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('subject', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent', models.BooleanField(default=False)),
                ('sent_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_on', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_on', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=128)),
                ('last_name', models.CharField(blank=True, max_length=128)),
                ('company', models.CharField(blank=True, max_length=256)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('source', models.CharField(blank=True, help_text='Lead source or campaign', max_length=256)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('disqualified', 'Disqualified')], default='new', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='AggregatedStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('country', models.CharField(db_index=True, max_length=2)),
                ('device_type', models.CharField(max_length=32)),
                ('total_visits', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'country', 'device_type')},
            },
        ),
        migrations.CreateModel(
            name='NewsletterTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened', models.BooleanField(default=False)),
                ('opened_on', models.DateTimeField(blank=True, null=True)),
                ('clicked', models.BooleanField(default=False)),
                ('clicked_on', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.newslettercampaign')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.newslettersubscriber')),
            ],
        ),
        migrations.CreateModel(
            name='VisitEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('marketing_id', models.CharField(db_index=True, max_length=32)),
                ('ip_address', models.GenericIPAddressField()),
                ('country', models.CharField(db_index=True, max_length=2)),
                ('device_type', models.CharField(max_length=32)),
                ('browser', models.CharField(max_length=32)),
                ('os', models.CharField(max_length=32)),
                ('path', models.CharField(max_length=256)),
                ('method', models.CharField(max_length=8)),
                ('utm_source', models.CharField(blank=True, max_length=128, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=128, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=128, null=True)),
                ('utm_content', models.CharField(blank=True, max_length=128, null=True)),
                ('utm_term', models.CharField(blank=True, max_length=128, null=True)),
                ('ref', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['marketing_id'], name='marketing_v_marketi_9ce7f0_idx'), models.Index(fields=['country'], name='marketing_v_country_2bf4d6_idx'), models.Index(fields=['timestamp'], name='marketing_v_timesta_f51165_idx'), models.Index(fields=['device_type'], name='marketing_v_device__ee3555_idx')],
            },
        ),
    ]
