# Generated by Django 5.2.7 on 2026-01-25 14:53

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('tenants', '0002_add_company_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderPortfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record is active.', verbose_name='Is active')),
                ('image', models.ImageField(help_text='Portfolio image', upload_to='provider_portfolio/')),
                ('title', models.CharField(blank=True, help_text='Portfolio piece title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Portfolio piece description')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Display order in portfolio grid')),
                ('grid_col_span', models.PositiveSmallIntegerField(default=1, help_text='Grid column span (1-3)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('grid_row_span', models.PositiveSmallIntegerField(default=1, help_text='Grid row span (1-2)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(help_text='Provider who owns this portfolio item', on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='services.serviceprovider')),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Provider Portfolio Item',
                'verbose_name_plural': 'Provider Portfolio Items',
                'ordering': ['provider', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ServicePricingTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record is active.', verbose_name='Is active')),
                ('name', models.CharField(help_text='Tier name (e.g., Starter, Professional, Executive)', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Tier price', max_digits=10)),
                ('delivery_time_days', models.PositiveSmallIntegerField(help_text='Delivery time in days for this tier')),
                ('revisions', models.PositiveSmallIntegerField(help_text='Number of revisions included (0 = unlimited)')),
                ('features', models.JSONField(default=dict, help_text="Feature list with boolean/text values: {'printable_resolution': true, 'logo_design': true, ...}")),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Display order (usually price ascending)')),
                ('is_recommended', models.BooleanField(default=False, help_text='Highlight this tier as recommended')),
                ('service', models.ForeignKey(help_text='Parent service', on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tiers', to='services.service')),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Service Pricing Tier',
                'verbose_name_plural': 'Service Pricing Tiers',
                'ordering': ['service', 'sort_order'],
                'constraints': [models.UniqueConstraint(fields=('service', 'name'), name='services_pricing_tier_unique_service_name')],
            },
        ),
    ]
