# Generated by Django 5.2.7 on 2026-01-02 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(help_text='The user who made the appointment request.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_request',
            field=models.OneToOneField(help_text='The appointment request made by the client.', on_delete=django.db.models.deletion.CASCADE, to='appointment.appointmentrequest', verbose_name='Appointment Request'),
        ),
        migrations.AddField(
            model_name='appointmentreschedulehistory',
            name='appointment_request',
            field=models.ForeignKey(help_text='The appointment request made by a client.', on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_histories', to='appointment.appointmentrequest', verbose_name='Appointment Request'),
        ),
        migrations.AddField(
            model_name='emailverificationcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment', verbose_name='Appointment'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['name'], name='appointment_name_c25ec8_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['price'], name='appointment_price_0f5143_idx'),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.service', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='services_offered',
            field=models.ManyToManyField(help_text='Services that this staff member provides.', to='appointment.service', verbose_name='Services Offered'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='dayoff',
            name='staff_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.staffmember', verbose_name='Staff Member'),
        ),
        migrations.AddField(
            model_name='appointmentreschedulehistory',
            name='staff_member',
            field=models.ForeignKey(help_text='The previous staff member of the appointment before it was rescheduled.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointment.staffmember', verbose_name='Staff Member'),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='staff_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointment.staffmember', verbose_name='Staff Member'),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='staff_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.staffmember', verbose_name='Staff Member'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['client', '-created_at'], name='appointment_client__b0d651_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_to_pay__gte', 0)), name='positive_amount_to_pay'),
        ),
        migrations.AddIndex(
            model_name='appointmentrequest',
            index=models.Index(fields=['date', 'start_time'], name='appointment_date_eff862_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentrequest',
            index=models.Index(fields=['staff_member', 'date'], name='appointment_staff_m_13c670_idx'),
        ),
        migrations.AddConstraint(
            model_name='workinghours',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='start_time_before_end_time'),
        ),
        migrations.AlterUniqueTogether(
            name='workinghours',
            unique_together={('staff_member', 'day_of_week')},
        ),
    ]
