# Generated by Django 5.2.7 on 2026-01-10 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('configurations', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_users', to='configurations.department'),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='reports_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='accounts.tenantuser'),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trustscore',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_score', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='candidatecv',
            unique_together={('user', 'slug')},
        ),
        migrations.AddIndex(
            model_name='educationverification',
            index=models.Index(fields=['user', 'status'], name='accounts_ed_user_id_388b55_idx'),
        ),
        migrations.AddIndex(
            model_name='educationverification',
            index=models.Index(fields=['verification_token'], name='accounts_ed_verific_c27e9d_idx'),
        ),
        migrations.AddIndex(
            model_name='employmentverification',
            index=models.Index(fields=['user', 'status'], name='accounts_em_user_id_f26402_idx'),
        ),
        migrations.AddIndex(
            model_name='employmentverification',
            index=models.Index(fields=['verification_token'], name='accounts_em_verific_69a171_idx'),
        ),
        migrations.AddIndex(
            model_name='kycverification',
            index=models.Index(fields=['user', 'verification_type'], name='accounts_ky_user_id_39f92a_idx'),
        ),
        migrations.AddIndex(
            model_name='kycverification',
            index=models.Index(fields=['status', 'created_at'], name='accounts_ky_status_60cf02_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['user', 'timestamp'], name='accounts_lo_user_id_85d75c_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['ip_address', 'timestamp'], name='accounts_lo_ip_addr_bcaa8b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='progressiveconsent',
            unique_together={('grantor', 'grantee_user', 'grantee_tenant', 'data_category', 'context_type', 'context_id')},
        ),
        migrations.AddIndex(
            model_name='dataaccesslog',
            index=models.Index(fields=['data_subject', 'accessed_at'], name='accounts_da_data_su_289b4c_idx'),
        ),
        migrations.AddIndex(
            model_name='dataaccesslog',
            index=models.Index(fields=['accessor', 'accessed_at'], name='accounts_da_accesso_404a3e_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewee', 'status', '-created_at'], name='accounts_re_reviewe_b666be_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewer', '-created_at'], name='accounts_re_reviewe_aa662c_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['overall_rating', 'status'], name='accounts_re_overall_8dcb26_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('reviewer', 'reviewee', 'context_type', 'context_id'), name='accounts_review_unique_per_context'),
        ),
        migrations.AlterUniqueTogether(
            name='coopterm',
            unique_together={('student', 'term_number')},
        ),
        migrations.AlterUniqueTogether(
            name='tenantuser',
            unique_together={('user', 'tenant')},
        ),
        migrations.AddIndex(
            model_name='trustscore',
            index=models.Index(fields=['trust_level', 'overall_score'], name='accounts_tr_trust_l_005fb4_idx'),
        ),
        migrations.AddIndex(
            model_name='trustscore',
            index=models.Index(fields=['entity_type', 'trust_level'], name='accounts_tr_entity__1c5d75_idx'),
        ),
    ]
