# Generated by Django 5.2.7 on 2026-01-11 06:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tenantprofile'),
        ('configurations', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tenant Profile', 'verbose_name_plural': 'Tenant Profiles'},
        ),
        migrations.RemoveConstraint(
            model_name='tenantprofile',
            name='accounts_tenantprofile_unique_user_tenant',
        ),
        migrations.RemoveIndex(
            model_name='tenantprofile',
            name='accounts_te_employe_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantprofile',
            new_name='accounts_te_user_id_24a5a3_idx',
            old_name='accounts_te_user_id_tenant_idx',
        ),
        migrations.AlterUniqueTogether(
            name='tenantprofile',
            unique_together={('user', 'tenant')},
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='email',
            field=models.EmailField(blank=True, help_text='Synced from PublicProfile.public_email', max_length=254),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='languages_json',
            field=models.JSONField(blank=True, default=list, help_text='Synced from PublicProfile.languages'),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='skills_json',
            field=models.JSONField(blank=True, default=list, help_text='Synced from PublicProfile.skills'),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='synced_fields',
            field=models.JSONField(blank=True, default=list, help_text='List of field names that were synced'),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When profile was last synced from PublicProfile', null=True),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Synced from PublicProfile.phone', max_length=30),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='portfolio_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='tenantprofile',
            index=models.Index(fields=['tenant', 'job_title'], name='accounts_te_tenant__dff779_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantprofile',
            index=models.Index(fields=['department'], name='accounts_te_departm_2153ee_idx'),
        ),
        migrations.AlterModelTable(
            name='tenantprofile',
            table=None,
        ),
        migrations.RemoveField(
            model_name='tenantprofile',
            name='cv_file_url',
        ),
        migrations.RemoveField(
            model_name='tenantprofile',
            name='cv_last_updated',
        ),
        migrations.RemoveField(
            model_name='tenantprofile',
            name='email_work',
        ),
        migrations.RemoveField(
            model_name='tenantprofile',
            name='professional_title',
        ),
        migrations.RemoveField(
            model_name='tenantprofile',
            name='skills',
        ),
    ]
