# Generated by Django 5.2.7 on 2026-01-11 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_tenantprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycverification',
            name='document_file',
            field=models.FileField(blank=True, help_text='Uploaded KYC document (ID, passport, etc.)', null=True, upload_to='kyc_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
