# Generated by Django 5.2.7 on 2026-01-18 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_matching', '0001_initial'),
        ('configurations', '0001_initial'),
        ('jobs', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='biasauditlog',
            name='auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bias_audits_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='biasmetric',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bias_metrics', to='jobs.jobposting'),
        ),
        migrations.AddField(
            model_name='biasmetric',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_bias_metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='biasmetric',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this object belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='candidateembedding',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='configurations.candidateprofile'),
        ),
        migrations.AddField(
            model_name='candidateranking',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='jobembedding',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='configurations.job'),
        ),
        migrations.AddField(
            model_name='jobmatchingprofile',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matching_profile', to='jobs.jobposting'),
        ),
        migrations.AddField(
            model_name='jobmatchingprofile',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this object belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='matchingprofile',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matching_profile', to='jobs.candidate'),
        ),
        migrations.AddField(
            model_name='matchingprofile',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this object belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='matchingresult',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_results', to='configurations.candidateprofile'),
        ),
        migrations.AddField(
            model_name='matchingresult',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_results', to='configurations.job'),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_match_results', to='jobs.candidate'),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_match_results', to='jobs.jobposting'),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this object belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='rankingprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ranking_profiles_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rankingprofile',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='rankingprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ranking_profiles_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidateranking',
            name='ranking_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rankings', to='ai_matching.rankingprofile'),
        ),
        migrations.AddField(
            model_name='rankingrule',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skillembedding',
            name='skill',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='configurations.skill'),
        ),
        migrations.AddField(
            model_name='skilltaxonomy',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent skill (e.g., Python -> Programming)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='ai_matching.skilltaxonomy'),
        ),
        migrations.AddField(
            model_name='skilltaxonomy',
            name='related_skills',
            field=models.ManyToManyField(blank=True, help_text='Related skills for similarity matching', to='ai_matching.skilltaxonomy'),
        ),
        migrations.AddIndex(
            model_name='biasauditlog',
            index=models.Index(fields=['content_type', 'content_id'], name='ai_matching_content_b08c1e_idx'),
        ),
        migrations.AddIndex(
            model_name='biasauditlog',
            index=models.Index(fields=['bias_detected'], name='ai_matching_bias_de_890da8_idx'),
        ),
        migrations.AddIndex(
            model_name='biasauditlog',
            index=models.Index(fields=['created_at'], name='ai_matching_created_8cde1f_idx'),
        ),
        migrations.AddIndex(
            model_name='biasmetric',
            index=models.Index(fields=['tenant', 'period_start'], name='ai_matching_tenant__6b90d9_idx'),
        ),
        migrations.AddIndex(
            model_name='biasmetric',
            index=models.Index(fields=['bias_detected'], name='ai_matching_bias_de_b282ec_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateembedding',
            index=models.Index(fields=['candidate'], name='ai_matching_candida_9977b8_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateembedding',
            index=models.Index(fields=['updated_at'], name='ai_matching_updated_727dfb_idx'),
        ),
        migrations.AddIndex(
            model_name='jobembedding',
            index=models.Index(fields=['job'], name='ai_matching_job_id_4ede94_idx'),
        ),
        migrations.AddIndex(
            model_name='jobembedding',
            index=models.Index(fields=['updated_at'], name='ai_matching_updated_fe15bc_idx'),
        ),
        migrations.AddIndex(
            model_name='jobmatchingprofile',
            index=models.Index(fields=['tenant', 'job'], name='ai_matching_tenant__90bc0a_idx'),
        ),
        migrations.AddIndex(
            model_name='jobmatchingprofile',
            index=models.Index(fields=['processing_status'], name='ai_matching_process_7870a0_idx'),
        ),
        migrations.AddIndex(
            model_name='jobmatchingprofile',
            index=models.Index(fields=['-last_processed'], name='ai_matching_last_pr_4b249a_idx'),
        ),
        migrations.AddIndex(
            model_name='matchingprofile',
            index=models.Index(fields=['tenant', 'candidate'], name='ai_matching_tenant__063fb9_idx'),
        ),
        migrations.AddIndex(
            model_name='matchingprofile',
            index=models.Index(fields=['processing_status'], name='ai_matching_process_1df15e_idx'),
        ),
        migrations.AddIndex(
            model_name='matchingprofile',
            index=models.Index(fields=['overall_quality_score'], name='ai_matching_overall_c56267_idx'),
        ),
        migrations.AddIndex(
            model_name='matchingprofile',
            index=models.Index(fields=['-last_processed'], name='ai_matching_last_pr_6ba67d_idx'),
        ),
        migrations.AddIndex(
            model_name='matchingresult',
            index=models.Index(fields=['candidate', 'job'], name='ai_matching_candida_f36849_idx'),
        ),
        migrations.AddIndex(
            model_name='matchingresult',
            index=models.Index(fields=['overall_score'], name='ai_matching_overall_04b040_idx'),
        ),
        migrations.AddIndex(
            model_name='matchingresult',
            index=models.Index(fields=['calculated_at'], name='ai_matching_calcula_98fc62_idx'),
        ),
        migrations.AddIndex(
            model_name='matchingresult',
            index=models.Index(fields=['is_stale'], name='ai_matching_is_stal_7a7af1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='matchingresult',
            unique_together={('candidate', 'job')},
        ),
        migrations.AddIndex(
            model_name='matchresult',
            index=models.Index(fields=['tenant', 'candidate', 'job'], name='ai_matching_tenant__e425e5_idx'),
        ),
        migrations.AddIndex(
            model_name='matchresult',
            index=models.Index(fields=['tenant', 'job', '-overall_score'], name='ai_matching_tenant__49cb6b_idx'),
        ),
        migrations.AddIndex(
            model_name='matchresult',
            index=models.Index(fields=['tenant', 'candidate', '-overall_score'], name='ai_matching_tenant__61e230_idx'),
        ),
        migrations.AddIndex(
            model_name='matchresult',
            index=models.Index(fields=['overall_score'], name='ai_matching_overall_6b23b5_idx'),
        ),
        migrations.AddIndex(
            model_name='matchresult',
            index=models.Index(fields=['computed_at'], name='ai_matching_compute_880776_idx'),
        ),
        migrations.AddIndex(
            model_name='matchresult',
            index=models.Index(fields=['is_stale'], name='ai_matching_is_stal_1b409e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='matchresult',
            unique_together={('tenant', 'candidate', 'job')},
        ),
        migrations.AddIndex(
            model_name='candidateranking',
            index=models.Index(fields=['tenant', 'job_id', '-overall_score'], name='ai_matching_tenant__9be1c0_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateranking',
            index=models.Index(fields=['tenant', 'candidate_id'], name='ai_matching_tenant__1011bf_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateranking',
            index=models.Index(fields=['is_recommended', '-overall_score'], name='ai_matching_is_reco_ae8eb9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='candidateranking',
            unique_together={('tenant', 'job_id', 'candidate_id')},
        ),
        migrations.AddIndex(
            model_name='recommendationlog',
            index=models.Index(fields=['user'], name='ai_matching_user_id_d0b6d5_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationlog',
            index=models.Index(fields=['recommendation_type'], name='ai_matching_recomme_d17813_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationlog',
            index=models.Index(fields=['created_at'], name='ai_matching_created_9ac35d_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationlog',
            index=models.Index(fields=['fallback_used'], name='ai_matching_fallbac_fec19a_idx'),
        ),
        migrations.AddIndex(
            model_name='skillembedding',
            index=models.Index(fields=['skill'], name='ai_matching_skill_i_29fa21_idx'),
        ),
        migrations.AddIndex(
            model_name='skillembedding',
            index=models.Index(fields=['updated_at'], name='ai_matching_updated_8f21b8_idx'),
        ),
        migrations.AddIndex(
            model_name='skilltaxonomy',
            index=models.Index(fields=['canonical_name'], name='ai_matching_canonic_77b78d_idx'),
        ),
        migrations.AddIndex(
            model_name='skilltaxonomy',
            index=models.Index(fields=['category'], name='ai_matching_categor_5a6e38_idx'),
        ),
        migrations.AddIndex(
            model_name='skilltaxonomy',
            index=models.Index(fields=['is_active'], name='ai_matching_is_acti_5d78cb_idx'),
        ),
    ]
