# Generated by Django 5.2.6 on 2025-10-31 16:23

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Titre de l'article", max_length=200)),
                ('slug', models.SlugField(help_text="Slug unique pour l'URL", max_length=200, unique=True)),
                ('content_html', tinymce.models.HTMLField()),
                ('excerpt', models.TextField(blank=True, help_text="Résumé de l'article", max_length=300)),
                ('featured_image', models.ImageField(help_text='Image principale', upload_to='blog_images/')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('scheduled', 'Planifié'), ('finished', 'Terminé'), ('published', 'Publié')], default='draft', help_text='Statut de publication', max_length=10)),
                ('meta_title', models.CharField(blank=True, help_text='Titre SEO (optionnel)', max_length=200)),
                ('meta_description', models.TextField(blank=True, help_text='Description SEO (optionnelle)')),
                ('publishing_date', models.DateTimeField(blank=True, help_text='Date de publication planifiée', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de modification')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de la catégorie', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description facultative')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Contenu du commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du tag (unique)', max_length=64, unique=True)),
            ],
        ),
    ]
