# Generated by Django 5.2.7 on 2026-01-02 10:10

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CategoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPostPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('heading2', 1), ('heading3', 2), ('heading4', 3), ('heading5', 4), ('heading6', 5), ('ordered_list', 7), ('unordered_list', 8), ('paragraph', 6), ('image', 9), ('quote', 13), ('table', 20)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'form_classname': 'title2'}), 2: ('wagtail.blocks.RichTextBlock', (), {'form_classname': 'title3'}), 3: ('wagtail.blocks.RichTextBlock', (), {'form_classname': 'title4'}), 4: ('wagtail.blocks.RichTextBlock', (), {'form_classname': 'title5'}), 5: ('wagtail.blocks.RichTextBlock', (), {'form_classname': 'title6'}), 6: ('wagtail.blocks.RichTextBlock', (), {}), 7: ('wagtail.blocks.ListBlock', (6,), {'icon': 'list-ol'}), 8: ('wagtail.blocks.ListBlock', (6,), {'icon': 'list-ul'}), 9: ('wagtail.images.blocks.ImageBlock', [], {}), 10: ('wagtail.blocks.BlockQuoteBlock', (), {'help_text': 'Texte de la citation', 'required': True}), 11: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Auteur de la citation', 'required': False}), 12: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Source de la citation', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('quote', 10), ('author', 11), ('source', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {}), 15: ('wagtail.blocks.ListBlock', (14,), {}), 16: ('blog.models.RichTextCellBlock', (), {}), 17: ('wagtail.blocks.ListBlock', (16,), {}), 18: ('wagtail.blocks.StructBlock', [[('cells', 17)]], {}), 19: ('wagtail.blocks.ListBlock', (18,), {}), 20: ('wagtail.blocks.StructBlock', [[('header', 15), ('rows', 19)]], {})}, null=True)),
                ('excerpt', models.TextField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('scheduled', 'Planifié'), ('finished', 'Terminé'), ('published', 'Publié')], default='draft', max_length=10)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('publishing_date', models.DateTimeField(blank=True, null=True)),
                ('featured_image', models.ForeignKey(blank=True, help_text='Image principale', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='blog.blogpostpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='blog.BlogPostTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, default='', max_length=120)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpostpage')),
            ],
        ),
    ]
