# Generated by Django 5.2.6 on 2025-11-02 03:16

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_index_page_blogindexpage_categorypage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostpage',
            name='content_html',
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('code', 5), ('quote', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageBlock', [], {}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('bash', 'Bash/Shell'), ('css', 'CSS'), ('diff', 'diff'), ('html', 'HTML'), ('javascript', 'Javascript'), ('json', 'JSON'), ('python', 'Python'), ('scss', 'SCSS'), ('yaml', 'YAML')], 'help_text': 'Coding language', 'identifier': 'language', 'label': 'Language'}), 4: ('wagtail.blocks.TextBlock', (), {'identifier': 'code', 'label': 'Code'}), 5: ('wagtail.blocks.StructBlock', [[('language', 3), ('code', 4)]], {}), 6: ('wagtail.blocks.BlockQuoteBlock', (), {})}, null=True),
        ),
        migrations.DeleteModel(
            name='Blog_index_Page',
        ),
    ]
