# Generated by Django 5.2.7 on 2025-11-03 15:20

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blogpostpage_content_html_blogpostpage_body_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('heading2', 1), ('heading3', 2), ('heading4', 3), ('heading5', 4), ('heading6', 5), ('ordered_list', 7), ('unordered_list', 8), ('paragraph', 6), ('image', 9), ('quote', 13), ('table', 20)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'form_classname': 'title2'}), 2: ('wagtail.blocks.RichTextBlock', (), {'form_classname': 'title3'}), 3: ('wagtail.blocks.RichTextBlock', (), {'form_classname': 'title4'}), 4: ('wagtail.blocks.RichTextBlock', (), {'form_classname': 'title5'}), 5: ('wagtail.blocks.RichTextBlock', (), {'form_classname': 'title6'}), 6: ('wagtail.blocks.RichTextBlock', (), {}), 7: ('wagtail.blocks.ListBlock', (6,), {'icon': 'list-ol'}), 8: ('wagtail.blocks.ListBlock', (6,), {'icon': 'list-ul'}), 9: ('wagtail.images.blocks.ImageBlock', [], {}), 10: ('wagtail.blocks.BlockQuoteBlock', (), {'help_text': 'Texte de la citation', 'required': True}), 11: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Auteur de la citation', 'required': False}), 12: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Source de la citation', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('quote', 10), ('author', 11), ('source', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {}), 15: ('wagtail.blocks.ListBlock', (14,), {}), 16: ('blog.models.RichTextCellBlock', (), {}), 17: ('wagtail.blocks.ListBlock', (16,), {}), 18: ('wagtail.blocks.StructBlock', [[('cells', 17)]], {}), 19: ('wagtail.blocks.ListBlock', (18,), {}), 20: ('wagtail.blocks.StructBlock', [[('header', 15), ('rows', 19)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='blogpostpage',
            name='featured_image',
            field=models.ForeignKey(blank=True, help_text='Image principale', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
