# Generated by Django 5.2.7 on 2026-01-02 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ats', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='applicationactivity',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='ats.application'),
        ),
        migrations.AddField(
            model_name='applicationactivity',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationnote',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='ats.application'),
        ),
        migrations.AddField(
            model_name='applicationnote',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ats_applicationnote_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationnote',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidate',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_candidates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidate',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_profile_ats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='ats.candidate'),
        ),
        migrations.AddField(
            model_name='interview',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='ats.application'),
        ),
        migrations.AddField(
            model_name='interview',
            name='interviewers',
            field=models.ManyToManyField(related_name='interviews_as_interviewer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interview',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_interviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='ats.interview'),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='interviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewslot',
            name='booked_by_interview',
            field=models.OneToOneField(blank=True, help_text='The interview that booked this slot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_slot', to='ats.interview'),
        ),
        migrations.AddField(
            model_name='interviewslot',
            name='interviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewslot',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='interviewtemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_interview_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewtemplate',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='interview',
            name='interview_template',
            field=models.ForeignKey(blank=True, help_text='Template used for this interview', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to='ats.interviewtemplate'),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='ats.jobcategory'),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='ats.jobcategory'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='hiring_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruiting_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='ats.jobposting'),
        ),
        migrations.AddField(
            model_name='offer',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='ats.application'),
        ),
        migrations.AddField(
            model_name='offer',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='previous_offer',
            field=models.ForeignKey(blank=True, help_text='Previous offer in the counter-offer chain', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_offers', to='ats.offer'),
        ),
        migrations.AddField(
            model_name='offerapproval',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offerapproval',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='ats.offer'),
        ),
        migrations.AddField(
            model_name='offerapproval',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_offer_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offerapproval',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='offertemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_offer_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offertemplate',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_template',
            field=models.ForeignKey(blank=True, help_text='Template used to create this offer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='ats.offertemplate'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pipelines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='ats.pipeline'),
        ),
        migrations.AddField(
            model_name='pipelinestage',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='ats.pipeline'),
        ),
        migrations.AddField(
            model_name='application',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='ats.pipelinestage'),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['email'], name='ats_candida_email_625af4_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['source', 'created_at'], name='ats_candida_source_936892_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(fields=('tenant', 'email'), name='ats_candidate_unique_tenant_email'),
        ),
        migrations.AlterUniqueTogether(
            name='interviewfeedback',
            unique_together={('interview', 'interviewer')},
        ),
        migrations.AddIndex(
            model_name='interviewslot',
            index=models.Index(fields=['interviewer', 'start_time'], name='ats_intervi_intervi_fb444f_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewslot',
            index=models.Index(fields=['is_available', 'start_time'], name='ats_intervi_is_avai_0e75b5_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewslot',
            index=models.Index(fields=['start_time', 'end_time'], name='ats_intervi_start_t_50ca6e_idx'),
        ),
        migrations.AddConstraint(
            model_name='interviewslot',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='ats_interviewslot_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='interviewtemplate',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='ats_interviewtemplate_unique_tenant_name'),
        ),
        migrations.AddConstraint(
            model_name='interviewtemplate',
            constraint=models.CheckConstraint(condition=models.Q(('required_interviewers__gte', 1)), name='ats_interviewtemplate_min_interviewers'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['application', 'status'], name='ats_intervi_applica_87ea9f_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['scheduled_start', 'status'], name='ats_intervi_schedul_914a5f_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['interview_type', 'scheduled_start'], name='ats_intervi_intervi_2e531f_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobcategory',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='ats_jobcategory_unique_tenant_slug'),
        ),
        migrations.AddIndex(
            model_name='offerapproval',
            index=models.Index(fields=['offer', 'status'], name='ats_offerap_offer_i_48af32_idx'),
        ),
        migrations.AddIndex(
            model_name='offerapproval',
            index=models.Index(fields=['approver', 'status'], name='ats_offerap_approve_b6adbf_idx'),
        ),
        migrations.AddIndex(
            model_name='offerapproval',
            index=models.Index(fields=['level', 'status'], name='ats_offerap_level_64f74c_idx'),
        ),
        migrations.AddConstraint(
            model_name='offerapproval',
            constraint=models.UniqueConstraint(fields=('offer', 'approver'), name='ats_offerapproval_unique_offer_approver'),
        ),
        migrations.AddConstraint(
            model_name='offertemplate',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='ats_offertemplate_unique_tenant_name'),
        ),
        migrations.AddConstraint(
            model_name='offertemplate',
            constraint=models.CheckConstraint(condition=models.Q(('base_salary_min__lte', models.F('base_salary_max'))), name='ats_offertemplate_salary_min_lte_max'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['application', 'status'], name='ats_offer_applica_975457_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['approval_status'], name='ats_offer_approva_4d5cd2_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['status', 'created_at'], name='ats_offer_status_1544e2_idx'),
        ),
        migrations.AddConstraint(
            model_name='pipeline',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='ats_pipeline_unique_tenant_name'),
        ),
        migrations.AddConstraint(
            model_name='pipeline',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('tenant',), name='ats_pipeline_unique_default_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['status', 'created_at'], name='ats_jobpost_status_2e7b21_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['category', 'status'], name='ats_jobpost_categor_dfa068_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['job_type', 'experience_level'], name='ats_jobpost_job_typ_52e737_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobposting',
            constraint=models.UniqueConstraint(fields=('tenant', 'reference_code'), name='ats_jobposting_unique_tenant_reference'),
        ),
        migrations.AddConstraint(
            model_name='jobposting',
            constraint=models.UniqueConstraint(condition=models.Q(('slug__gt', '')), fields=('tenant', 'slug'), name='ats_jobposting_unique_tenant_slug'),
        ),
        migrations.AddConstraint(
            model_name='jobposting',
            constraint=models.CheckConstraint(condition=models.Q(('salary_min__isnull', True), ('salary_max__isnull', True), ('salary_min__lte', models.F('salary_max')), _connector='OR'), name='ats_jobposting_salary_min_lte_max'),
        ),
        migrations.AddConstraint(
            model_name='jobposting',
            constraint=models.CheckConstraint(condition=models.Q(('positions_count__gte', 1)), name='ats_jobposting_positions_count_gte_1'),
        ),
        migrations.AlterUniqueTogether(
            name='pipelinestage',
            unique_together={('pipeline', 'order')},
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job', 'status'], name='ats_applica_job_id_26f74f_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job', 'current_stage'], name='ats_applica_job_id_bb52a8_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['candidate', 'applied_at'], name='ats_applica_candida_280cd1_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('tenant', 'candidate', 'job'), name='ats_application_unique_tenant_candidate_job'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(('overall_rating__isnull', True), models.Q(('overall_rating__gte', 0), ('overall_rating__lte', 5)), _connector='OR'), name='ats_application_overall_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(('ai_match_score__isnull', True), models.Q(('ai_match_score__gte', 0), ('ai_match_score__lte', 100)), _connector='OR'), name='ats_application_ai_match_score_range'),
        ),
    ]
