# Generated by Django 5.2.7 on 2026-01-25 14:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_add_company_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record is active.', verbose_name='Is active')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('first_name', models.CharField(blank=True, max_length=128, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=128, verbose_name='Last name')),
                ('company', models.CharField(blank=True, max_length=256, verbose_name='Company')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Phone')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('subscribed', 'Subscribed'), ('unsubscribed', 'Unsubscribed'), ('converted', 'Converted'), ('disqualified', 'Disqualified')], db_index=True, default='new', max_length=32, verbose_name='Status')),
                ('source', models.CharField(blank=True, help_text='Lead source or campaign', max_length=256, verbose_name='Source')),
                ('subscribed', models.BooleanField(db_index=True, default=False, help_text='Whether contact is subscribed to email campaigns', verbose_name='Subscribed')),
                ('subscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='Subscribed at')),
                ('unsubscribed', models.BooleanField(db_index=True, default=False, verbose_name='Unsubscribed')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='Unsubscribed at')),
                ('activation_code', models.CharField(blank=True, help_text='Code for confirming subscription', max_length=40, verbose_name='Activation code')),
                ('subscribe_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Subscription request date')),
                ('unsubscribe_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Unsubscription date')),
                ('mailchimp_id', models.CharField(blank=True, help_text='Mailchimp subscriber ID', max_length=255, verbose_name='Mailchimp ID')),
                ('mailchimp_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Last synced to Mailchimp')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_contacts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record is active.', verbose_name='Is active')),
                ('name', models.CharField(max_length=200, verbose_name='Segment name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('filters', models.JSONField(default=dict, help_text='JSON filter criteria for contacts', verbose_name='Filters')),
                ('contact_count', models.PositiveIntegerField(default=0, verbose_name='Contact count')),
                ('last_calculated_at', models.DateTimeField(blank=True, null=True, verbose_name='Last calculated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Contact Segment',
                'verbose_name_plural': 'Contact Segments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConversionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record is active.', verbose_name='Is active')),
                ('marketing_id', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Marketing ID')),
                ('event_name', models.CharField(help_text='E.g., purchase, signup, subscription', max_length=128, verbose_name='Event name')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Value')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('metadata', models.JSONField(blank=True, help_text='Additional event data (product ID, campaign, etc.)', null=True, verbose_name='Metadata')),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Conversion Event',
                'verbose_name_plural': 'Conversion Events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record is active.', verbose_name='Is active')),
                ('title', models.CharField(max_length=256, verbose_name='Campaign title')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='Slug')),
                ('campaign_type', models.CharField(choices=[('newsletter', 'Newsletter'), ('email_sequence', 'Email Sequence'), ('triggered', 'Triggered'), ('announcement', 'Announcement')], default='newsletter', max_length=32, verbose_name='Campaign type')),
                ('subject', models.CharField(max_length=256, verbose_name='Email subject')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=32, verbose_name='Status')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled for')),
                ('sent', models.BooleanField(default=False, verbose_name='Sent')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent at')),
                ('sending', models.BooleanField(default=False, verbose_name='Currently sending')),
                ('sender_name', models.CharField(blank=True, max_length=200, verbose_name='Sender name')),
                ('sender_email', models.EmailField(blank=True, max_length=254, verbose_name='Sender email')),
                ('send_html', models.BooleanField(default=True, verbose_name='Send HTML email')),
                ('total_recipients', models.PositiveIntegerField(default=0, verbose_name='Total recipients')),
                ('total_sent', models.PositiveIntegerField(default=0, verbose_name='Total sent')),
                ('total_opens', models.PositiveIntegerField(default=0, verbose_name='Total opens')),
                ('total_clicks', models.PositiveIntegerField(default=0, verbose_name='Total clicks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Marketing Campaign',
                'verbose_name_plural': 'Marketing Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record is active.', verbose_name='Is active')),
                ('opened', models.BooleanField(default=False, verbose_name='Opened')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Opened at')),
                ('clicked', models.BooleanField(default=False, verbose_name='Clicked')),
                ('clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='Clicked at')),
                ('open_count', models.PositiveIntegerField(default=0, verbose_name='Open count')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='Click count')),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_tracking', to='marketing_campaigns.contact', verbose_name='Contact')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='marketing_campaigns.marketingcampaign', verbose_name='Campaign')),
            ],
            options={
                'verbose_name': 'Campaign Tracking',
                'verbose_name_plural': 'Campaign Tracking',
            },
        ),
        migrations.CreateModel(
            name='CampaignAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='campaign_attachments/', verbose_name='File')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='marketing_campaigns.marketingcampaign', verbose_name='Campaign')),
            ],
            options={
                'verbose_name': 'Campaign Attachment',
                'verbose_name_plural': 'Campaign Attachments',
            },
        ),
        migrations.CreateModel(
            name='MessageArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('url', models.URLField(blank=True, help_text='Optional link for this article', verbose_name='Link')),
                ('image', models.ImageField(blank=True, null=True, upload_to='campaign_articles/', verbose_name='Image')),
                ('sortorder', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Sort order')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='marketing_campaigns.marketingcampaign', verbose_name='Campaign')),
            ],
            options={
                'verbose_name': 'Campaign Article',
                'verbose_name_plural': 'Campaign Articles',
                'ordering': ['sortorder'],
            },
        ),
        migrations.CreateModel(
            name='VisitEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record is active.', verbose_name='Is active')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('marketing_id', models.CharField(blank=True, db_index=True, help_text='Anonymous visitor tracking ID', max_length=32, verbose_name='Marketing ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('country', models.CharField(blank=True, db_index=True, max_length=2, verbose_name='Country')),
                ('device_type', models.CharField(blank=True, max_length=32, verbose_name='Device type')),
                ('browser', models.CharField(blank=True, max_length=32, verbose_name='Browser')),
                ('os', models.CharField(blank=True, max_length=32, verbose_name='OS')),
                ('path', models.CharField(max_length=256, verbose_name='Path')),
                ('method', models.CharField(default='GET', max_length=8, verbose_name='HTTP Method')),
                ('utm_source', models.CharField(blank=True, max_length=128, null=True, verbose_name='UTM Source')),
                ('utm_medium', models.CharField(blank=True, max_length=128, null=True, verbose_name='UTM Medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=128, null=True, verbose_name='UTM Campaign')),
                ('utm_content', models.CharField(blank=True, max_length=128, null=True, verbose_name='UTM Content')),
                ('utm_term', models.CharField(blank=True, max_length=128, null=True, verbose_name='UTM Term')),
                ('ref', models.CharField(blank=True, max_length=128, null=True, verbose_name='Referrer')),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Visit Event',
                'verbose_name_plural': 'Visit Events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AggregatedStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record is active.', verbose_name='Is active')),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('country', models.CharField(blank=True, db_index=True, max_length=2, verbose_name='Country')),
                ('device_type', models.CharField(blank=True, max_length=32, verbose_name='Device type')),
                ('total_visits', models.IntegerField(default=0, verbose_name='Total visits')),
                ('total_conversions', models.IntegerField(default=0, verbose_name='Total conversions')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total revenue')),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Aggregated Stats',
                'verbose_name_plural': 'Aggregated Stats',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['tenant', 'date'], name='marketing_c_tenant__d6d051_idx')],
                'unique_together': {('tenant', 'date', 'country', 'device_type')},
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['tenant', 'email'], name='marketing_c_tenant__b6a431_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['tenant', 'status'], name='marketing_c_tenant__12dd80_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['tenant', 'subscribed'], name='marketing_c_tenant__964eae_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['added_at'], name='marketing_c_added_a_c1a7a1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('tenant', 'email')},
        ),
        migrations.AddIndex(
            model_name='contactsegment',
            index=models.Index(fields=['tenant', 'name'], name='marketing_c_tenant__550318_idx'),
        ),
        migrations.AddIndex(
            model_name='conversionevent',
            index=models.Index(fields=['tenant', 'marketing_id'], name='marketing_c_tenant__9f68c0_idx'),
        ),
        migrations.AddIndex(
            model_name='conversionevent',
            index=models.Index(fields=['tenant', 'event_name'], name='marketing_c_tenant__5677ea_idx'),
        ),
        migrations.AddIndex(
            model_name='conversionevent',
            index=models.Index(fields=['timestamp'], name='marketing_c_timesta_10c902_idx'),
        ),
        migrations.AddIndex(
            model_name='marketingcampaign',
            index=models.Index(fields=['tenant', 'status'], name='marketing_c_tenant__371066_idx'),
        ),
        migrations.AddIndex(
            model_name='marketingcampaign',
            index=models.Index(fields=['tenant', 'scheduled_for'], name='marketing_c_tenant__e05598_idx'),
        ),
        migrations.AddIndex(
            model_name='marketingcampaign',
            index=models.Index(fields=['created_at'], name='marketing_c_created_58d49d_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigntracking',
            index=models.Index(fields=['tenant', 'campaign', 'opened'], name='marketing_c_tenant__11f08a_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigntracking',
            index=models.Index(fields=['tenant', 'contact'], name='marketing_c_tenant__51fa7d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaigntracking',
            unique_together={('tenant', 'contact', 'campaign')},
        ),
        migrations.AlterUniqueTogether(
            name='messagearticle',
            unique_together={('campaign', 'sortorder')},
        ),
        migrations.AddIndex(
            model_name='visitevent',
            index=models.Index(fields=['tenant', 'marketing_id'], name='marketing_c_tenant__dc13a3_idx'),
        ),
        migrations.AddIndex(
            model_name='visitevent',
            index=models.Index(fields=['tenant', 'country'], name='marketing_c_tenant__1fd97c_idx'),
        ),
        migrations.AddIndex(
            model_name='visitevent',
            index=models.Index(fields=['tenant', 'timestamp'], name='marketing_c_tenant__73ae5b_idx'),
        ),
        migrations.AddIndex(
            model_name='visitevent',
            index=models.Index(fields=['device_type'], name='marketing_c_device__27a525_idx'),
        ),
    ]
