# Generated by Django 5.2.7 on 2026-01-18 07:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('subscriptions', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvalaraConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(help_text='Avalara account ID', max_length=255)),
                ('license_key', models.CharField(help_text='Avalara license key (should be encrypted)', max_length=255)),
                ('company_code', models.CharField(help_text='Avalara company code', max_length=100)),
                ('is_sandbox', models.BooleanField(default=True, help_text='Whether to use Avalara sandbox environment')),
                ('company_name', models.CharField(max_length=255)),
                ('tax_id', models.CharField(blank=True, help_text='Tax ID (EIN, VAT number, etc.)', max_length=50)),
                ('default_tax_code', models.CharField(default='P0000000', help_text='Default Avalara tax code for products', max_length=50)),
                ('commit_transactions', models.BooleanField(default=False, help_text='Whether to auto-commit transactions in Avalara')),
                ('is_active', models.BooleanField(default=False)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Avalara Configuration',
                'verbose_name_plural': 'Avalara Configurations',
            },
        ),
        migrations.CreateModel(
            name='TaxCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('avalara', 'Avalara AvaTax'), ('manual', 'Manual Calculation'), ('imported', 'Imported')], default='avalara', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Amount before tax', max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, help_text='Total tax amount', max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, help_text='Subtotal + tax', max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('tax_breakdown', models.JSONField(default=list, help_text='Detailed tax breakdown by jurisdiction')),
                ('tax_address', models.JSONField(default=dict, help_text='Address used for tax calculation')),
                ('avalara_transaction_code', models.CharField(blank=True, max_length=255)),
                ('avalara_response', models.JSONField(blank=True, default=dict, help_text='Full Avalara API response')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_calculations', to='payments.paymenttransaction')),
                ('subscription_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_calculations', to='subscriptions.subscriptioninvoice')),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tax Calculation',
                'verbose_name_plural': 'Tax Calculations',
                'ordering': ['-calculated_at'],
                'indexes': [models.Index(fields=['payment_transaction'], name='tax_taxcalc_payment_93fc45_idx'), models.Index(fields=['subscription_invoice'], name='tax_taxcalc_subscri_1b6f9d_idx'), models.Index(fields=['-calculated_at'], name='tax_taxcalc_calcula_455029_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaxExemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exemption_type', models.CharField(choices=[('resale', 'Resale Certificate'), ('nonprofit', 'Nonprofit Organization'), ('government', 'Government Entity'), ('educational', 'Educational Institution'), ('religious', 'Religious Organization'), ('diplomatic', 'Diplomatic/Consular'), ('other', 'Other')], max_length=20)),
                ('exemption_number', models.CharField(help_text='Certificate or exemption number', max_length=100)),
                ('country', models.CharField(default='US', max_length=2)),
                ('state_province', models.CharField(blank=True, help_text='State/province where exemption applies', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('pending', 'Pending Verification')], db_index=True, default='pending', max_length=20)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('certificate_file', models.FileField(blank=True, help_text='Uploaded exemption certificate', null=True, upload_to='tax_exemptions/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_exemptions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tax Exemption',
                'verbose_name_plural': 'Tax Exemptions',
                'ordering': ['-issue_date'],
                'indexes': [models.Index(fields=['customer', 'status'], name='tax_taxexem_custome_1f8621_idx'), models.Index(fields=['exemption_number'], name='tax_taxexem_exempti_5c9511_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='US', max_length=2)),
                ('state_province', models.CharField(blank=True, help_text='State, province, or region', max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('tax_type', models.CharField(choices=[('sales', 'Sales Tax'), ('vat', 'Value Added Tax (VAT)'), ('gst', 'Goods and Services Tax (GST)'), ('pst', 'Provincial Sales Tax (PST)'), ('hst', 'Harmonized Sales Tax (HST)'), ('excise', 'Excise Tax')], default='sales', max_length=20)),
                ('rate', models.DecimalField(decimal_places=5, help_text='Tax rate as decimal (e.g., 0.08500 for 8.5%)', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00000'))])),
                ('effective_start', models.DateField()),
                ('effective_end', models.DateField(blank=True, null=True)),
                ('avalara_jurisdiction_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tax Rate',
                'verbose_name_plural': 'Tax Rates',
                'ordering': ['country', 'state_province', 'city'],
                'indexes': [models.Index(fields=['country', 'state_province'], name='tax_taxrate_country_e740fd_idx'), models.Index(fields=['postal_code'], name='tax_taxrate_postal__122054_idx'), models.Index(fields=['is_active', 'effective_start'], name='tax_taxrate_is_acti_9c3ce8_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaxRemittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remittance_id', models.CharField(db_index=True, help_text='Unique remittance identifier (auto-generated)', max_length=50, unique=True)),
                ('country', models.CharField(default='US', max_length=2)),
                ('state_province', models.CharField(blank=True, max_length=100)),
                ('authority_name', models.CharField(help_text="Tax authority name (e.g., 'California Department of Tax and Fee Administration')", max_length=200)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('tax_collected', models.DecimalField(decimal_places=2, help_text='Total tax collected during period', max_digits=12)),
                ('tax_owed', models.DecimalField(decimal_places=2, help_text='Total tax owed to authority', max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount paid', max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('paid', 'Paid'), ('failed', 'Failed'), ('overdue', 'Overdue')], db_index=True, default='scheduled', max_length=20)),
                ('due_date', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('filing_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='quarterly', max_length=20)),
                ('filing_reference', models.CharField(blank=True, help_text='Confirmation or filing reference number', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_remittances', to='payments.paymenttransaction')),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tax Remittance',
                'verbose_name_plural': 'Tax Remittances',
                'ordering': ['-due_date'],
                'indexes': [models.Index(fields=['remittance_id'], name='tax_taxremi_remitta_478fa5_idx'), models.Index(fields=['status', 'due_date'], name='tax_taxremi_status_2fb3d6_idx'), models.Index(fields=['country', 'state_province'], name='tax_taxremi_country_759ae5_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaxReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(db_index=True, help_text='Unique report number (auto-generated)', max_length=50, unique=True)),
                ('report_type', models.CharField(choices=[('monthly', 'Monthly Report'), ('quarterly', 'Quarterly Report'), ('annual', 'Annual Report'), ('custom', 'Custom Period')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_taxable_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total taxable sales', max_digits=12)),
                ('total_exempt_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total tax-exempt sales', max_digits=12)),
                ('total_tax_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total tax collected', max_digits=12)),
                ('total_tax_remitted', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total tax remitted to authorities', max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('jurisdiction_breakdown', models.JSONField(default=list, help_text='Tax breakdown by jurisdiction')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='tax_reports/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_reports_generated', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tax Report',
                'verbose_name_plural': 'Tax Reports',
                'ordering': ['-period_end'],
                'indexes': [models.Index(fields=['report_number'], name='tax_taxrepo_report__86d7ee_idx'), models.Index(fields=['report_type', '-period_end'], name='tax_taxrepo_report__7cc830_idx')],
            },
        ),
    ]
