# Generated by Django 5.2.7 on 2026-01-18 07:40

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Global unique identifier for this user', unique=True)),
                ('email', models.EmailField(db_index=True, help_text='Email address (used for login)', max_length=254, unique=True)),
                ('mfa_enabled', models.BooleanField(db_index=True, default=False, help_text='Whether user has MFA enabled via allauth.mfa')),
                ('mfa_grace_period_end', models.DateTimeField(blank=True, help_text='End of 30-day grace period for MFA setup', null=True)),
                ('anonymous_mode', models.BooleanField(db_index=True, default=False, help_text='Whether user is browsing anonymously')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'core_identity_customuser',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CoopSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_type', models.CharField(choices=[('academic', 'Academic Supervisor (Professor/Teacher)'), ('workplace', 'Workplace Supervisor (Company Manager)')], db_index=True, help_text='Type of supervisor', max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, help_text='Contact email', max_length=254, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128, null=True, region=None)),
                ('institution_name', models.CharField(blank=True, help_text='Educational institution name (for academic supervisors)', max_length=200)),
                ('department', models.CharField(blank=True, help_text='Department or faculty', max_length=200)),
                ('job_title', models.CharField(blank=True, help_text='Job title at company (for workplace supervisors)', max_length=150)),
                ('credentials', models.CharField(blank=True, help_text='Professional credentials or certifications', max_length=200)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether supervisor is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Platform account if supervisor is also a user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coop_supervisor_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Co-op Supervisor',
                'verbose_name_plural': 'Co-op Supervisors',
                'db_table': 'core_identity_coopsupervisor',
            },
        ),
        migrations.CreateModel(
            name='MarketplaceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Whether user has activated their marketplace profile')),
                ('professional_title', models.CharField(help_text='Professional title or headline', max_length=150)),
                ('skills', models.JSONField(blank=True, default=list, help_text='List of professional skills')),
                ('available_for_work', models.BooleanField(db_index=True, default=False, help_text='Currently available for new projects')),
                ('availability_hours_per_week', models.PositiveIntegerField(blank=True, help_text='Available hours per week', null=True)),
                ('hourly_rate_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum hourly rate', max_digits=10, null=True)),
                ('hourly_rate_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum hourly rate', max_digits=10, null=True)),
                ('rate_currency', models.CharField(default='CAD', help_text='Currency code (ISO 4217)', max_length=3)),
                ('portfolio_url', models.URLField(blank=True, help_text='Portfolio website URL')),
                ('cv_file', models.FileField(blank=True, help_text='Latest CV/resume file', null=True, upload_to='cvs/')),
                ('profile_visibility', models.CharField(choices=[('public', 'Public - Anyone can view'), ('tenants_only', 'Tenants Only - Only organizations I joined'), ('private', 'Private - Hidden')], db_index=True, default='private', help_text='Who can view this marketplace profile', max_length=20)),
                ('completed_projects', models.PositiveIntegerField(default=0, help_text='Total completed projects')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, help_text='Total earnings across all projects', max_digits=12)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, help_text='Average rating from clients (0-5)', max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_at', models.DateTimeField(blank=True, help_text='When profile was first activated', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marketplace Profile',
                'verbose_name_plural': 'Marketplace Profiles',
                'db_table': 'core_identity_marketplaceprofile',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, help_text='Student ID from educational institution', max_length=50, unique=True)),
                ('institution_name', models.CharField(help_text='Name of educational institution', max_length=200)),
                ('program_name', models.CharField(help_text='Program/degree name', max_length=200)),
                ('program_level', models.CharField(choices=[('diploma', 'Diploma'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('doctorate', 'Doctorate')], help_text='Level of study', max_length=50)),
                ('program_start_date', models.DateField(help_text='When student started the program')),
                ('expected_graduation_date', models.DateField(help_text='Expected graduation date')),
                ('total_coop_terms_required', models.PositiveIntegerField(default=3, help_text='Total co-op terms required for graduation')),
                ('total_hours_required', models.PositiveIntegerField(default=1800, help_text='Total hours required across all co-op terms')),
                ('academic_advisor_email', models.EmailField(help_text='Email of academic advisor or co-op coordinator', max_length=254)),
                ('academic_advisor_name', models.CharField(help_text='Name of academic advisor or co-op coordinator', max_length=200)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether student is currently enrolled')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'db_table': 'core_identity_studentprofile',
            },
        ),
        migrations.CreateModel(
            name='TenantInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique invitation token', unique=True)),
                ('email', models.EmailField(db_index=True, help_text='Email address being invited', max_length=254)),
                ('tenant_uuid', models.UUIDField(db_index=True, help_text='UUID of the tenant inviting this user')),
                ('tenant_name', models.CharField(help_text='Cached name of tenant for display', max_length=200)),
                ('invited_role', models.CharField(help_text='Role user will have when they join', max_length=20)),
                ('invited_by_email', models.EmailField(help_text='Email of user who sent the invitation', max_length=254)),
                ('invited_by_name', models.CharField(help_text='Name of user who sent the invitation', max_length=200)),
                ('custom_message', models.TextField(blank=True, help_text='Optional personal message from inviter', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Current status of invitation', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(help_text='When invitation expires (default: 7 days)')),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When invitation was accepted', null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who accepted this invitation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant Invitation',
                'verbose_name_plural': 'Tenant Invitations',
                'db_table': 'core_identity_tenantinvitation',
            },
        ),
        migrations.CreateModel(
            name='UserIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Display name shown across platform', max_length=100)),
                ('avatar', models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, help_text='Short bio or introduction', max_length=1000)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Primary phone number', max_length=128, null=True, region=None)),
                ('location_city', models.CharField(blank=True, help_text='City of residence', max_length=100)),
                ('location_state', models.CharField(blank=True, help_text='State/Province', max_length=100)),
                ('location_country', models.CharField(blank=True, default='CA', help_text='Country code (ISO 3166-1 alpha-2)', max_length=100)),
                ('timezone', models.CharField(default='America/Toronto', help_text='IANA timezone identifier', max_length=50)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('github_url', models.URLField(blank=True, help_text='GitHub profile URL')),
                ('twitter_handle', models.CharField(blank=True, help_text='Twitter/X handle (without @)', max_length=100)),
                ('website_url', models.URLField(blank=True, help_text='Personal website URL')),
                ('languages', models.JSONField(blank=True, default=list, help_text='List of languages spoken with proficiency levels')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Identity',
                'verbose_name_plural': 'User Identities',
                'db_table': 'core_identity_useridentity',
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='core_identi_email_e7a3a5_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['uuid'], name='core_identi_uuid_a46753_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['mfa_enabled'], name='core_identi_mfa_ena_64a727_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['created_at'], name='core_identi_created_a70389_idx'),
        ),
        migrations.AddIndex(
            model_name='coopsupervisor',
            index=models.Index(fields=['email'], name='core_identi_email_ccf507_idx'),
        ),
        migrations.AddIndex(
            model_name='coopsupervisor',
            index=models.Index(fields=['supervisor_type'], name='core_identi_supervi_b35eee_idx'),
        ),
        migrations.AddIndex(
            model_name='coopsupervisor',
            index=models.Index(fields=['is_active'], name='core_identi_is_acti_0c4382_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplaceprofile',
            index=models.Index(fields=['user'], name='core_identi_user_id_7cd1ec_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplaceprofile',
            index=models.Index(fields=['is_active', 'available_for_work'], name='core_identi_is_acti_684ac8_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplaceprofile',
            index=models.Index(fields=['profile_visibility'], name='core_identi_profile_8e6766_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplaceprofile',
            index=models.Index(fields=['created_at'], name='core_identi_created_dd0412_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['user'], name='core_identi_user_id_129200_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['student_id'], name='core_identi_student_ca6fad_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['institution_name'], name='core_identi_institu_a008d6_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['is_active'], name='core_identi_is_acti_e0fbe1_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantinvitation',
            index=models.Index(fields=['uuid'], name='core_identi_uuid_d40b03_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantinvitation',
            index=models.Index(fields=['email', 'status'], name='core_identi_email_0ae181_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantinvitation',
            index=models.Index(fields=['tenant_uuid', 'status'], name='core_identi_tenant__f5d998_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantinvitation',
            index=models.Index(fields=['expires_at'], name='core_identi_expires_c29570_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantinvitation',
            index=models.Index(fields=['created_at'], name='core_identi_created_d59d95_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantinvitation',
            unique_together={('email', 'tenant_uuid', 'status')},
        ),
        migrations.AddIndex(
            model_name='useridentity',
            index=models.Index(fields=['user'], name='core_identi_user_id_960b0d_idx'),
        ),
        migrations.AddIndex(
            model_name='useridentity',
            index=models.Index(fields=['location_country'], name='core_identi_locatio_7a63c2_idx'),
        ),
        migrations.AddIndex(
            model_name='useridentity',
            index=models.Index(fields=['created_at'], name='core_identi_created_775509_idx'),
        ),
    ]
