# Generated by Django 5.2.7 on 2026-01-18 07:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr_core', '0001_initial'),
        ('payments', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings')], default='checking', max_length=20)),
                ('routing_number', models.CharField(help_text='Bank routing number (encrypted in production)', max_length=9)),
                ('account_number_last4', models.CharField(help_text='Last 4 digits of account number', max_length=4)),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('account_number', models.CharField(help_text='Full account number (should be encrypted)', max_length=255)),
                ('allocation_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount'), ('remainder', 'Remainder')], default='remainder', max_length=20)),
                ('allocation_value', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage (0-100) or fixed amount', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=True, help_text='Primary account for payroll')),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_deposits', to='hr_core.employee')),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Direct Deposit',
                'verbose_name_plural': 'Direct Deposits',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text='Gross wages before deductions', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('regular_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Regular hours worked', max_digits=6)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Overtime hours worked', max_digits=6)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate (if applicable)', max_digits=10, null=True)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Bonus or commission', max_digits=12)),
                ('adjustment_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Manual adjustment (can be negative)', max_digits=12)),
                ('federal_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Federal income tax withheld', max_digits=12)),
                ('state_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='State income tax withheld', max_digits=12)),
                ('local_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Local income tax withheld', max_digits=12)),
                ('social_security', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Social Security (FICA) tax', max_digits=12)),
                ('medicare', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Medicare tax', max_digits=12)),
                ('total_taxes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all taxes', max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all deductions', max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Net pay (take-home)', max_digits=12)),
                ('payment_method', models.CharField(choices=[('direct_deposit', 'Direct Deposit'), ('check', 'Check'), ('cash', 'Cash')], default='direct_deposit', max_length=20)),
                ('paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('ytd_gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Year-to-date gross', max_digits=12)),
                ('ytd_taxes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Year-to-date taxes', max_digits=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direct_deposit', models.ForeignKey(blank=True, help_text='Direct deposit account used', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.directdeposit')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_payments', to='hr_core.employee')),
                ('payment_transaction', models.ForeignKey(blank=True, help_text='Payment transaction record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_payments', to='payments.paymenttransaction')),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Employee Payment',
                'verbose_name_plural': 'Employee Payments',
                'ordering': ['employee__user__last_name', 'employee__user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_type', models.CharField(choices=[('health_insurance', 'Health Insurance'), ('dental_insurance', 'Dental Insurance'), ('vision_insurance', 'Vision Insurance'), ('retirement_401k', '401(k) Retirement'), ('retirement_ira', 'IRA Retirement'), ('hsa', 'Health Savings Account'), ('fsa', 'Flexible Spending Account'), ('union_dues', 'Union Dues'), ('garnishment', 'Wage Garnishment'), ('child_support', 'Child Support'), ('loan_repayment', 'Loan Repayment'), ('other', 'Other')], max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('pre_tax', models.BooleanField(default=False, help_text='Whether deduction is pre-tax (reduces taxable income)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='payroll.employeepayment')),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Payroll Deduction',
                'verbose_name_plural': 'Payroll Deductions',
                'ordering': ['deduction_type'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_number', models.CharField(db_index=True, help_text='Payroll run number (e.g., 2026-01-001)', max_length=50, unique=True)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('semi_monthly', 'Semi-monthly'), ('monthly', 'Monthly')], default='biweekly', max_length=20)),
                ('pay_period_start', models.DateField(help_text='Start date of pay period')),
                ('pay_period_end', models.DateField(help_text='End date of pay period')),
                ('pay_date', models.DateField(help_text='Date employees will be paid')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('approved', 'Approved'), ('paid', 'Paid'), ('failed', 'Failed')], db_index=True, default='draft', max_length=20)),
                ('employee_count', models.PositiveIntegerField(default=0, help_text='Number of employees in this payroll run')),
                ('total_gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total gross wages', max_digits=12)),
                ('total_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total net pay', max_digits=12)),
                ('total_taxes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total tax withholdings', max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total deductions (benefits, 401k, etc.)', max_digits=12)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Payroll Run',
                'verbose_name_plural': 'Payroll Runs',
                'ordering': ['-pay_date'],
            },
        ),
        migrations.AddField(
            model_name='employeepayment',
            name='payroll_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_payments', to='payroll.payrollrun'),
        ),
        migrations.CreateModel(
            name='PayrollTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(choices=[('federal_income', 'Federal Income Tax'), ('state_income', 'State Income Tax'), ('local_income', 'Local Income Tax'), ('social_security', 'Social Security (FICA)'), ('medicare', 'Medicare'), ('unemployment', 'Unemployment Tax')], max_length=30)),
                ('taxable_amount', models.DecimalField(decimal_places=2, help_text='Amount subject to this tax', max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=4, help_text='Tax rate as decimal (e.g., 0.22 for 22%)', max_digits=6)),
                ('tax_amount', models.DecimalField(decimal_places=2, help_text='Calculated tax amount', max_digits=12)),
                ('jurisdiction', models.CharField(blank=True, help_text='State, city, or other jurisdiction', max_length=100)),
                ('calculation_data', models.JSONField(blank=True, default=dict, help_text='Tax calculation details (brackets, deductions, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_records', to='payroll.employeepayment')),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Payroll Tax',
                'verbose_name_plural': 'Payroll Taxes',
                'ordering': ['tax_type'],
            },
        ),
        migrations.CreateModel(
            name='PayStub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stub_number', models.CharField(db_index=True, help_text='Unique pay stub number', max_length=50, unique=True)),
                ('pdf_file', models.FileField(blank=True, help_text='Generated PDF pay stub', null=True, upload_to='paystubs/%Y/%m/')),
                ('pdf_url', models.URLField(blank=True)),
                ('employee_viewed', models.BooleanField(default=False)),
                ('employee_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('employee_payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pay_stub', to='payroll.employeepayment')),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Pay Stub',
                'verbose_name_plural': 'Pay Stubs',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['run_number'], name='payroll_pay_run_num_e80b2a_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['status', '-pay_date'], name='payroll_pay_status_bb98aa_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['-pay_date'], name='payroll_pay_pay_dat_c1e36b_idx'),
        ),
        migrations.AddIndex(
            model_name='employeepayment',
            index=models.Index(fields=['payroll_run', 'employee'], name='payroll_emp_payroll_b2b0be_idx'),
        ),
        migrations.AddIndex(
            model_name='employeepayment',
            index=models.Index(fields=['employee', '-created_at'], name='payroll_emp_employe_fddf2e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employeepayment',
            unique_together={('payroll_run', 'employee')},
        ),
    ]
