# Generated by Django 5.2.7 on 2026-01-18 07:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_account_id', models.CharField(db_index=True, help_text='Stripe Connect account ID (acct_xxxxx)', max_length=255, unique=True)),
                ('account_type', models.CharField(choices=[('express', 'Stripe Express'), ('standard', 'Stripe Standard'), ('custom', 'Stripe Custom')], default='express', max_length=20)),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('pending', 'Pending Verification'), ('enabled', 'Enabled'), ('disabled', 'Disabled'), ('rejected', 'Rejected')], db_index=True, default='incomplete', max_length=20)),
                ('charges_enabled', models.BooleanField(default=False, help_text='Can receive charges')),
                ('payouts_enabled', models.BooleanField(default=False, help_text='Can receive payouts')),
                ('transfers_enabled', models.BooleanField(default=False, help_text='Can receive transfers')),
                ('requirements', models.JSONField(default=dict, help_text='Stripe requirements data (currently_due, eventually_due, etc.)')),
                ('requirements_pending', models.BooleanField(default=True, help_text='Whether account has pending requirements')),
                ('verification_status', models.CharField(blank=True, max_length=50)),
                ('verification_disabled_reason', models.CharField(blank=True, max_length=255)),
                ('business_type', models.CharField(blank=True, help_text='individual, company, etc.', max_length=50)),
                ('country', models.CharField(default='US', max_length=2)),
                ('default_currency', models.CharField(default='USD', max_length=3)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('dashboard_link_expires', models.DateTimeField(blank=True, help_text='Expiration of Stripe Dashboard login link', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_connected_account', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Connected Account',
                'verbose_name_plural': 'Connected Accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.CharField(choices=[('manual', 'Manual'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('weekly_anchor', models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], default='friday', help_text='Day of week for weekly payouts', max_length=20)),
                ('monthly_anchor', models.PositiveSmallIntegerField(default=1, help_text='Day of month for monthly payouts (1-31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('delay_days', models.PositiveIntegerField(default=2, help_text='Days to delay payout after period end (Stripe standard is 2)')),
                ('minimum_payout', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Minimum amount required for payout', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_schedule', to='stripe_connect.connectedaccount')),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Payout Schedule',
                'verbose_name_plural': 'Payout Schedules',
            },
        ),
        migrations.CreateModel(
            name='PlatformFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Fee name (e.g., 'Standard Marketplace Fee', 'Premium Service Fee')", max_length=100)),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Percentage fee (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed fee amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('min_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum fee amount (null = no minimum)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum fee amount (null = no maximum)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('applies_to', models.CharField(default='all', help_text='What this fee applies to (all, services, projects, etc.)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Platform Fee',
                'verbose_name_plural': 'Platform Fees',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StripeConnectOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', max_length=20)),
                ('onboarding_url', models.URLField(blank=True, help_text='Stripe Connect onboarding URL')),
                ('onboarding_url_expires', models.DateTimeField(blank=True, help_text='When onboarding URL expires', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('return_url', models.URLField(blank=True, help_text='URL to return to after onboarding')),
                ('refresh_url', models.URLField(blank=True, help_text='URL to refresh onboarding if user exits')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='stripe_connect.connectedaccount')),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Stripe Connect Onboarding',
                'verbose_name_plural': 'Stripe Connect Onboardings',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_id', models.CharField(db_index=True, help_text='Internal transfer ID', max_length=255, unique=True)),
                ('stripe_transfer_id', models.CharField(db_index=True, help_text='Stripe transfer ID (tr_xxxxx)', max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('paid', 'Paid'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at_stripe', models.DateTimeField(help_text='When transfer was created in Stripe')),
                ('arrival_date', models.DateTimeField(blank=True, help_text="Expected arrival date in provider's bank", null=True)),
                ('failure_code', models.CharField(blank=True, max_length=100)),
                ('failure_message', models.TextField(blank=True)),
                ('reversed', models.BooleanField(default=False)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='stripe_connect.connectedaccount')),
                ('source_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe_transfers', to='payments.paymenttransaction')),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BalanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_balance_transaction_id', models.CharField(db_index=True, help_text='Stripe balance transaction ID (txn_xxxxx)', max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Gross amount (positive = credit, negative = debit)', max_digits=12)),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fees deducted from amount', max_digits=12)),
                ('net', models.DecimalField(decimal_places=2, help_text='Net amount (amount - fee)', max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('transaction_type', models.CharField(choices=[('charge', 'Charge'), ('refund', 'Refund'), ('transfer', 'Transfer'), ('payout', 'Payout'), ('fee', 'Fee'), ('adjustment', 'Adjustment')], db_index=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('source_id', models.CharField(blank=True, help_text='Stripe ID of source object (charge, transfer, etc.)', max_length=255)),
                ('available_on', models.DateTimeField(help_text='When funds become available for payout')),
                ('created_at_stripe', models.DateTimeField(help_text='When transaction was created in Stripe')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('connected_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_transactions', to='stripe_connect.connectedaccount')),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_transactions', to='stripe_connect.transfer')),
            ],
            options={
                'verbose_name': 'Balance Transaction',
                'verbose_name_plural': 'Balance Transactions',
                'ordering': ['-created_at_stripe'],
            },
        ),
        migrations.AddIndex(
            model_name='connectedaccount',
            index=models.Index(fields=['stripe_account_id'], name='stripe_conn_stripe__6bc99e_idx'),
        ),
        migrations.AddIndex(
            model_name='connectedaccount',
            index=models.Index(fields=['provider'], name='stripe_conn_provide_6f8ef7_idx'),
        ),
        migrations.AddIndex(
            model_name='connectedaccount',
            index=models.Index(fields=['status'], name='stripe_conn_status_cd83a2_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['transfer_id'], name='stripe_conn_transfe_b754a7_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['stripe_transfer_id'], name='stripe_conn_stripe__cb9531_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['connected_account', '-created_at'], name='stripe_conn_connect_b5bbcc_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['status', '-created_at'], name='stripe_conn_status_212507_idx'),
        ),
        migrations.AddIndex(
            model_name='balancetransaction',
            index=models.Index(fields=['stripe_balance_transaction_id'], name='stripe_conn_stripe__43f01c_idx'),
        ),
        migrations.AddIndex(
            model_name='balancetransaction',
            index=models.Index(fields=['connected_account', '-created_at_stripe'], name='stripe_conn_connect_523626_idx'),
        ),
        migrations.AddIndex(
            model_name='balancetransaction',
            index=models.Index(fields=['transaction_type', '-created_at_stripe'], name='stripe_conn_transac_ea6f6c_idx'),
        ),
    ]
