# Generated by Django 5.2.7 on 2026-01-18 07:40

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicServiceCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Primary key for public catalog entry', primary_key=True, serialize=False)),
                ('provider_uuid', models.UUIDField(db_index=True, help_text='UUID of source ServiceProvider in tenant schema', unique=True)),
                ('tenant_id', models.IntegerField(db_index=True, help_text='ID of source tenant')),
                ('tenant_schema_name', models.CharField(db_index=True, help_text='Schema name of source tenant', max_length=100)),
                ('provider_name', models.CharField(db_index=True, help_text='Provider display name', max_length=255)),
                ('provider_avatar_url', models.URLField(blank=True, help_text='Provider avatar/logo URL (if available)')),
                ('bio', models.TextField(blank=True, help_text='Sanitized HTML provider bio/description')),
                ('tagline', models.CharField(blank=True, help_text='Short tagline or headline', max_length=255)),
                ('provider_type', models.CharField(blank=True, db_index=True, help_text='Provider type: individual, company, etc.', max_length=100)),
                ('location_city', models.CharField(blank=True, db_index=True, help_text='Provider location city', max_length=100)),
                ('location_state', models.CharField(blank=True, help_text='Provider location state/province', max_length=100)),
                ('location_country', models.CharField(blank=True, db_index=True, default='', help_text='Provider location country', max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Geographic location (PostGIS Point for geo-queries)', null=True, srid=4326)),
                ('can_work_remotely', models.BooleanField(db_index=True, default=False, help_text='Whether provider can work remotely')),
                ('can_work_onsite', models.BooleanField(db_index=True, default=False, help_text='Whether provider can work on-site')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate (optional)', max_digits=10, null=True)),
                ('minimum_budget', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum project budget (optional)', max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', help_text='Currency code (ISO 4217)', max_length=3)),
                ('category_names', models.JSONField(default=list, help_text="List of category names (e.g., ['Web Development', 'Design'])")),
                ('category_slugs', models.JSONField(db_index=True, default=list, help_text="List of category slugs for filtering (e.g., ['web-dev', 'design'])")),
                ('skills_data', models.JSONField(default=list, help_text="List of skill objects: [{'name': 'Python', 'level': 'expert', 'years_experience': 5}]")),
                ('rating_avg', models.DecimalField(blank=True, db_index=True, decimal_places=2, help_text='Average rating from reviews', max_digits=3, null=True)),
                ('total_reviews', models.IntegerField(db_index=True, default=0, help_text='Total number of reviews')),
                ('completed_jobs_count', models.IntegerField(default=0, help_text='Number of completed jobs/contracts')),
                ('response_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Response rate percentage', max_digits=5, null=True)),
                ('avg_response_time_hours', models.IntegerField(blank=True, help_text='Average response time in hours', null=True)),
                ('availability_status', models.CharField(db_index=True, default='available', help_text='Availability status: available, busy, unavailable', max_length=50)),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text='Whether provider is verified')),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Whether provider is featured in marketplace')),
                ('is_accepting_work', models.BooleanField(db_index=True, default=True, help_text='Whether provider is accepting new service requests and contracts')),
                ('published_at', models.DateTimeField(db_index=True, help_text='When provider was published to marketplace')),
                ('synced_at', models.DateTimeField(auto_now=True, help_text='When this catalog entry was last synced from tenant')),
                ('booking_url', models.URLField(help_text='URL to book/contact this provider (redirects to tenant domain)')),
            ],
            options={
                'verbose_name': 'Public Service Catalog Entry',
                'verbose_name_plural': 'Public Service Catalog Entries',
                'db_table': 'services_public_catalog',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['provider_name'], name='svc_pub_provider_idx'), models.Index(fields=['provider_type', 'can_work_remotely'], name='svc_pub_type_idx'), models.Index(fields=['location_city', 'location_state'], name='svc_pub_location_idx'), models.Index(fields=['-rating_avg', '-total_reviews'], name='svc_pub_rating_idx'), models.Index(fields=['-published_at'], name='svc_pub_published_idx'), models.Index(fields=['availability_status', 'is_accepting_work'], name='svc_pub_availability_idx')],
            },
        ),
    ]
