# Generated by Django 5.2.7 on 2026-01-02 10:10

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import integrations.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('integration_type', models.CharField(choices=[('calendar', 'Calendar'), ('email', 'Email'), ('job_board', 'Job Board'), ('background_check', 'Background Check'), ('esign', 'E-Signature'), ('hris', 'HRIS'), ('messaging', 'Messaging'), ('video', 'Video Conferencing'), ('payment', 'Payment'), ('analytics', 'Analytics'), ('crm', 'CRM'), ('storage', 'Storage')], help_text='Category of integration', max_length=30)),
                ('provider', models.CharField(choices=[('google_calendar', 'Google Calendar'), ('outlook_calendar', 'Outlook Calendar'), ('gmail', 'Gmail'), ('outlook_email', 'Outlook Email'), ('smtp', 'SMTP'), ('sendgrid', 'SendGrid'), ('mailgun', 'Mailgun'), ('indeed', 'Indeed'), ('linkedin', 'LinkedIn'), ('glassdoor', 'Glassdoor'), ('ziprecruiter', 'ZipRecruiter'), ('checkr', 'Checkr'), ('sterling', 'Sterling'), ('hireright', 'HireRight'), ('docusign', 'DocuSign'), ('hellosign', 'HelloSign'), ('adobe_sign', 'Adobe Sign'), ('bamboohr', 'BambooHR'), ('workday', 'Workday'), ('adp', 'ADP'), ('gusto', 'Gusto'), ('slack', 'Slack'), ('microsoft_teams', 'Microsoft Teams'), ('discord', 'Discord'), ('zoom', 'Zoom'), ('teams_meeting', 'Microsoft Teams Meeting'), ('google_meet', 'Google Meet'), ('stripe', 'Stripe'), ('google_analytics', 'Google Analytics'), ('salesforce', 'Salesforce'), ('hubspot', 'HubSpot'), ('aws_s3', 'AWS S3'), ('google_drive', 'Google Drive')], help_text='Third-party provider', max_length=50)),
                ('name', models.CharField(help_text='Display name for this integration instance', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('pending', 'Pending Setup'), ('connecting', 'Connecting'), ('active', 'Active'), ('error', 'Error'), ('expired', 'Credentials Expired'), ('suspended', 'Suspended')], default='inactive', max_length=20)),
                ('status_message', models.TextField(blank=True, help_text='Status details or error message')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Integration-specific configuration')),
                ('is_enabled', models.BooleanField(default=True)),
                ('auto_sync', models.BooleanField(default=False, help_text='Enable automatic data synchronization')),
                ('sync_interval_minutes', models.PositiveIntegerField(default=60, help_text='Sync interval in minutes (5-1440)', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)])),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('next_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_error_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_integrations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Tenant this integration belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Integration',
                'verbose_name_plural': 'Integrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('auth_type', models.CharField(choices=[('oauth2', 'OAuth 2.0'), ('api_key', 'API Key'), ('basic', 'Basic Auth'), ('jwt', 'JWT Token'), ('webhook', 'Webhook Secret')], default='oauth2', max_length=20)),
                ('access_token', integrations.models.EncryptedTextField(blank=True, help_text='OAuth access token (encrypted)')),
                ('refresh_token', integrations.models.EncryptedTextField(blank=True, help_text='OAuth refresh token (encrypted)')),
                ('token_type', models.CharField(default='Bearer', max_length=50)),
                ('scope', models.TextField(blank=True, help_text='OAuth scopes granted')),
                ('api_key', integrations.models.EncryptedTextField(blank=True, help_text='API key (encrypted)')),
                ('api_secret', integrations.models.EncryptedTextField(blank=True, help_text='API secret (encrypted)')),
                ('username', integrations.models.EncryptedTextField(blank=True)),
                ('password', integrations.models.EncryptedTextField(blank=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Additional credential data')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the access token expires', null=True)),
                ('refresh_expires_at', models.DateTimeField(blank=True, help_text='When the refresh token expires', null=True)),
                ('external_user_id', models.CharField(blank=True, help_text='User ID in external system', max_length=255)),
                ('external_account_id', models.CharField(blank=True, help_text='Account/organization ID in external system', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='integrations.integration')),
            ],
            options={
                'verbose_name': 'Integration Credential',
                'verbose_name_plural': 'Integration Credentials',
            },
        ),
        migrations.CreateModel(
            name='IntegrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('event_type', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('token_refreshed', 'Token Refreshed'), ('sync_started', 'Sync Started'), ('sync_completed', 'Sync Completed'), ('sync_failed', 'Sync Failed'), ('webhook_received', 'Webhook Received'), ('config_changed', 'Configuration Changed'), ('error', 'Error'), ('rate_limited', 'Rate Limited')], max_length=30)),
                ('message', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='integrations.integration')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Integration Event',
                'verbose_name_plural': 'Integration Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sync_type', models.CharField(choices=[('full', 'Full Sync'), ('incremental', 'Incremental Sync'), ('webhook', 'Webhook Triggered'), ('manual', 'Manual Sync'), ('scheduled', 'Scheduled Sync')], default='incremental', max_length=20)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound (from external)'), ('outbound', 'Outbound (to external)'), ('bidirectional', 'Bidirectional')], default='inbound', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partial Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('resource_type', models.CharField(blank=True, help_text='Type of resource being synced (e.g., contacts, events)', max_length=100)),
                ('records_processed', models.PositiveIntegerField(default=0)),
                ('records_created', models.PositiveIntegerField(default=0)),
                ('records_updated', models.PositiveIntegerField(default=0)),
                ('records_deleted', models.PositiveIntegerField(default=0)),
                ('records_failed', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('error_details', models.JSONField(blank=True, default=dict, help_text='Detailed error information')),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('sync_cursor', models.CharField(blank=True, help_text='Cursor/token for incremental sync', max_length=500)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='integrations.integration')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_syncs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Integration Sync Log',
                'verbose_name_plural': 'Integration Sync Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='Descriptive name for this webhook', max_length=255)),
                ('endpoint_path', models.CharField(help_text='Unique URL path for this webhook', max_length=255, unique=True)),
                ('secret_key', models.CharField(help_text='Secret for webhook signature verification', max_length=255)),
                ('signature_header', models.CharField(default='X-Webhook-Signature', help_text='Header name containing signature', max_length=100)),
                ('signature_algorithm', models.CharField(choices=[('sha256', 'HMAC-SHA256'), ('sha1', 'HMAC-SHA1'), ('md5', 'HMAC-MD5')], default='sha256', max_length=20)),
                ('subscribed_events', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='List of event types to process', size=None)),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('total_received', models.PositiveIntegerField(default=0)),
                ('total_processed', models.PositiveIntegerField(default=0)),
                ('total_failed', models.PositiveIntegerField(default=0)),
                ('last_received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='integrations.integration')),
            ],
            options={
                'verbose_name': 'Webhook Endpoint',
                'verbose_name_plural': 'Webhook Endpoints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(help_text='Type of event received', max_length=100)),
                ('event_id', models.CharField(blank=True, help_text='External event ID for deduplication', max_length=255)),
                ('headers', models.JSONField(default=dict, help_text='Request headers')),
                ('payload', models.JSONField(default=dict, help_text='Webhook payload')),
                ('signature_valid', models.BooleanField(default=False, help_text='Whether signature verification passed')),
                ('signature_received', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('retrying', 'Retrying'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('status_message', models.TextField(blank=True)),
                ('response_status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=5)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_result', models.JSONField(blank=True, default=dict, help_text='Result of webhook processing')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='integrations.webhookendpoint')),
            ],
            options={
                'verbose_name': 'Webhook Delivery',
                'verbose_name_plural': 'Webhook Deliveries',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['tenant', 'integration_type'], name='integration_tenant__0a25e4_idx'),
        ),
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['tenant', 'status'], name='integration_tenant__a16d0e_idx'),
        ),
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['provider', 'status'], name='integration_provide_c23515_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='integration',
            unique_together={('tenant', 'provider')},
        ),
        migrations.AddIndex(
            model_name='integrationevent',
            index=models.Index(fields=['integration', '-created_at'], name='integration_integra_b78402_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationevent',
            index=models.Index(fields=['integration', 'event_type'], name='integration_integra_0e1ac2_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationsynclog',
            index=models.Index(fields=['integration', '-started_at'], name='integration_integra_e7ebcf_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationsynclog',
            index=models.Index(fields=['integration', 'status'], name='integration_integra_a48a09_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['endpoint', '-received_at'], name='integration_endpoin_6de2c5_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['endpoint', 'status'], name='integration_endpoin_37e0b3_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['event_id'], name='integration_event_i_07f282_idx'),
        ),
    ]
