# Generated by Django 5.2.7 on 2026-01-09 18:53

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundWebhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name for this webhook', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('url', models.URLField(help_text='URL to send webhooks to', max_length=2048)),
                ('secret', models.CharField(help_text='Secret for signing webhook payloads', max_length=255)),
                ('subscribed_apps', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Apps to subscribe to (empty = all apps)', size=None)),
                ('subscribed_events', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Event types to subscribe to (empty = all events)', size=None)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended - Too Many Failures')], default='active', max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('total_sent', models.PositiveIntegerField(default=0)),
                ('total_successful', models.PositiveIntegerField(default=0)),
                ('total_failed', models.PositiveIntegerField(default=0)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('custom_headers', models.JSONField(blank=True, default=dict, help_text='Custom headers to include in webhook requests')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_webhooks', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Tenant this webhook belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='outbound_webhooks', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Outbound Webhook',
                'verbose_name_plural': 'Outbound Webhooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutboundWebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_name', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=100)),
                ('event_id', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('status_message', models.TextField(blank=True)),
                ('response_status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=5)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='integrations.outboundwebhook')),
            ],
            options={
                'verbose_name': 'Outbound Webhook Delivery',
                'verbose_name_plural': 'Outbound Webhook Deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='outboundwebhook',
            index=models.Index(fields=['tenant', 'status'], name='integration_tenant__85e2cf_idx'),
        ),
        migrations.AddIndex(
            model_name='outboundwebhook',
            index=models.Index(fields=['tenant', 'is_enabled'], name='integration_tenant__98724b_idx'),
        ),
        migrations.AddIndex(
            model_name='outboundwebhookdelivery',
            index=models.Index(fields=['webhook', '-created_at'], name='integration_webhook_187e21_idx'),
        ),
        migrations.AddIndex(
            model_name='outboundwebhookdelivery',
            index=models.Index(fields=['status', 'next_retry_at'], name='integration_status_2df883_idx'),
        ),
    ]
