# Generated by Django 5.2.7 on 2026-01-18 07:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('product_type', models.CharField(choices=[('standard', 'Standard'), ('metered', 'Metered (Usage-Based)'), ('licensed', 'Licensed (Per-Seat)')], default='standard', max_length=20)),
                ('base_price_monthly', models.DecimalField(decimal_places=2, help_text='Base monthly price', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('base_price_yearly', models.DecimalField(decimal_places=2, help_text='Base yearly price', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('trial_period_days', models.PositiveIntegerField(default=0, help_text='Number of days for trial period (0 = no trial)')),
                ('features', models.JSONField(default=list, help_text='List of features included in this product')),
                ('max_users', models.PositiveIntegerField(blank=True, help_text='Maximum users allowed (null = unlimited)', null=True)),
                ('max_storage_gb', models.PositiveIntegerField(blank=True, help_text='Maximum storage in GB (null = unlimited)', null=True)),
                ('max_api_calls_per_month', models.PositiveIntegerField(blank=True, help_text='Maximum API calls per month (null = unlimited)', null=True)),
                ('stripe_product_id', models.CharField(blank=True, max_length=255)),
                ('stripe_price_id_monthly', models.CharField(blank=True, max_length=255)),
                ('stripe_price_id_yearly', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True, help_text='Whether product is shown on public pricing page')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Subscription Product',
                'verbose_name_plural': 'Subscription Products',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_quantity', models.PositiveIntegerField(help_text='Minimum quantity for this tier', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_quantity', models.PositiveIntegerField(blank=True, help_text='Maximum quantity for this tier (null = unlimited)', null=True)),
                ('price_per_unit_monthly', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('price_per_unit_yearly', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='subscriptions.subscriptionproduct')),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Subscription Tier',
                'verbose_name_plural': 'Subscription Tiers',
                'ordering': ['product', 'min_quantity'],
            },
        ),
        migrations.CreateModel(
            name='CustomerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid'), ('paused', 'Paused')], db_index=True, default='active', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of units (e.g., seats, licenses)', validators=[django.core.validators.MinValueValidator(1)])),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Price per unit at subscription time', max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total subscription price (quantity * price_per_unit)', max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('trial_start', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, unique=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_subscriptions', to='subscriptions.subscriptionproduct')),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_subscriptions', to='subscriptions.subscriptiontier')),
            ],
            options={
                'verbose_name': 'Customer Subscription',
                'verbose_name_plural': 'Customer Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_type', models.CharField(choices=[('api_calls', 'API Calls'), ('compute_hours', 'Compute Hours'), ('storage_gb', 'Storage (GB)'), ('bandwidth_gb', 'Bandwidth (GB)'), ('transactions', 'Transactions'), ('custom', 'Custom')], db_index=True, max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity of usage', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('unit_price', models.DecimalField(decimal_places=4, help_text='Price per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total cost (quantity * unit_price)', max_digits=12)),
                ('usage_date', models.DateField(db_index=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('stripe_usage_record_id', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='subscriptions.customersubscription')),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Usage Record',
                'verbose_name_plural': 'Usage Records',
                'ordering': ['-usage_date'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, help_text='Unique invoice number (auto-generated)', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('paid', 'Paid'), ('void', 'Void'), ('uncollectible', 'Uncollectible')], db_index=True, default='draft', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal before tax', max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax amount', max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, help_text='Total amount (subtotal + tax)', max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount_due', models.DecimalField(decimal_places=2, help_text='Amount still owed', max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('line_items', models.JSONField(default=list, help_text='Invoice line items (JSON)')),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=255, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('pdf_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('customer_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_invoices', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='subscriptions.customersubscription')),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Subscription Invoice',
                'verbose_name_plural': 'Subscription Invoices',
                'ordering': ['-invoice_date'],
                'indexes': [models.Index(fields=['invoice_number'], name='subscriptio_invoice_b19cba_idx'), models.Index(fields=['subscription', '-invoice_date'], name='subscriptio_subscri_749901_idx'), models.Index(fields=['customer', '-invoice_date'], name='subscriptio_custome_b3f5f6_idx'), models.Index(fields=['status', '-invoice_date'], name='subscriptio_status_0b4239_idx'), models.Index(fields=['due_date'], name='subscriptio_due_dat_241118_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='subscriptionproduct',
            index=models.Index(fields=['slug'], name='subscriptio_slug_b2ba38_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionproduct',
            index=models.Index(fields=['is_active', 'is_public'], name='subscriptio_is_acti_3e5b73_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionproduct',
            index=models.Index(fields=['sort_order'], name='subscriptio_sort_or_e7a6b0_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptiontier',
            index=models.Index(fields=['product', 'min_quantity'], name='subscriptio_product_687573_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptiontier',
            unique_together={('product', 'min_quantity')},
        ),
        migrations.AddIndex(
            model_name='customersubscription',
            index=models.Index(fields=['customer', 'status'], name='subscriptio_custome_08183b_idx'),
        ),
        migrations.AddIndex(
            model_name='customersubscription',
            index=models.Index(fields=['product', 'status'], name='subscriptio_product_5afe9a_idx'),
        ),
        migrations.AddIndex(
            model_name='customersubscription',
            index=models.Index(fields=['status', '-created_at'], name='subscriptio_status_a847bd_idx'),
        ),
        migrations.AddIndex(
            model_name='customersubscription',
            index=models.Index(fields=['stripe_subscription_id'], name='subscriptio_stripe__682bbf_idx'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['subscription', '-usage_date'], name='subscriptio_subscri_d6a142_idx'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['usage_type', '-usage_date'], name='subscriptio_usage_t_24d1f8_idx'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['-usage_date'], name='subscriptio_usage_d_52348b_idx'),
        ),
    ]
