# Generated by Django 5.2.7 on 2025-10-25 22:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='company',
        ),
        migrations.AddField(
            model_name='service',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date de création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(blank=True, help_text='Description facultative'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Catégorie parent, pour structure arborescente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='dashboard_service.servicecategory'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date de mise à jour'),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(help_text='Nom de la catégorie', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='dashboard_service.providerskill'),
        ),
        migrations.AlterField(
            model_name='servicestag',
            name='tag',
            field=models.CharField(help_text='Nom du tag (unique)', max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='ServiceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, help_text='Contenu du commentaire')),
                ('rating', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de mise à jour')),
                ('parent', models.ForeignKey(blank=True, help_text='Commentaire parent si ce commentaire est une réponse', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='dashboard_service.servicecomment')),
                ('provider', models.ForeignKey(help_text='Professionnel associé au commentaire', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dashboard_service.serviceproviderprofile')),
                ('reviewer', models.ForeignKey(help_text='Auteur du commentaire', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(help_text='Service associé au commentaire', on_delete=django.db.models.deletion.CASCADE, related_name='comments_service', to='dashboard_service.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ProviderReview',
        ),
    ]
