# Generated by Django 5.2.7 on 2025-11-03 18:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceproviderprofile',
            options={'verbose_name': 'Service Provider Profile', 'verbose_name_plural': 'Service Provider Profiles'},
        ),
        migrations.RenameField(
            model_name='serviceproviderprofile',
            old_name='completed_jobs',
            new_name='completed_jobs_count',
        ),
        migrations.RenameField(
            model_name='serviceproviderprofile',
            old_name='location_lon',
            new_name='location_lng',
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='address',
            field=models.CharField(blank=True, help_text='Address line 1 eg. 123 Main Street', max_length=255),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='is_mobile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='available', max_length=25),
        ),
    ]
