# Generated by Django 5.2.7 on 2025-10-25 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_service', '0002_remove_service_company_service_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='provider',
            field=models.ForeignKey(default=43423, on_delete=django.db.models.deletion.CASCADE, related_name='services_offered_by_provider', to='dashboard_service.serviceproviderprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='service_providers', to='dashboard_service.service'),
        ),
    ]
