# Generated by Django 5.2.7 on 2026-01-02 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('configurations', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmessage',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationmessage',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='applicationnote',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_applicationnote_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationnote',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='candidatedocument',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basic_candidate_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidatedocument',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='configurations.candidateprofile'),
        ),
        migrations.AddField(
            model_name='certification',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='configurations.candidateprofile'),
        ),
        migrations.AddField(
            model_name='certification',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='company',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='configurations.company'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='department',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='configurations.companyprofile'),
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='configurations.department'),
        ),
        migrations.AddField(
            model_name='department',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='education',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='configurations.candidateprofile'),
        ),
        migrations.AddField(
            model_name='education',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='employeerecord',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='employee_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='configurations.employeerecord'),
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='employee_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='configurations.employeerecord'),
        ),
        migrations.AddField(
            model_name='faqentry',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='internalnotification',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_notifications', to='configurations.company'),
        ),
        migrations.AddField(
            model_name='internalnotification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internalnotification',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='interview',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='interviewnote',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='configurations.interview'),
        ),
        migrations.AddField(
            model_name='interviewnote',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_listings', to='configurations.company'),
        ),
        migrations.AddField(
            model_name='job',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='configurations.candidateprofile'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='configurations.job'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='interview',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='configurations.jobapplication'),
        ),
        migrations.AddField(
            model_name='applicationnote',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='configurations.jobapplication'),
        ),
        migrations.AddField(
            model_name='applicationmessage',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='configurations.jobapplication'),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='configurations.companyprofile'),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='configurations.department'),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='job',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='configurations.jobposition'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='employee_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='configurations.employeerecord'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leave_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='membership',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='configurations.companyprofile'),
        ),
        migrations.AddField(
            model_name='membership',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='configurations.department'),
        ),
        migrations.AddField(
            model_name='membership',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membership',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='org_membership_permissions', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='interviewnote',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurations.membership'),
        ),
        migrations.AddField(
            model_name='interview',
            name='interviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_interviews', to='configurations.membership'),
        ),
        migrations.AddField(
            model_name='employeerecord',
            name='membership',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_record', to='configurations.membership'),
        ),
        migrations.AddField(
            model_name='onboardingchecklist',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onboardingchecklist',
            name='employee_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_items', to='configurations.employeerecord'),
        ),
        migrations.AddField(
            model_name='onboardingchecklist',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='partnership',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='role',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='configurations.companyprofile'),
        ),
        migrations.AddField(
            model_name='role',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='org_role_permissions', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='role',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='membership',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='configurations.role'),
        ),
        migrations.AddField(
            model_name='internalnotification',
            name='target_roles',
            field=models.ManyToManyField(blank=True, to='configurations.role'),
        ),
        migrations.AddField(
            model_name='site',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='configurations.company'),
        ),
        migrations.AddField(
            model_name='site',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='configurations.site'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='configurations.site'),
        ),
        migrations.AddField(
            model_name='skill',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='basic_candidates', to='configurations.skill'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_timesheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='employee_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='configurations.employeerecord'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='trustedcompany',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='configurations.candidateprofile'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='configurations_department_unique_company_name'),
        ),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.UniqueConstraint(fields=('candidate', 'job'), name='configurations_application_unique_candidate_job'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='configurations_role_unique_company_name'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'company'), name='configurations_membership_unique_user_company'),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='configurations_site_unique_company_name'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='configurations_skill_unique_tenant_slug'),
        ),
        migrations.AddConstraint(
            model_name='timesheet',
            constraint=models.UniqueConstraint(fields=('employee_record', 'week_start'), name='configurations_timesheet_unique_employee_week'),
        ),
    ]
