# Generated by Django 5.2.7 on 2026-01-18 07:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_id', models.CharField(db_index=True, help_text='Unique payout identifier (auto-generated)', max_length=255, unique=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text='Amount before platform fee', max_digits=12)),
                ('platform_fee', models.DecimalField(decimal_places=2, help_text='Platform fee deducted', max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Amount paid to provider (gross - fee)', max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=20)),
                ('stripe_transfer_id', models.CharField(blank=True, max_length=255)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Escrow Payout',
                'verbose_name_plural': 'Escrow Payouts',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='EscrowRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_type', models.CharField(choices=[('full', 'Full Release'), ('partial', 'Partial Release'), ('refund', 'Refund to Client')], default='full', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount being released', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('approval_reason', models.TextField(blank=True)),
                ('is_automatic', models.BooleanField(default=False, help_text='Whether this was an auto-release or manual')),
                ('released_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Escrow Release',
                'verbose_name_plural': 'Escrow Releases',
                'ordering': ['-released_at'],
            },
        ),
        migrations.CreateModel(
            name='EscrowTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escrow_id', models.CharField(db_index=True, help_text='Unique escrow identifier (auto-generated)', max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Escrow amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('platform_fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Platform fee percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MinValueValidator(Decimal('100.00'))])),
                ('platform_fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated platform fee amount', max_digits=12)),
                ('payout_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount to be paid out to provider (amount - platform_fee)', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('funded', 'Funded'), ('released', 'Released'), ('refunded', 'Refunded'), ('disputed', 'Disputed'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('auto_release_days', models.PositiveIntegerField(default=7, help_text='Days after work completion before auto-release (0 = manual only)')),
                ('work_completed_at', models.DateTimeField(blank=True, help_text='When provider marked work as complete', null=True)),
                ('auto_release_at', models.DateTimeField(blank=True, help_text='Calculated auto-release datetime', null=True)),
                ('funded_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Escrow Transaction',
                'verbose_name_plural': 'Escrow Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MilestonePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_number', models.PositiveIntegerField(help_text='Milestone sequence number (1, 2, 3, ...)')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('funded', 'Funded'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('approved', 'Approved'), ('paid', 'Paid'), ('disputed', 'Disputed')], db_index=True, default='pending', max_length=20)),
                ('deliverables', models.JSONField(default=list, help_text='List of expected deliverables for this milestone')),
                ('delivered_files', models.JSONField(default=list, help_text='List of delivered files/URLs')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Milestone Payment',
                'verbose_name_plural': 'Milestone Payments',
                'ordering': ['milestone_number'],
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispute_id', models.CharField(db_index=True, help_text='Unique dispute identifier (auto-generated)', max_length=255, unique=True)),
                ('reason', models.TextField(help_text='Reason for dispute')),
                ('evidence', models.JSONField(default=list, help_text='Evidence submitted (file URLs, descriptions)')),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('resolution', models.CharField(blank=True, choices=[('release_to_provider', 'Release to Provider'), ('refund_to_client', 'Refund to Client'), ('partial_release', 'Partial Release'), ('no_action', 'No Action')], max_length=30, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('provider_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount released to provider (if partial)', max_digits=12, null=True)),
                ('client_refund_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount refunded to client (if partial)', max_digits=12, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes_initiated', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_resolved', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Dispute',
                'verbose_name_plural': 'Disputes',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='EscrowAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('funded', 'Funded'), ('work_completed', 'Work Completed'), ('approved', 'Approved'), ('released', 'Released'), ('refunded', 'Refunded'), ('disputed', 'Disputed'), ('dispute_resolved', 'Dispute Resolved'), ('canceled', 'Canceled')], db_index=True, max_length=30)),
                ('description', models.TextField()),
                ('previous_state', models.JSONField(blank=True, default=dict, help_text='State before action')),
                ('new_state', models.JSONField(blank=True, default=dict, help_text='State after action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed this action (null = system)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Escrow Audit Log',
                'verbose_name_plural': 'Escrow Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
