# Generated by Django 5.2.7 on 2026-01-18 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('escrow', '0001_initial'),
        ('payments', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowpayout',
            name='payment_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escrow_payouts', to='payments.paymenttransaction'),
        ),
        migrations.AddField(
            model_name='escrowpayout',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escrow_payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escrowpayout',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='escrowrelease',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escrow_releases_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escrowrelease',
            name='payout_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escrow_releases', to='payments.paymenttransaction'),
        ),
        migrations.AddField(
            model_name='escrowrelease',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='client',
            field=models.ForeignKey(help_text='Client funding the escrow', on_delete=django.db.models.deletion.PROTECT, related_name='escrow_as_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='payment_transaction',
            field=models.ForeignKey(blank=True, help_text='Payment transaction that funded this escrow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escrow_transactions', to='payments.paymenttransaction'),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='provider',
            field=models.ForeignKey(help_text='Provider receiving funds upon release', on_delete=django.db.models.deletion.PROTECT, related_name='escrow_as_provider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='escrowrelease',
            name='escrow_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='escrow.escrowtransaction'),
        ),
        migrations.AddField(
            model_name='escrowpayout',
            name='escrow_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='escrow.escrowtransaction'),
        ),
        migrations.AddField(
            model_name='escrowaudit',
            name='escrow_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='escrow.escrowtransaction'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='escrow_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='escrow.escrowtransaction'),
        ),
        migrations.AddField(
            model_name='milestonepayment',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='milestonepayment',
            name='escrow_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestone', to='escrow.escrowtransaction'),
        ),
        migrations.AddField(
            model_name='milestonepayment',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='escrowtransaction',
            index=models.Index(fields=['escrow_id'], name='escrow_escr_escrow__2bf956_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowtransaction',
            index=models.Index(fields=['status', '-created_at'], name='escrow_escr_status_dcb63e_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowtransaction',
            index=models.Index(fields=['client', '-created_at'], name='escrow_escr_client__d25dad_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowtransaction',
            index=models.Index(fields=['provider', '-created_at'], name='escrow_escr_provide_51d30d_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowtransaction',
            index=models.Index(fields=['content_type', 'object_id'], name='escrow_escr_content_081132_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowrelease',
            index=models.Index(fields=['escrow_transaction', '-released_at'], name='escrow_escr_escrow__4aa86e_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowpayout',
            index=models.Index(fields=['payout_id'], name='escrow_escr_payout__ccba37_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowpayout',
            index=models.Index(fields=['provider', '-initiated_at'], name='escrow_escr_provide_9f3aef_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowpayout',
            index=models.Index(fields=['status', '-initiated_at'], name='escrow_escr_status_f04870_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowaudit',
            index=models.Index(fields=['escrow_transaction', '-created_at'], name='escrow_escr_escrow__167e5a_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowaudit',
            index=models.Index(fields=['action', '-created_at'], name='escrow_escr_action_53e46b_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['dispute_id'], name='escrow_disp_dispute_c76f68_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['escrow_transaction', 'status'], name='escrow_disp_escrow__cd7ebf_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['status', '-opened_at'], name='escrow_disp_status_cb7ba3_idx'),
        ),
        migrations.AddIndex(
            model_name='milestonepayment',
            index=models.Index(fields=['status', '-created_at'], name='escrow_mile_status_9e0d18_idx'),
        ),
        migrations.AddIndex(
            model_name='milestonepayment',
            index=models.Index(fields=['content_type', 'object_id'], name='escrow_mile_content_3e15fb_idx'),
        ),
    ]
