# Generated by Django 5.2.7 on 2026-01-18 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_id', models.CharField(db_index=True, editable=False, help_text='Auto-generated webhook ID', max_length=100, unique=True)),
                ('source', models.CharField(choices=[('stripe', 'Stripe'), ('avalara', 'Avalara'), ('quickbooks', 'QuickBooks'), ('xero', 'Xero')], db_index=True, help_text='Webhook source provider', max_length=20)),
                ('event_type', models.CharField(db_index=True, help_text='Event type (e.g., payment_intent.succeeded)', max_length=100)),
                ('event_id', models.CharField(db_index=True, help_text='External event ID from provider', max_length=255)),
                ('payload', models.JSONField(help_text='Full webhook payload')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('ignored', 'Ignored')], db_index=True, default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the webhook was processed', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of related object', null=True)),
                ('signature_verified', models.BooleanField(default=False, help_text='Whether webhook signature was verified')),
                ('signature', models.TextField(blank=True, help_text='Webhook signature from provider')),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of processing retries')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When webhook was received')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='Type of related object', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Webhook Event',
                'verbose_name_plural': 'Webhook Events',
                'db_table': 'finance_webhooks_event',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('stripe', 'Stripe'), ('avalara', 'Avalara'), ('quickbooks', 'QuickBooks'), ('xero', 'Xero')], help_text='Webhook source provider', max_length=20)),
                ('event_type', models.CharField(help_text='Event type identifier', max_length=100)),
                ('handler_path', models.CharField(help_text='Python path to handler function (e.g., finance_webhooks.handlers.stripe.payment_succeeded)', max_length=255)),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this event type is enabled')),
                ('auto_retry', models.BooleanField(default=True, help_text='Whether to automatically retry failed events')),
                ('max_retries', models.PositiveIntegerField(default=5, help_text='Maximum retry attempts')),
                ('description', models.TextField(blank=True, help_text='Event type description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Webhook Event Type',
                'verbose_name_plural': 'Webhook Event Types',
                'db_table': 'finance_webhooks_event_type',
                'ordering': ['source', 'event_type'],
                'unique_together': {('source', 'event_type')},
            },
        ),
        migrations.CreateModel(
            name='WebhookRetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retry_number', models.PositiveIntegerField(help_text='Retry attempt number')),
                ('retry_at', models.DateTimeField(auto_now_add=True, help_text='When retry was attempted')),
                ('succeeded', models.BooleanField(default=False, help_text='Whether retry succeeded')),
                ('error_message', models.TextField(blank=True, help_text='Error message if retry failed')),
                ('next_retry_at', models.DateTimeField(blank=True, help_text='When next retry is scheduled', null=True)),
                ('webhook_event', models.ForeignKey(help_text='Related webhook event', on_delete=django.db.models.deletion.CASCADE, related_name='retries', to='finance_webhooks.webhookevent')),
            ],
            options={
                'verbose_name': 'Webhook Retry',
                'verbose_name_plural': 'Webhook Retries',
                'db_table': 'finance_webhooks_retry',
                'ordering': ['-retry_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(help_text='Whether signature was valid')),
                ('signature', models.TextField(help_text='Webhook signature')),
                ('expected_signature', models.TextField(blank=True, help_text='Expected signature (computed)')),
                ('algorithm', models.CharField(help_text='Signature algorithm (e.g., HMAC-SHA256)', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Verification timestamp')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Request IP address', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Request User-Agent header')),
                ('webhook_event', models.ForeignKey(help_text='Related webhook event', on_delete=django.db.models.deletion.CASCADE, related_name='signature_logs', to='finance_webhooks.webhookevent')),
            ],
            options={
                'verbose_name': 'Webhook Signature',
                'verbose_name_plural': 'Webhook Signatures',
                'db_table': 'finance_webhooks_signature',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['source', 'event_type'], name='finance_web_source_d8f9ac_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['source', 'status'], name='finance_web_source_d51b7c_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['event_id', 'source'], name='finance_web_event_i_34e732_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['received_at', 'status'], name='finance_web_receive_ce1c87_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookretry',
            index=models.Index(fields=['webhook_event', 'retry_number'], name='finance_web_webhook_04e236_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookretry',
            index=models.Index(fields=['next_retry_at'], name='finance_web_next_re_9a9ab1_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooksignature',
            index=models.Index(fields=['webhook_event', 'verified'], name='finance_web_webhook_a20dd9_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooksignature',
            index=models.Index(fields=['verified', 'timestamp'], name='finance_web_verifie_fbba7a_idx'),
        ),
    ]
