# Generated by Django 5.2.7 on 2026-01-18 07:40

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('quickbooks', 'QuickBooks Online'), ('xero', 'Xero'), ('manual', 'Manual Entry')], db_index=True, max_length=20)),
                ('access_token', models.CharField(blank=True, help_text='OAuth access token (should be encrypted)', max_length=500)),
                ('refresh_token', models.CharField(blank=True, help_text='OAuth refresh token (should be encrypted)', max_length=500)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('realm_id', models.CharField(blank=True, help_text='QuickBooks Company ID', max_length=255)),
                ('xero_tenant_id', models.CharField(blank=True, help_text='Xero Tenant ID', max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('base_currency', models.CharField(default='USD', max_length=3)),
                ('auto_sync', models.BooleanField(default=False, help_text='Automatically sync transactions')),
                ('sync_frequency', models.CharField(choices=[('realtime', 'Real-time'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('manual', 'Manual Only')], default='daily', max_length=20)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error'), ('syncing', 'Syncing')], db_index=True, default='disconnected', max_length=20)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Accounting Provider',
                'verbose_name_plural': 'Accounting Providers',
            },
        ),
        migrations.CreateModel(
            name='AccountingSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.CharField(db_index=True, help_text='Unique sync identifier (auto-generated)', max_length=50, unique=True)),
                ('sync_type', models.CharField(choices=[('full', 'Full Sync'), ('incremental', 'Incremental Sync'), ('manual', 'Manual Sync')], max_length=20)),
                ('status', models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partially Completed')], db_index=True, default='started', max_length=20)),
                ('records_processed', models.PositiveIntegerField(default=0)),
                ('records_synced', models.PositiveIntegerField(default=0)),
                ('records_failed', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Accounting Sync Log',
                'verbose_name_plural': 'Accounting Sync Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense'), ('cost_of_goods_sold', 'Cost of Goods Sold')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('provider_account_id', models.CharField(help_text='Account ID in QuickBooks/Xero', max_length=255)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current account balance', max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chart of Accounts',
                'verbose_name_plural': 'Chart of Accounts',
                'ordering': ['account_type', 'account_number', 'account_name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(db_index=True, help_text='Unique report number (auto-generated)', max_length=50, unique=True)),
                ('report_type', models.CharField(choices=[('profit_loss', 'Profit & Loss (Income Statement)'), ('balance_sheet', 'Balance Sheet'), ('cash_flow', 'Cash Flow Statement'), ('trial_balance', 'Trial Balance'), ('ar_aging', 'Accounts Receivable Aging'), ('ap_aging', 'Accounts Payable Aging')], max_length=20)),
                ('report_name', models.CharField(max_length=255)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('report_data', models.JSONField(default=dict, help_text='Full report data (JSON)')),
                ('source', models.CharField(choices=[('system', 'System Generated'), ('quickbooks', 'QuickBooks'), ('xero', 'Xero')], default='system', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='financial_reports/%Y/%m/')),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Financial Report',
                'verbose_name_plural': 'Financial Reports',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(db_index=True, help_text='Unique journal entry number (auto-generated)', max_length=50, unique=True)),
                ('entry_date', models.DateField(db_index=True)),
                ('description', models.TextField()),
                ('reference', models.CharField(blank=True, help_text='Reference number or document', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('void', 'Void')], db_index=True, default='draft', max_length=20)),
                ('provider_entry_id', models.CharField(blank=True, help_text='Journal entry ID in QuickBooks/Xero', max_length=255)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-entry_date', '-entry_number'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('description', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Journal Entry Line',
                'verbose_name_plural': 'Journal Entry Lines',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconciliation_id', models.CharField(db_index=True, help_text='Unique reconciliation identifier (auto-generated)', max_length=50, unique=True)),
                ('statement_date', models.DateField()),
                ('statement_ending_balance', models.DecimalField(decimal_places=2, help_text='Ending balance per bank statement', max_digits=15)),
                ('opening_balance', models.DecimalField(decimal_places=2, help_text='Opening balance', max_digits=15)),
                ('cleared_debits', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total cleared debits', max_digits=15)),
                ('cleared_credits', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total cleared credits', max_digits=15)),
                ('calculated_balance', models.DecimalField(decimal_places=2, help_text='Calculated ending balance', max_digits=15)),
                ('difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Difference between statement and calculated balance', max_digits=15)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], db_index=True, default='in_progress', max_length=20)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reconciliation Record',
                'verbose_name_plural': 'Reconciliation Records',
                'ordering': ['-statement_date'],
            },
        ),
    ]
