# Generated by Django 5.2.7 on 2026-01-18 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0003_initial'),
        ('payments', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='payment_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='payments.paymenttransaction'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='accounting.accountingprovider'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='reconciliationrecord',
            name='account',
            field=models.ForeignKey(help_text='Bank or cash account being reconciled', on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='accounting.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='reconciliationrecord',
            name='reconciled_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations_done', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reconciliationrecord',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='accountingsynclog',
            index=models.Index(fields=['sync_id'], name='accounting__sync_id_db7c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingsynclog',
            index=models.Index(fields=['provider', 'status'], name='accounting__provide_16ee42_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingsynclog',
            index=models.Index(fields=['-started_at'], name='accounting__started_09ca6b_idx'),
        ),
        migrations.AddIndex(
            model_name='chartofaccounts',
            index=models.Index(fields=['provider', 'account_type'], name='accounting__provide_633b73_idx'),
        ),
        migrations.AddIndex(
            model_name='chartofaccounts',
            index=models.Index(fields=['provider_account_id'], name='accounting__provide_b038db_idx'),
        ),
        migrations.AddIndex(
            model_name='financialreport',
            index=models.Index(fields=['report_number'], name='accounting__report__76ae42_idx'),
        ),
        migrations.AddIndex(
            model_name='financialreport',
            index=models.Index(fields=['report_type', '-period_end'], name='accounting__report__3559ec_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['entry_number'], name='accounting__entry_n_734b5b_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['status', '-entry_date'], name='accounting__status_edfa8d_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['provider_entry_id'], name='accounting__provide_ff1c5f_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationrecord',
            index=models.Index(fields=['reconciliation_id'], name='accounting__reconci_9e845a_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationrecord',
            index=models.Index(fields=['account', 'status'], name='accounting__account_68bfc2_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationrecord',
            index=models.Index(fields=['-statement_date'], name='accounting__stateme_8b0900_idx'),
        ),
    ]
