# Generated by Django 5.2.7 on 2026-01-18 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant_profiles', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatecv',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coopterm',
            name='employer_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coop_terms', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='dataaccesslog',
            name='accessor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_access_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataaccesslog',
            name='accessor_tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='dataaccesslog',
            name='data_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_accessed_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='educationverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employmentverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_verifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
