# Generated by Django 5.2.7 on 2026-01-18 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant_profiles', '0002_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('configurations', '0002_initial'),
        ('services', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Service categories this freelancer works in', related_name='freelancers', to='services.servicecategory'),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='service_provider',
            field=models.ForeignKey(blank=True, help_text='Link to ServiceProvider profile if offering services', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freelancer_profiles', to='services.serviceprovider'),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_verifications_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='progressiveconsent',
            name='grantee_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consents_received', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='progressiveconsent',
            name='grantee_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consents_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='progressiveconsent',
            name='grantor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataaccesslog',
            name='consent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant_profiles.progressiveconsent'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityquestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coopterm',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coop_terms', to='tenant_profiles.studentprofile'),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='configurations.department'),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='custom_permissions',
            field=models.ManyToManyField(blank=True, related_name='tenant_users', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_users', to='configurations.department'),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='reports_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='tenant_profiles.tenantuser'),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='reports_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinate_profiles', to='tenant_profiles.tenantuser'),
        ),
        migrations.AddField(
            model_name='trustscore',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_score', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='candidatecv',
            index=models.Index(fields=['user', 'is_primary'], name='tenant_profiles_ca_user_id_8bc1a0_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatecv',
            index=models.Index(fields=['user', 'status'], name='tenant_profiles_ca_user_id_475450_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='candidatecv',
            unique_together={('user', 'slug')},
        ),
        migrations.AddIndex(
            model_name='educationverification',
            index=models.Index(fields=['user', 'status'], name='tenant_profiles_ed_user_id_388b55_idx'),
        ),
        migrations.AddIndex(
            model_name='educationverification',
            index=models.Index(fields=['verification_token'], name='tenant_profiles_ed_verific_c27e9d_idx'),
        ),
        migrations.AddIndex(
            model_name='educationverification',
            index=models.Index(fields=['status', 'created_at'], name='tenant_profiles_ed_status_7dc7b4_idx'),
        ),
        migrations.AddIndex(
            model_name='employmentverification',
            index=models.Index(fields=['user', 'status'], name='tenant_profiles_em_user_id_f26402_idx'),
        ),
        migrations.AddIndex(
            model_name='employmentverification',
            index=models.Index(fields=['verification_token'], name='tenant_profiles_em_verific_69a171_idx'),
        ),
        migrations.AddIndex(
            model_name='employmentverification',
            index=models.Index(fields=['status', 'created_at'], name='tenant_profiles_em_status_ca84d0_idx'),
        ),
        migrations.AddIndex(
            model_name='freelancerprofile',
            index=models.Index(fields=['availability_status'], name='tenant_profiles_fr_availab_354e7e_idx'),
        ),
        migrations.AddIndex(
            model_name='freelancerprofile',
            index=models.Index(fields=['is_verified'], name='tenant_profiles_fr_is_veri_75c103_idx'),
        ),
        migrations.AddIndex(
            model_name='freelancerprofile',
            index=models.Index(fields=['average_rating', 'total_reviews'], name='tenant_profiles_fr_average_6ae189_idx'),
        ),
        migrations.AddIndex(
            model_name='freelancerprofile',
            index=models.Index(fields=['created_at'], name='tenant_profiles_fr_created_776e25_idx'),
        ),
        migrations.AddIndex(
            model_name='kycverification',
            index=models.Index(fields=['user', 'verification_type'], name='tenant_profiles_ky_user_id_39f92a_idx'),
        ),
        migrations.AddIndex(
            model_name='kycverification',
            index=models.Index(fields=['status', 'created_at'], name='tenant_profiles_ky_status_60cf02_idx'),
        ),
        migrations.AddIndex(
            model_name='kycverification',
            index=models.Index(fields=['user', 'status'], name='tenant_profiles_ky_user_id_f149d0_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['user', 'timestamp'], name='tenant_profiles_lo_user_id_85d75c_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['ip_address', 'timestamp'], name='tenant_profiles_lo_ip_addr_bcaa8b_idx'),
        ),
        migrations.AddIndex(
            model_name='progressiveconsent',
            index=models.Index(fields=['grantor', 'status'], name='tenant_profiles_pr_grantor_d2b597_idx'),
        ),
        migrations.AddIndex(
            model_name='progressiveconsent',
            index=models.Index(fields=['grantee_user', 'status'], name='tenant_profiles_pr_grantee_81e795_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='progressiveconsent',
            unique_together={('grantor', 'grantee_user', 'grantee_tenant', 'data_category', 'context_type', 'context_id')},
        ),
        migrations.AddIndex(
            model_name='dataaccesslog',
            index=models.Index(fields=['data_subject', 'accessed_at'], name='tenant_profiles_da_data_su_289b4c_idx'),
        ),
        migrations.AddIndex(
            model_name='dataaccesslog',
            index=models.Index(fields=['accessor', 'accessed_at'], name='tenant_profiles_da_accesso_404a3e_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewee', 'status', '-created_at'], name='tenant_profiles_re_reviewe_b666be_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewer', '-created_at'], name='tenant_profiles_re_reviewe_aa662c_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['overall_rating', 'status'], name='tenant_profiles_re_overall_8dcb26_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_negative', 'status'], name='tenant_profiles_re_is_nega_56f32b_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('reviewer', 'reviewee', 'context_type', 'context_id'), name='tenant_profiles_review_unique_per_context'),
        ),
        migrations.AddIndex(
            model_name='securityquestion',
            index=models.Index(fields=['user', 'created_at'], name='tenant_profiles_se_user_id_fc0700_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['enrollment_status'], name='tenant_profiles_st_enrollm_eb8800_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['enrollment_verified'], name='tenant_profiles_st_enrollm_899e7e_idx'),
        ),
        migrations.AddIndex(
            model_name='coopterm',
            index=models.Index(fields=['student', 'status'], name='tenant_profiles_co_student_8f0b12_idx'),
        ),
        migrations.AddIndex(
            model_name='coopterm',
            index=models.Index(fields=['status', 'start_date'], name='tenant_profiles_co_status_3cde09_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coopterm',
            unique_together={('student', 'term_number')},
        ),
        migrations.AlterUniqueTogether(
            name='tenantuser',
            unique_together={('user', 'tenant')},
        ),
        migrations.AddIndex(
            model_name='tenantprofile',
            index=models.Index(fields=['user', 'tenant'], name='tenant_profiles_te_user_id_24a5a3_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantprofile',
            index=models.Index(fields=['tenant', 'job_title'], name='tenant_profiles_te_tenant__dff779_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantprofile',
            index=models.Index(fields=['department'], name='tenant_profiles_te_departm_2153ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantprofile',
            unique_together={('user', 'tenant')},
        ),
        migrations.AddIndex(
            model_name='trustscore',
            index=models.Index(fields=['trust_level', 'overall_score'], name='tenant_profiles_tr_trust_l_005fb4_idx'),
        ),
        migrations.AddIndex(
            model_name='trustscore',
            index=models.Index(fields=['entity_type', 'trust_level'], name='tenant_profiles_tr_entity__1c5d75_idx'),
        ),
        migrations.AddIndex(
            model_name='trustscore',
            index=models.Index(fields=['is_id_verified', 'is_career_verified'], name='tenant_profiles_tr_is_id_v_dd9b6e_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='tenant_profiles_us_user_id_806298_idx'),
        ),
    ]
