# Generated by Django 5.2.7 on 2026-01-10 18:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('channel_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('in_app', 'In-App Notification'), ('slack', 'Slack'), ('webhook', 'Webhook')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Channel-specific configuration')),
                ('rate_limit_per_hour', models.PositiveIntegerField(default=100, help_text='Maximum notifications per hour for this channel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Channel',
                'verbose_name_plural': 'Notification Channels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_enabled', models.BooleanField(default=True, help_text='Master switch for all notifications')),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('channel_preferences', models.JSONField(default=dict, help_text='Per-channel enable/disable settings')),
                ('type_preferences', models.JSONField(default=dict, help_text='Per-type and per-channel preferences')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('slack_user_id', models.CharField(blank=True, max_length=50)),
                ('fcm_token', models.TextField(blank=True, help_text='Firebase Cloud Messaging token')),
                ('apns_token', models.TextField(blank=True, help_text='Apple Push Notification token')),
                ('email_digest_frequency', models.CharField(choices=[('realtime', 'Real-time'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('never', 'Never')], default='realtime', max_length=20)),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('global_unsubscribe', models.BooleanField(default=False)),
                ('unsubscribed_types', models.JSONField(default=list, help_text='List of notification types user has unsubscribed from')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('template_type', models.CharField(choices=[('application_received', 'Application Received'), ('application_reviewed', 'Application Reviewed'), ('interview_scheduled', 'Interview Scheduled'), ('interview_reminder', 'Interview Reminder'), ('interview_cancelled', 'Interview Cancelled'), ('offer_sent', 'Offer Sent'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('onboarding_task_due', 'Onboarding Task Due'), ('onboarding_complete', 'Onboarding Complete'), ('time_off_requested', 'Time Off Requested'), ('time_off_approved', 'Time Off Approved'), ('time_off_denied', 'Time Off Denied'), ('timesheet_reminder', 'Timesheet Reminder'), ('timesheet_approved', 'Timesheet Approved'), ('proposal_received', 'Proposal Received'), ('proposal_accepted', 'Proposal Accepted'), ('proposal_rejected', 'Proposal Rejected'), ('contract_created', 'Contract Created'), ('contract_signed', 'Contract Signed'), ('contract_completed', 'Contract Completed'), ('contract_cancelled', 'Contract Cancelled'), ('payment_received', 'Payment Received'), ('payment_sent', 'Payment Sent'), ('payment_failed', 'Payment Failed'), ('invoice_generated', 'Invoice Generated'), ('escrow_funded', 'Escrow Funded'), ('escrow_released', 'Escrow Released'), ('refund_processed', 'Refund Processed'), ('review_received', 'Review Received'), ('review_response', 'Review Response'), ('new_message', 'New Message'), ('message_reply', 'Message Reply'), ('appointment_booked', 'Appointment Booked'), ('appointment_reminder', 'Appointment Reminder'), ('appointment_cancelled', 'Appointment Cancelled'), ('appointment_rescheduled', 'Appointment Rescheduled'), ('account_created', 'Account Created'), ('password_changed', 'Password Changed'), ('login_alert', 'Login Alert'), ('two_factor_enabled', 'Two Factor Enabled'), ('account_suspended', 'Account Suspended'), ('account_reactivated', 'Account Reactivated'), ('system_maintenance', 'System Maintenance'), ('feature_announcement', 'Feature Announcement'), ('policy_update', 'Policy Update'), ('welcome_email', 'Welcome Email'), ('weekly_digest', 'Weekly Digest'), ('daily_digest', 'Daily Digest'), ('promotional', 'Promotional'), ('event_invitation', 'Event Invitation'), ('custom', 'Custom')], max_length=50)),
                ('subject', models.CharField(blank=True, help_text='Subject line (for email/push). Supports Django template syntax.', max_length=255)),
                ('body', models.TextField(help_text='Notification body. Supports Django template syntax.')),
                ('html_body', models.TextField(blank=True, help_text='HTML version of the body (for email). Supports Django template syntax.')),
                ('language', models.CharField(default='en', help_text="Language code (e.g., 'en', 'fr', 'es')", max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('default_context', models.JSONField(blank=True, default=dict, help_text='Default context variables for template rendering')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='notifications.notificationchannel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'ordering': ['template_type', 'channel', 'language'],
                'unique_together': {('template_type', 'channel', 'language')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('notification_type', models.CharField(choices=[('application_received', 'Application Received'), ('application_reviewed', 'Application Reviewed'), ('interview_scheduled', 'Interview Scheduled'), ('interview_reminder', 'Interview Reminder'), ('interview_cancelled', 'Interview Cancelled'), ('offer_sent', 'Offer Sent'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('onboarding_task_due', 'Onboarding Task Due'), ('onboarding_complete', 'Onboarding Complete'), ('time_off_requested', 'Time Off Requested'), ('time_off_approved', 'Time Off Approved'), ('time_off_denied', 'Time Off Denied'), ('timesheet_reminder', 'Timesheet Reminder'), ('timesheet_approved', 'Timesheet Approved'), ('proposal_received', 'Proposal Received'), ('proposal_accepted', 'Proposal Accepted'), ('proposal_rejected', 'Proposal Rejected'), ('contract_created', 'Contract Created'), ('contract_signed', 'Contract Signed'), ('contract_completed', 'Contract Completed'), ('contract_cancelled', 'Contract Cancelled'), ('payment_received', 'Payment Received'), ('payment_sent', 'Payment Sent'), ('payment_failed', 'Payment Failed'), ('invoice_generated', 'Invoice Generated'), ('escrow_funded', 'Escrow Funded'), ('escrow_released', 'Escrow Released'), ('refund_processed', 'Refund Processed'), ('review_received', 'Review Received'), ('review_response', 'Review Response'), ('new_message', 'New Message'), ('message_reply', 'Message Reply'), ('appointment_booked', 'Appointment Booked'), ('appointment_reminder', 'Appointment Reminder'), ('appointment_cancelled', 'Appointment Cancelled'), ('appointment_rescheduled', 'Appointment Rescheduled'), ('account_created', 'Account Created'), ('password_changed', 'Password Changed'), ('login_alert', 'Login Alert'), ('two_factor_enabled', 'Two Factor Enabled'), ('account_suspended', 'Account Suspended'), ('account_reactivated', 'Account Reactivated'), ('system_maintenance', 'System Maintenance'), ('feature_announcement', 'Feature Announcement'), ('policy_update', 'Policy Update'), ('welcome_email', 'Welcome Email'), ('weekly_digest', 'Weekly Digest'), ('daily_digest', 'Daily Digest'), ('promotional', 'Promotional'), ('event_invitation', 'Event Invitation'), ('custom', 'Custom')], db_index=True, default='custom', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('html_message', models.TextField(blank=True)),
                ('action_url', models.URLField(blank=True, max_length=500)),
                ('action_text', models.CharField(blank=True, default='View', max_length=100)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('external_id', models.CharField(blank=True, help_text='ID from external service (e.g., Twilio SID, SendGrid ID)', max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, help_text='User who triggered this notification (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notifications.notificationchannel')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.notificationtemplate')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('recipient_filter', models.JSONField(blank=True, default=dict, help_text='Filter criteria for selecting recipients (for broadcasts)')),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('recurrence', models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='once', max_length=20)),
                ('recurrence_end_date', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scheduled_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(blank=True, help_text='Specific user recipient (leave blank for broadcast)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_notifications', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_notifications', to='notifications.notificationtemplate')),
            ],
            options={
                'verbose_name': 'Scheduled Notification',
                'verbose_name_plural': 'Scheduled Notifications',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(max_length=20)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('error_type', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('error_traceback', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='notifications.notification')),
            ],
            options={
                'verbose_name': 'Notification Delivery Log',
                'verbose_name_plural': 'Notification Delivery Logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['notification', 'attempt_number'], name='notificatio_notific_a3828d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'status'], name='notificatio_recipie_e285de_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['channel', 'status'], name='notificatio_channel_dff6f6_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'created_at'], name='notificatio_notific_f2e0f7_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['batch_id'], name='notificatio_batch_i_f9a553_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulednotification',
            index=models.Index(fields=['scheduled_at', 'is_active', 'is_processed'], name='notificatio_schedul_35b21d_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulednotification',
            index=models.Index(fields=['next_run_at', 'is_active'], name='notificatio_next_ru_8b2fe9_idx'),
        ),
    ]
