# Generated by Django 5.2.6 on 2025-10-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_account_u', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='anonymous_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
