# Generated by Django 5.2.7 on 2026-01-11 06:34

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_account_u', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('display_name', models.CharField(help_text='Public display name for marketplace', max_length=100)),
                ('professional_title', models.CharField(blank=True, help_text='Professional title or headline', max_length=150)),
                ('avatar', models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='public_avatars/')),
                ('bio', models.TextField(blank=True, help_text='Professional bio or summary', max_length=2000)),
                ('public_email', models.EmailField(blank=True, help_text='Public contact email (can be different from login email)', max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128, null=True, region=None)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, default='CA', max_length=100)),
                ('timezone', models.CharField(default='America/Toronto', max_length=50)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('github_url', models.URLField(blank=True, help_text='GitHub profile URL')),
                ('portfolio_url', models.URLField(blank=True, help_text='Portfolio website URL')),
                ('personal_website', models.URLField(blank=True, help_text='Personal website URL')),
                ('cv_file', models.FileField(blank=True, help_text='Latest CV/resume file', null=True, upload_to='cvs/')),
                ('cv_last_updated', models.DateTimeField(blank=True, help_text='When CV was last updated', null=True)),
                ('skills', models.JSONField(blank=True, default=list, help_text='List of skills as JSON array')),
                ('languages', models.JSONField(blank=True, default=list, help_text='List of languages as JSON array')),
                ('certifications', models.JSONField(blank=True, default=list, help_text='List of certifications as JSON array')),
                ('available_for_work', models.BooleanField(default=False, help_text='Available for freelance work')),
                ('hourly_rate_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum hourly rate', max_digits=10, null=True)),
                ('hourly_rate_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum hourly rate', max_digits=10, null=True)),
                ('currency', models.CharField(default='CAD', max_length=3)),
                ('profile_visibility', models.CharField(choices=[('public', 'Public - Anyone can view'), ('tenants_only', 'Tenants Only - Only orgs I joined'), ('private', 'Private - Hidden')], default='tenants_only', help_text='Who can view this profile', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Public Profile',
                'verbose_name_plural': 'Public Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileFieldSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('tenant_uuid', models.UUIDField(db_index=True, help_text='UUID of tenant (not FK to avoid cross-schema issues)')),
                ('sync_display_name', models.BooleanField(default=True, help_text='Sync display name to tenant profile')),
                ('sync_avatar', models.BooleanField(default=True, help_text='Sync avatar to tenant profile')),
                ('sync_bio', models.BooleanField(default=True, help_text='Sync bio to tenant profile')),
                ('sync_public_email', models.BooleanField(default=False, help_text='Sync public email to tenant profile')),
                ('sync_phone', models.BooleanField(default=False, help_text='Sync phone to tenant profile')),
                ('sync_city', models.BooleanField(default=True, help_text='Sync city to tenant profile')),
                ('sync_state', models.BooleanField(default=True, help_text='Sync state/province to tenant profile')),
                ('sync_country', models.BooleanField(default=True, help_text='Sync country to tenant profile')),
                ('sync_linkedin', models.BooleanField(default=True, help_text='Sync LinkedIn URL to tenant profile')),
                ('sync_github', models.BooleanField(default=True, help_text='Sync GitHub URL to tenant profile')),
                ('sync_portfolio', models.BooleanField(default=True, help_text='Sync portfolio URL to tenant profile')),
                ('sync_skills', models.BooleanField(default=True, help_text='Sync skills to tenant profile')),
                ('sync_languages', models.BooleanField(default=True, help_text='Sync languages to tenant profile')),
                ('auto_sync', models.BooleanField(default=False, help_text='Automatically sync when public profile changes (NOT recommended)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_sync_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile Field Sync Settings',
                'verbose_name_plural': 'Profile Field Sync Settings',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'tenant_uuid')},
            },
        ),
    ]
