# Generated by Django 5.2.6 on 2025-10-10 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_account_u', '0002_customuser_anonymous_mode_customuser_mfa_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceproviderprofile',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='preferred_service_types',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='serviceproviderprofile',
            name='specialties',
        ),
        migrations.RemoveField(
            model_name='serviceproviderprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='CandidateProfile',
        ),
        migrations.DeleteModel(
            name='CertificationBadge',
        ),
        migrations.DeleteModel(
            name='ClientProfile',
        ),
        migrations.DeleteModel(
            name='EmployerProfile',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
        migrations.DeleteModel(
            name='ServiceProviderProfile',
        ),
        migrations.DeleteModel(
            name='StaffProfile',
        ),
    ]
